using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion9
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "407644",    "Computer Technologies Institute - Isabela",            "REGION IX",    "Basilan",  "City of Isabela" },
                new string[] { "402392",    "Juan S. Alano Memorial School, Inc.",          "REGION IX",    "City of Isabela",  "City of Isabela" },
                new string[] { "404908",    "Claret College of Isabela",            "REGION IX",    "City of Isabela",  "City of Isabela" },
                new string[] { "600155",    "Basilan State College-Main Campus",            "REGION IX",    "City of Isabela",  "City of Isabela" },
                new string[] { "455505",    "Coronado Bay Academy",             "REGION IX",    "Zamboanga del Norte",  "Baliguian" },
                new string[] { "404891",    "Rizal Memorial Institute of Dapitan City, Inc.",           "REGION IX",    "Zamboanga del Norte",  "Dapitan City" },
                new string[] { "406912",    "Mindanao Auto and Technical Skills Training Center, Inc.",             "REGION IX",    "Zamboanga del Norte",  "Dapitan City" },
                new string[] { "600084",    "Jose Rizal Memorial State University-Main Campus",             "REGION IX",    "Zamboanga del Norte",  "Dapitan City" },
                new string[] { "402395",    "STI College - Dipolog",            "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404892",    "Andres Bonifacio College",             "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404894",    "Dipolog Community School",             "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404895",    "Dipolog City Institute of Technology",             "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404896",    "DMC College Foundation Science High School",           "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404904",    "St. Mary's Academy-Dipolog City",          "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "404905",    "St. Vincent's College",            "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "406917",    "ZN Agri-Technical Institute, Inc.",            "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "457509",    "Global Springs of Learning Academy",           "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "600128",    "Jose Rizal Memorial State University-Dipolog Campus",          "REGION IX",    "Zamboanga del Norte",  "Dipolog City" },
                new string[] { "455502",    "Riverside Community School",           "REGION IX",    "Zamboanga del Norte",  "Gutalac" },
                new string[] { "600087",    "Jose Rizal Memorial State University-Katipunan Campus",            "REGION IX",    "Zamboanga del Norte",  "Katipunan" },
                new string[] { "404823",    "St. Mary's College of Labason",            "REGION IX",    "Zamboanga del Norte",  "Labason" },
                new string[] { "455503",    "Southern Peninsula College",           "REGION IX",    "Zamboanga del Norte",  "Labason" },
                new string[] { "402686",    "Ave Maria College",            "REGION IX",    "Zamboanga del Norte",  "Liloy" },
                new string[] { "404824",    "Liloy Technical Institute, Inc.",          "REGION IX",    "Zamboanga del Norte",  "Liloy" },
                new string[] { "404826",    "Saint Estanislao Kostka College, Inc.",            "REGION IX",    "Zamboanga del Norte",  "Manukan" },
                new string[] { "404827",    "Colegio de San Francisco Javier",          "REGION IX",    "Zamboanga del Norte",  "Rizal" },
                new string[] { "405507",    "Zamsula Everlasting College",          "REGION IX",    "Zamboanga del Norte",  "Salug" },
                new string[] { "404830",    "Philippine Advent College",            "REGION IX",    "Zamboanga del Norte",  "Sindangan" },
                new string[] { "404831",    "Saint Joseph College of Sindangan Incorporation",          "REGION IX",    "Zamboanga del Norte",  "Sindangan" },
                new string[] { "404832",    "Siocon Institute of Technology, Inc.",             "REGION IX",    "Zamboanga del Norte",  "Siocon" },
                new string[] { "600129",    "Jose Rizal Memorial State University-Siocon Campus",           "REGION IX",    "Zamboanga del Norte",  "Siocon" },
                new string[] { "600125",    "Jose Rizal Memorial State University-Tampilisan Campus",           "REGION IX",    "Zamboanga del Norte",  "Tampilisan" },
                new string[] { "404834",    "Aurora Pioneers Memorial College",             "REGION IX",    "Zamboanga del Sur",    "Aurora" },
                new string[] { "404837",    "Santa Teresita Academy",           "REGION IX",    "Zamboanga del Sur",    "Aurora" },
                new string[] { "408197",    "LGU of Aurora - Zoom Technical Vocational Training and Assessment Center, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Aurora" },
                new string[] { "(Blank)",   "Zamboanga del Sur Provincial Government College",          "REGION IX",    "Zamboanga del Sur",    "Aurora" },
                new string[] { "402396",    "Eastern Mindanao College of Technology",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402425",    "Lucan Central Colleges",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402550",    "Philippine Technological and Marine Sciences",             "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402587",    "STI College - Pagadian",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402609",    "Universidad de Zamboanga-Pagadian Branch",             "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402611",    "Yllana Bay View College",          "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "402692",    "Zamboanga del Sur Maritime Institute of Technology",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "404913",    "Holy Child Academy",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "404920",    "PJC High School",          "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "404921",    "Saint Columban College",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "404922",    "Southern Mindanao Colleges",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "405464",    "International College of Philsouth",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "405475",    "Southeast Asian Institute of Local Governance",            "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "405497",    "Zoom Technical-Vocational Training and Assessment Center, Inc.",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "406718",    "Medina College",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "406854",    "West Prime Horizon Institute, Inc.",           "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "458501",    "Pagadian Capitol College",             "REGION IX",    "Zamboanga del Sur",    "City of Pagadian" },
                new string[] { "404838",    "Pres. Garcia Memorial Institute of Technology",            "REGION IX",    "Zamboanga del Sur",    "Dinas" },
                new string[] { "404839",    "Immaculate Heart Academy",             "REGION IX",    "Zamboanga del Sur",    "Dumalinao" },
                new string[] { "404840",    "Maria Clara Lobregat Educational Foundation, Inc.",            "REGION IX",    "Zamboanga del Sur",    "Dumalinao" },
                new string[] { "404843",    "San Jose Academy",             "REGION IX",    "Zamboanga del Sur",    "Dumingag" },
                new string[] { "404846",    "Western Mindanao Adventist Academy",           "REGION IX",    "Zamboanga del Sur",    "Dumingag" },
                new string[] { "406866",    "Dumingag Institute of Sustainable Organic Agriculture",            "REGION IX",    "Zamboanga del Sur",    "Dumingag" },
                new string[] { "406867",    "Dumingag Technological Training School",           "REGION IX",    "Zamboanga del Sur",    "Dumingag" },
                new string[] { "456024",    "Alhadeetha Mindanao College (AMC), Inc.",          "REGION IX",    "Zamboanga del Sur",    "Labangan" },
                new string[] { "404849",    "Santa Maria Goretti College",          "REGION IX",    "Zamboanga del Sur",    "Mahayag" },
                new string[] { "405509",    "Pagadian Institute of Technology-Mahayag Branch",          "REGION IX",    "Zamboanga del Sur",    "Mahayag" },
                new string[] { "404851",    "Margosatubig Academy, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Margosatubig" },
                new string[] { "404852",    "Margosatubig Pax High School Kindergarten, Inc.",          "REGION IX",    "Zamboanga del Sur",    "Margosatubig" },
                new string[] { "407526",    "Margosatubig Friendship School of Arts and Trade",             "REGION IX",    "Zamboanga del Sur",    "Margosatubig" },
                new string[] { "404853",    "Holy Trinity High School",             "REGION IX",    "Zamboanga del Sur",    "Midsalip" },
                new string[] { "404854",    "Blancia College Foundation, Inc.",             "REGION IX",    "Zamboanga del Sur",    "Molave" },
                new string[] { "404857",    "Sacred Heart Diocesan School, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Molave" },
                new string[] { "404870",    "Immaculate Conception High School of Pitogo, Inc.",            "REGION IX",    "Zamboanga del Sur",    "Pitogo" },
                new string[] { "404859",    "Holy Family High School",          "REGION IX",    "Zamboanga del Sur",    "Ramon Magsaysay (Liargo)" },
                new string[] { "404861",    "Lourdes Academy",          "REGION IX",    "Zamboanga del Sur",    "San Miguel" },
                new string[] { "404863",    "Saint Andrew's Academy of San Pablo, Inc.",            "REGION IX",    "Zamboanga del Sur",    "San Pablo" },
                new string[] { "404864",    "Saint Ambrose High School, Inc.",          "REGION IX",    "Zamboanga del Sur",    "Tabina" },
                new string[] { "404865",    "San Isidro High School, Inc",          "REGION IX",    "Zamboanga del Sur",    "Tambulig" },
                new string[] { "405514",    "Pimentel Creative Arts Resource and Technological Institute Inc.",             "REGION IX",    "Zamboanga del Sur",    "Tambulig" },
                new string[] { "404868",    "Star of the Sea High School",          "REGION IX",    "Zamboanga del Sur",    "Tukuran" },
                new string[] { "456030",    "Hyrons College Philippines, Inc.",             "REGION IX",    "Zamboanga del Sur",    "Tukuran" },
                new string[] { "402632",    "AMA Computer College-Zamboanga City",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "402657",    "Computer Technologies Institute of Zamboanga City (COMTECH) Inc.",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "402664",    "Western Mindanao Cooperative College",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404923",    "Arturo Eustaquio Memorial Science High School",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404925",    "Ateneo de Zamboanga University",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404926",    "Bethany Child Development Center",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404927",    "Claret School of Zamboanga City",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404928",    "Creche Integrated Studies Centre, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404931",    "Ebenezer Bible College and Seminary",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404934",    "Filipino-Turkish Tolerance School",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404935",    "Good Shepherd Mission School",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404937",    "HMIJ Foundation - Philippine Islamic College, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404939",    "Immaculate Conception Archdiocesan School",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404941",    "Islamic Institute of the Philippines",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404942",    "J-Jireh School",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404945",    "MEIN College, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404946",    "Montessori de Zamboanga",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404948",    "Pilar College of Zamboanga City, Inc.",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404950",    "Zamboanga Hermosa Youth Academy, Inc.",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404951",    "Saint Joseph School-Zamboanga City",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404954",    "Southern City Colleges",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404955",    "Zamboanga Sto. Niño Village School",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404960",    "Immaculate Conception Archdiocesan School de Calarian",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404962",    "Universidad de Zamboanga Technical High School",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404963",    "Zamboanga Avalokitesvara School",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404965",    "Caldwell Adventist Academy",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404966",    "Zamboanga Chong Hua High School",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "405498",    "Universal College of Southeast Asia and the Pacific",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "407525",    "Universidad de Zamboanga",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "407786",    "Ayala Technical-Vocational School",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459013",    "Ferndale International School",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459030",    "Nuevo Zamboanga College, Inc.",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459039",    "Zamboanga Institute of Aviation and Technology",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459043",    "Global Technical School of Zamboanga, Inc.",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459044",    "Brent Hospital and Colleges Incorporated",             "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459046",    "STI College - Zamboanga",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "459048",    "Winzelle International College",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "600085",    "Zamboanga City State Polytechnic College-Main",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "600086",    "Zamboanga State College of Marine Sciences and Technology",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "600136",    "Western Mindanao State University",            "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "(Blank)",   "Vitali Technical Vocational School",           "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "(Blank)",   "Western Mindanao Foundation College",          "REGION IX",    "Zamboanga del Sur",    "Zamboanga City" },
                new string[] { "404872",    "Saint Paul School",            "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "404873",    "Western Mindanao Institute of Buug, Inc.",             "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "405526",    "Internacional Colegio De Tecnologia",          "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "405533",    "St. John College of Buug Foundation Incorporated",             "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "407404",    "St. John General Hospital & College, Inc.",            "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "456515",    "Seeds of Life Christian School of Buug, Inc.",             "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "600153",    "Mindanao State University-Buug",           "REGION IX",    "Zamboanga Sibugay",    "Buug" },
                new string[] { "404874",    "The Good Shepherd School of Imelda, Inc.",             "REGION IX",    "Zamboanga Sibugay",    "Imelda" },
                new string[] { "402685",    "Universidad de Zamboanga-Ipil Campus",             "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "404875",    "Dr. Aurelio Mendoza Memorial Colleges",            "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "404879",    "Marcelo Spinola School",           "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "404880",    "Marian College, Inc.",             "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "407005",    "Philippine Technological and Marine Sciences",             "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "456521",    "Aim High Colleges Incorporation",          "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "456529",    "Sibugay Technical Institute, Inc",             "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "456532",    "Medina College Ipil, Inc.",            "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "456534",    "Sibugay's Matthew-Jackson School, Inc.",           "REGION IX",    "Zamboanga Sibugay",    "Ipil" },
                new string[] { "404884",    "Xavier High School",           "REGION IX",    "Zamboanga Sibugay",    "Mabuhay" },
                new string[] { "600234",    "Western Mindanao State University-Mabuhay",            "REGION IX",    "Zamboanga Sibugay",    "Mabuhay" },
                new string[] { "404885",    "Malangas Institute",           "REGION IX",    "Zamboanga Sibugay",    "Malangas" },
                new string[] { "600154",    "Western Mindanao State University-Malangas",           "REGION IX",    "Zamboanga Sibugay",    "Malangas" },
                new string[] { "404888",    "Loyola High School",           "REGION IX",    "Zamboanga Sibugay",    "Olutanga" },
                new string[] { "600235",    "Western Mindanao State University - Olutanga",             "REGION IX",    "Zamboanga Sibugay",    "Olutanga" },
                new string[] { "407378",    "Zamboanga Peninsula Technical Colleges",           "REGION IX",    "Zamboanga Sibugay",    "Talusan" },
                new string[] { "407405",    "Asian Business Cooperative Academy",           "REGION IX",    "Zamboanga Sibugay",    "Talusan" },
                new string[] { "456520",    "Global Academy Institute of Technology Foundation, Inc.",          "REGION IX",    "Zamboanga Sibugay",    "Titay" },
            };
            return School;
        }
    }
}