using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion10
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "459533",    "The Abba's Orchard School",            "REGION X",     "Bukidnon",     "Baungon" },
                new string[] { "405082",    "Fr. Leoni Memorial School Inc. (Formerly Nuestra Sra. De Guadalupe High School)",          "REGION X",     "Bukidnon",     "Cabanglasan" },
                new string[] { "403708",    "STI Malaybalay",           "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "404977",    "Lake View Academy",            "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "405003",    "Mindanao Arts and Technological Institute",            "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "405006",    "San Isidro College",           "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "405008",    "Saint Isidore High School",            "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "459522",    "Marywoods Academy Inc.",           "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "600130",    "Bukidnon State University",            "REGION X",     "Bukidnon",     "City of Malaybalay" },
                new string[] { "400788",    "CFC-Valencia School of the Morning Star",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "400792",    "I.B.A College of Mindanao",            "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "400793",    "Valencia Baptist Christian Academy",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "403722",    "AMA Computer Learning Center-Valencia City",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "403723",    "STI Valencia",             "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405050",    "Bukidnon Faith Christian School, Inc.",            "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405053",    "Dagat Kidavao Christian Academy Foundation, Inc.",             "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405054",    "EMEU Gequillana Memorial Academy, Inc.",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405056",    "First Fruits Christian Academy",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405061",    "Infant Jesus School of Bukidnon",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405064",    "Lumbayao Technical Institute, Inc.",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405070",    "Philippine College Foundation",            "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405072",    "San Agustin Institute of Technology",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405073",    "San Jose High School of Sinayawan, Inc.",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "405078",    "Valencia Colleges, Inc.",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "407406",    "Saint Joseph High School of Valencia",             "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "407672",    "Mountain View College-Annex",          "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "459502",    "Mountain View College",            "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "459506",    "Sacred Heart Academy of Valencia, Inc.",           "REGION X",     "Bukidnon",     "City of Valencia" },
                new string[] { "404973",    "Xavier de Damulog High School",            "REGION X",     "Bukidnon",     "Damulog" },
                new string[] { "404974",    "Sto. Niño High School of Dangcagan, Inc.",             "REGION X",     "Bukidnon",     "Dangcagan" },
                new string[] { "404979",    "Southern Bukidnon Foundation Academy",             "REGION X",     "Bukidnon",     "Don Carlos" },
                new string[] { "407554",    "Loyola High School",           "REGION X",     "Bukidnon",     "Don Carlos" },
                new string[] { "407668",    "Don Carlos Polytechnic College",           "REGION X",     "Bukidnon",     "Don Carlos" },
                new string[] { "404981",    "San Isidro High School (Kadingilan)",          "REGION X",     "Bukidnon",     "Kadingilan" },
                new string[] { "404983",    "Kalilangan Pioneering Institute, Inc",             "REGION X",     "Bukidnon",     "Kalilangan" },
                new string[] { "404984",    "Cultural Mission Academy",             "REGION X",     "Bukidnon",     "Kibawe" },
                new string[] { "404986",    "Madana Mohana Academy",            "REGION X",     "Bukidnon",     "Kibawe" },
                new string[] { "404988",    "Roman C. Villalon Memorial Colleges Foundation, Inc.",             "REGION X",     "Bukidnon",     "Kibawe" },
                new string[] { "404989",    "Stella Matutina Academy",          "REGION X",     "Bukidnon",     "Kibawe" },
                new string[] { "459579",    "Exodus Tri-Power International School, Inc.",          "REGION X",     "Bukidnon",     "Kibawe" },
                new string[] { "459545",    "Philippine WideContinuing Distance Education System",          "REGION X",     "Bukidnon",     "Kitaotao" },
                new string[] { "404993",    "San Herminigildo Agro-Industrial School",          "REGION X",     "Bukidnon",     "Lantapan" },
                new string[] { "404994",    "Xavier de Kibangay High School",           "REGION X",     "Bukidnon",     "Lantapan" },
                new string[] { "405012",    "St. Paul Academy-Malitbog",            "REGION X",     "Bukidnon",     "Malitbog" },
                new string[] { "404972",    "St. Jude Thaddeus Academy",            "REGION X",     "Bukidnon",     "Manolo Fortrich" },
                new string[] { "405014",    "Holy Cross High School",           "REGION X",     "Bukidnon",     "Manolo Fortrich" },
                new string[] { "405021",    "Our Lady of Fatima High School-Dagumbaan",             "REGION X",     "Bukidnon",     "Maramag" },
                new string[] { "405022",    "Philippine Countryville College, Inc.",            "REGION X",     "Bukidnon",     "Maramag" },
                new string[] { "405023",    "San Andres High School",           "REGION X",     "Bukidnon",     "Maramag" },
                new string[] { "407603",    "Southern Maramag Colleges",            "REGION X",     "Bukidnon",     "Maramag" },
                new string[] { "600152",    "Central Mindanao University Laboratory High School",           "REGION X",     "Bukidnon",     "Maramag" },
                new string[] { "600272",    "Central Mindanao University",          "REGION X",     "Bukidnon",     "Musuan" },
                new string[] { "405026",    "Pangantucan Community High School",            "REGION X",     "Bukidnon",     "Pangantucan" },
                new string[] { "405027",    "San Isidro High School of Malipayon, Inc.",            "REGION X",     "Bukidnon",     "Pangantucan" },
                new string[] { "405028",    "BUSCO Academy Multi-Purpose Cooperative",          "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "405032",    "Nuestra Senora del Pilar High School",             "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "405033",    "Puntian Academy",          "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "405036",    "Quezon Institute of Technology",           "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "459528",    "Sulads Comprehensive High School for the Lumads",          "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "459537",    "Lumintao Saint Vincent Ferrer Academy, Inc.",          "REGION X",     "Bukidnon",     "Quezon" },
                new string[] { "405039",    "San Fernando Christian Academy",           "REGION X",     "Bukidnon",     "San Fernando" },
                new string[] { "405040",    "Kalagangan Academy",           "REGION X",     "Bukidnon",     "San Fernando" },
                new string[] { "405041",    "San Fernando Community College, Inc.",             "REGION X",     "Bukidnon",     "San Fernando" },
                new string[] { "459524",    "Divine Mercy School of Bukidnon, Inc",             "REGION X",     "Bukidnon",     "San Fernando" },
                new string[] { "405042",    "Pilar High School",            "REGION X",     "Bukidnon",     "Sumilao" },
                new string[] { "459538",    "Sumilao Bukidnon Tribal Academy",          "REGION X",     "Bukidnon",     "Sumilao" },
                new string[] { "404990",    "Western Bukidnon Academy, Inc.",           "REGION X",     "Bukidnon",     "Talakag" },
                new string[] { "405043",    "Bethany Christian School",             "REGION X",     "Bukidnon",     "Talakag" },
                new string[] { "405044",    "Saint Joseph High School of Talakag",          "REGION X",     "Bukidnon",     "Talakag" },
                new string[] { "459578",    "St. Therese School of Miarayon",           "REGION X",     "Bukidnon",     "Talakag" },
                new string[] { "405084",    "Columbia St. Michael's Parish High School",            "REGION X",     "Camiguin",     "Mahinog" },
                new string[] { "405087",    "Fatima College of Camiguin",           "REGION X",     "Camiguin",     "Mambajao (Capital)" },
                new string[] { "405091",    "Holy Rosary Academy of Camiguin",          "REGION X",     "Camiguin",     "Sagay" },
                new string[] { "405092",    "Laubach Institute",            "REGION X",     "Lanao del Norte",  "Bacolod" },
                new string[] { "405093",    "Santo Niño High School-Bacolod",           "REGION X",     "Lanao del Norte",  "Bacolod" },
                new string[] { "405094",    "Momungan Academy",             "REGION X",     "Lanao del Norte",  "Baloi" },
                new string[] { "460509",    "West Eastern Philippine College, Inc.",            "REGION X",     "Lanao del Norte",  "Baloi" },
                new string[] { "405096",    "Santo Niño Academy",           "REGION X",     "Lanao del Norte",  "Baroy" },
                new string[] { "405753",    "Lanao School of Science and Technology, Inc.-Baroy",           "REGION X",     "Lanao del Norte",  "Baroy" },
                new string[] { "403698",    "STI Iligan",           "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "403704",    "Sto. Niño Academy of Iligan City",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405280",    "Christian Horizon School",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405281",    "Corpus Christi Parochial School",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405283",    "Holy Family School of Iligan, Inc.",           "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405285",    "Iligan Capitol College, Inc",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405286",    "Iligan Medical Center College",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405287",    "La Salle Academy",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405288",    "Lanao Chung Hua School",           "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405296",    "Sacred Heart High School",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405298",    "St. Catherine Academy, Inc.",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405301",    "St. Michael's College",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405302",    "St. Peter's College",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405303",    "St. Therese Community of Learners-Iligan City",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405750",    "Adventist Medical Center College",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405751",    "Iligan Computer Institute-Iligan City",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "406602",    "Iligan Access Institute of Technology, Inc.",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "406607",    "Iligan International Institute of Technology, Inc",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407039",    "St. Laurence Institute of Technology",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407077",    "Masters Technology Institute of Mindanao, Inc.",           "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407361",    "Iligan Multi-Skills Development Institute, Inc.",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407407",    "Lyceum of Iligan Foundation",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407559",    "Bethany Baptist Academy",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "407670",    "Integrated Developmental School",          "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "460505",    "MSU-IIT:Integrated Development School",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "463004",    "ICTI Polytechnic College, Inc.",           "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "463009",    "MSU-IIT Coop Academy",             "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "463030",    "St. Paul's Institute of Technology of Iligan City",            "REGION X",     "Lanao del Norte",  "Iligan City" },
                new string[] { "405099",    "Saint Francis Xavier Academy",             "REGION X",     "Lanao del Norte",  "Kapatagan" },
                new string[] { "405752",    "Iligan Computer Institute, Inc.-Kapatagan",            "REGION X",     "Lanao del Norte",  "Kapatagan" },
                new string[] { "460530",    "Lanao School of Science and Technology, Inc.-Kapatagan",           "REGION X",     "Lanao del Norte",  "Kapatagan" },
                new string[] { "405101",    "St. Vincent's Academy",            "REGION X",     "Lanao del Norte",  "Kauswagan" },
                new string[] { "407560",    "Holy Cross High School",           "REGION X",     "Lanao del Norte",  "Kolambugan" },
                new string[] { "405095",    "Lanao School of Science and Technology, Inc.-Lala",            "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405097",    "North Central Mindanao College",           "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405103",    "Bible Baptist Christian Academy of Maranding",             "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405104",    "Christ the King College de Maranding",             "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405105",    "Lanipao Catholic High School",             "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405106",    "South Western Career College",             "REGION X",     "Lanao del Norte",  "Lala" },
                new string[] { "405109",    "Our Lady of Perpetual Help Academy",           "REGION X",     "Lanao del Norte",  "Linamon" },
                new string[] { "600093",    "Mindanao State University - Maigo School of Arts and Trades",          "REGION X",     "Lanao del Norte",  "Maigo" },
                new string[] { "405110",    "St. Joseph's Community High School",           "REGION X",     "Lanao del Norte",  "Sapad" },
                new string[] { "600094",    "MSU-Lanao del Norte Agricultural College",             "REGION X",     "Lanao del Norte",  "Sultan Naga Dimaporo" },
                new string[] { "405112",    "Mercy Junior College",             "REGION X",     "Lanao del Norte",  "Tubod (Capital)" },
                new string[] { "405114",    "Saint Matthew's High School",          "REGION X",     "Misamis Occidental",   "Aloran" },
                new string[] { "407563",    "Mount Carmel High School",             "REGION X",     "Misamis Occidental",   "Baliangao" },
                new string[] { "405116",    "Farmers' Institute-UCCP, Inc.",            "REGION X",     "Misamis Occidental",   "Bonifacio" },
                new string[] { "405117",    "St. Vincent's High School",            "REGION X",     "Misamis Occidental",   "Bonifacio" },
                new string[] { "405119",    "Liberation Institute",             "REGION X",     "Misamis Occidental",   "Calamba" },
                new string[] { "405121",    "Sacred Heart College of Calamba, Inc.",            "REGION X",     "Misamis Occidental",   "Calamba" },
                new string[] { "405754",    "College of Communication, Information & Technology",           "REGION X",     "Misamis Occidental",   "Calamba" },
                new string[] { "405123",    "Jimenez Bethel Institute",             "REGION X",     "Misamis Occidental",   "Jimenez" },
                new string[] { "405125",    "School of Saint John the Baptist",             "REGION X",     "Misamis Occidental",   "Jimenez" },
                new string[] { "405127",    "St. Francis Xavier High School",           "REGION X",     "Misamis Occidental",   "Lopez Jaena" },
                new string[] { "461014",    "Immanuel Adventist Academy",           "REGION X",     "Misamis Occidental",   "Lopez Jaena" },
                new string[] { "405129",    "Misamis University-Oroquieta City",            "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "405131",    "Southern Capital Colleges",            "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "405757",    "Misamis Occidental Technological Institute",           "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "407066",    "National Institute for Technical Excellence, Inc.",            "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "407409",    "C-LAN Institute of Technology",            "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "407564",    "Stella Maris College",             "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "(Blank)",   "Deor&Dune Academe School of Technology, Inc.",             "REGION X",     "Misamis Occidental",   "Oroquieta City" },
                new string[] { "403718",    "Our Lady of Triumph Institute of Technology",          "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405309",    "Firm Foundation Christian Academy",            "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405311",    "Lighthouse Christian Academy",             "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405312",    "Medina College",           "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405313",    "Misamis Institute of Technology, Inc.",            "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405314",    "Misamis Union High School",            "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405315",    "Misamis University-Ozamiz City",           "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405316",    "Ozamiz Montessori Center",             "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "407410",    "Northwestern Mindanao Institute of Technology",            "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "407973",    "Misamis Institute of Technology",          "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "463507",    "La Salle University-Ozamiz Integrated School",             "REGION X",     "Misamis Occidental",   "Ozamiz City" },
                new string[] { "405134",    "Panaon Community High School",             "REGION X",     "Misamis Occidental",   "Panaon" },
                new string[] { "405135",    "Saint Nicholas School of Plaridel",            "REGION X",     "Misamis Occidental",   "Plaridel" },
                new string[] { "405136",    "St. Patrick's High School",            "REGION X",     "Misamis Occidental",   "Plaridel" },
                new string[] { "407408",    "Medina Foundation College",            "REGION X",     "Misamis Occidental",   "Sapang Dalaga" },
                new string[] { "407561",    "Holy Child High School",           "REGION X",     "Misamis Occidental",   "Sapang Dalaga" },
                new string[] { "407562",    "Holy Rosary Academy",          "REGION X",     "Misamis Occidental",   "Sapang Dalaga" },
                new string[] { "405138",    "St. Joseph's High School",             "REGION X",     "Misamis Occidental",   "Sinacaban" },
                new string[] { "403720",    "Gov. Alfonso D. Tan College of Tangub City",           "REGION X",     "Misamis Occidental",   "Tangub City" },
                new string[] { "405009",    "St. Michael's High School",            "REGION X",     "Misamis Occidental",   "Tangub City" },
                new string[] { "600097",    "Northwestern Mindanao State College of Science and Technology",            "REGION X",     "Misamis Occidental",   "Tangub City" },
                new string[] { "405139",    "Northwestern Mindanao Christian College, Inc.",            "REGION X",     "Misamis Occidental",   "Tudela" },
                new string[] { "405140",    "San Isidro Academy",           "REGION X",     "Misamis Occidental",   "Tudela" },
                new string[] { "405143",    "St. Peter's College of Balingasag",            "REGION X",     "Misamis Oriental",     "Balingasag" },
                new string[] { "405144",    "St. Rita's College of Balingasag",             "REGION X",     "Misamis Oriental",     "Balingasag" },
                new string[] { "461501",    "Misamis Oriental Institute of Science and Technology",             "REGION X",     "Misamis Oriental",     "Balingasag" },
                new string[] { "459532",    "Promise Mountain Christian Academy",           "REGION X",     "Misamis Oriental",     "Cabanglasan" },
                new string[] { "403651",    "AMA Computer College-Cagayan de Oro City",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "403652",    "Informatics Institute-Cagayan de Oro City",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "403655",    "PHINMA Cagayan De Oro College, Puerto Campus",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "403659",    "Skills Mastery Institute",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "403663",    "STI College - Cagayan de Oro",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "403665",    "Vineyard International Polytechnic College",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405191",    "Blessed Mother College-Iponan",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405197",    "Capitol University",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405199",    "Cagayan de Oro City College-PHINMA",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405207",    "Corpus Christi School",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405212",    "The Fisher Valley Academy",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405216",    "Golden Heritage Polytechnic College",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405221",    "Immanuel Mission International School",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405226",    "Kong Hua School",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405228",    "Liceo de Cagayan University",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405231",    "Lourdes College",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405235",    "Merry Child School",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405236",    "Millenium Christian Academy",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405238",    "Montessori De Oro",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405246",    "Oro Christian Grace School",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405250",    "Philippine Southfield School",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405252",    "Pilgrim Christian College",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405254",    "Rosevale School Foundation, Inc.",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405256",    "Sacred Heart of Jesus Montessori School - Recto Campus",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405257",    "Shekinah Glory Christian Academy",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405258",    "Southern De Oro Philippines College",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405260",    "St. Mary's School",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405268",    "Xavier University-Ateneo de Cagayan",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405745",    "Asian Business Cabletow Cooperative Academy",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405746",    "Blessed Mother College-Opol Campus",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405748",    "Iligan Computer Institute-Cagayan de Oro City",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405749",    "Professional World Academy-Misamis",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "406443",    "1 and All Technical School",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "407086",    "Christian Samaritan Health Services and Technical School, Inc",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "407555",    "Blessed Mother College, Tiano Kalambaguhan",           "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "407556",    "Sacred Heart Academy",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "407557",    "St. Mary's Academy of Carmen",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "407669",    "Blessed Mother College-Centro Iponan Campus",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462024",    "Sacred Heart of Jesus Montessori School",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462028",    "Nanuri International School",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462045",    "King of Zion School CDO Inc.",             "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462047",    "Westshire Academy",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462049",    "Corpus Christi School-Pueblo Campus",          "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "462052",    "United Peace International School",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "600273",    "Mindanao University of Science and Technology",            "REGION X",     "Misamis Oriental",     "Cagayan de Oro City" },
                new string[] { "405146",    "The New El Salvador Colleges",             "REGION X",     "Misamis Oriental",     "City of El Salvador" },
                new string[] { "405148",    "St. Joseph Academy of El Salvador",            "REGION X",     "Misamis Oriental",     "City of El Salvador" },
                new string[] { "461516",    "Doalnara Agricultural Academy",            "REGION X",     "Misamis Oriental",     "Claveria" },
                new string[] { "600096",    "Misamis Oriental State College of Agriculture and Technology",             "REGION X",     "Misamis Oriental",     "Claveria" },
                new string[] { "405270",    "Gingoog Christian College",            "REGION X",     "Misamis Oriental",     "Gingoog City" },
                new string[] { "405271",    "Gingoog City Colleges",            "REGION X",     "Misamis Oriental",     "Gingoog City" },
                new string[] { "407558",    "Christ the King College",          "REGION X",     "Misamis Oriental",     "Gingoog City" },
                new string[] { "462505",    "Mt. Sioan Academy",            "REGION X",     "Misamis Oriental",     "Gingoog City" },
                new string[] { "461519",    "Prophet's Pen Academy",            "REGION X",     "Misamis Oriental",     "Gitagum" },
                new string[] { "405152",    "Xavier Academy of Initao",             "REGION X",     "Misamis Oriental",     "Initao" },
                new string[] { "405153",    "Colegio de Santo Niño de Jasaan",          "REGION X",     "Misamis Oriental",     "Jasaan" },
                new string[] { "407597",    "Holy Child High School",           "REGION X",     "Misamis Oriental",     "Kinoguitan" },
                new string[] { "405162",    "San Roque Parish High School",             "REGION X",     "Misamis Oriental",     "Magsaysay (Linugos)" },
                new string[] { "461507",    "Trinity College of Science and Technology, Inc.",          "REGION X",     "Misamis Oriental",     "Magsaysay (Linugos)" },
                new string[] { "405164",    "Mindanao Mission Academy",             "REGION X",     "Misamis Oriental",     "Manticao" },
                new string[] { "405168",    "St. Isidore School",           "REGION X",     "Misamis Oriental",     "Medina" },
                new string[] { "600095",    "Mindanao State University-Naawan",             "REGION X",     "Misamis Oriental",     "Naawan" },
                new string[] { "403714",    "Opol Community College",           "REGION X",     "Misamis Oriental",     "Opol" },
                new string[] { "403717",    "Tagoloan Community College",           "REGION X",     "Misamis Oriental",     "Tagoloan" },
                new string[] { "405755",    "St. Ignatius Technical College",           "REGION X",     "Misamis Oriental",     "Tagoloan" },
                new string[] { "405185",    "Regina Angelorum School of Villanueva Inc.",           "REGION X",     "Misamis Oriental",     "Villanueva" },
            };
            return School;
        }
    }
}