using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion8
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "404732",    "St. Magdalena of Canossa Catholic High School",            "REGION VIIII",     "Eastern Samar",    "Arteche" },
                new string[] { "404733",    "MSH Sisters of Academy of Balangiga, Inc.",            "REGION VIII",  "Eastern Samar",    "Balangiga" },
                new string[] { "407643",    "Eastern Samar State University-Can-Avid",          "REGION VIII",  "Eastern Samar",    "Can-avid" },
                new string[] { "404735",    "MSH Sisters Academy, Inc.-Borongan City",          "REGION VIII",  "Eastern Samar",    "City of Borongan" },
                new string[] { "404736",    "Seminario De Jesus Nazareno",          "REGION VIII",  "Eastern Samar",    "City of Borongan" },
                new string[] { "404737",    "St. Mary's College of Borongan",           "REGION VIII",  "Eastern Samar",    "City of Borongan" },
                new string[] { "407212",    "Don Bosco Training Center",            "REGION VIII",  "Eastern Samar",    "City of Borongan" },
                new string[] { "600264",    "Eastern Samar State University-Borongan Campus",           "REGION VIII",  "Eastern Samar",    "City of Borongan" },
                new string[] { "404738",    "Mater Divinae Gratiae College",            "REGION VIII",  "Eastern Samar",    "Dolores" },
                new string[] { "404740",    "Immaculate Conception School",             "REGION VIII",  "Eastern Samar",    "Guiuan" },
                new string[] { "404741",    "MSH Sisters Academy of Guiuan, Inc.",          "REGION VIII",  "Eastern Samar",    "Guiuan" },
                new string[] { "404742",    "St. Mary's Academy of Guiuan, Inc.",           "REGION VIII",  "Eastern Samar",    "Guiuan" },
                new string[] { "600265",    "Eastern Samar State University-Guiuan",            "REGION VIII",  "Eastern Samar",    "Guiuan" },
                new string[] { "404743",    "Divine Child Academy",             "REGION VIII",  "Eastern Samar",    "Lawaan" },
                new string[] { "404744",    "St. Anthony's Academy, Inc.",          "REGION VIII",  "Eastern Samar",    "Llorente" },
                new string[] { "600266",    "Eastern Samar State University-Maydolong",             "REGION VIII",  "Eastern Samar",    "Maydolong" },
                new string[] { "600267",    "Eastern Samar State University-Salcedo",           "REGION VIII",  "Eastern Samar",    "Salcedo" },
                new string[] { "404749",    "Loyola Academy",           "REGION VIII",  "Eastern Samar",    "Sulat" },
                new string[] { "403574",    "Abuyog Community College",             "REGION VIII",  "Leyte",    "Abuyog" },
                new string[] { "403592",    "Visayas Christian Institute of Technology",            "REGION VIII",  "Leyte",    "Abuyog" },
                new string[] { "404647",    "Abuyog Academy",           "REGION VIII",  "Leyte",    "Abuyog" },
                new string[] { "404649",    "Notre Dame of Abuyog",             "REGION VIII",  "Leyte",    "Abuyog" },
                new string[] { "404651",    "Holy Trinity College-A.R of Alang-alang Leyte",            "REGION VIII",  "Leyte",    "Alangalang" },
                new string[] { "404652",    "Albuera Private High School",          "REGION VIII",  "Leyte",    "Albuera" },
                new string[] { "451533",    "Saint Joseph Academy of Barugo, Inc.",             "REGION VIII",  "Leyte",    "Barugo" },
                new string[] { "404657",    "Bato Institute of Science and Technology, Inc.",           "REGION VIII",  "Leyte",    "Bato" },
                new string[] { "404667",    "Holy Cross College of Carigara",           "REGION VIII",  "Leyte",    "Carigara" },
                new string[] { "404661",    "Franciscan College of the Immaculate Conception",          "REGION VIII",  "Leyte",    "City of Baybay" },
                new string[] { "405744",    "Acedilla Technological Institute Foundation Incorporated",             "REGION VIII",  "Leyte",    "City of Baybay" },
                new string[] { "406893",    "Palermo Hotel Institute of Tourism and Hospitality, Inc.",             "REGION VIII",  "Leyte",    "City of Baybay" },
                new string[] { "600126",    "Visayas State University",             "REGION VIII",  "Leyte",    "City of Baybay" },
                new string[] { "404669",    "Grelina Osmeña Christian College Inc.",            "REGION VIII",  "Leyte",    "Hilongos" },
                new string[] { "404671",    "Saint Teresa School of Hilongos, Inc.",            "REGION VIII",  "Leyte",    "Hilongos" },
                new string[] { "451504",    "MLG College of Learning",          "REGION VIII",  "Leyte",    "Hilongos" },
                new string[] { "404675",    "Saint Michael College of Hindang, Leyte Inc.",             "REGION VIII",  "Leyte",    "Hindang" },
                new string[] { "404681",    "Holy Child Parish School of Isabel, Inc",          "REGION VIII",  "Leyte",    "Isabel" },
                new string[] { "404683",    "LIDE Learning Center, Inc.",           "REGION VIII",  "Leyte",    "Isabel" },
                new string[] { "404685",    "Notre Dame of Jaro",           "REGION VIII",  "Leyte",    "Jaro" },
                new string[] { "404686",    "East Visayan Adventist Academy of Leyte, Inc.",            "REGION VIII",  "Leyte",    "Javier (Bugho)" },
                new string[] { "404687",    "National Heroes Institute, Inc.",          "REGION VIII",  "Leyte",    "Kananga" },
                new string[] { "407666",    "Jose Navarro Polytechnic College",             "REGION VIII",  "Leyte",    "Kananga" },
                new string[] { "404691",    "Saint Joseph Academy of Leyte, Inc.",          "REGION VIII",  "Leyte",    "Matalom" },
                new string[] { "404644",    "Cathedral School of La Naval",             "REGION VIII",  "Leyte",    "Naval" },
                new string[] { "404645",    "Limpiado Memorial Foundation, Inc-Lightbringer Learning Center",           "REGION VIII",  "Leyte",    "Naval" },
                new string[] { "600074",    "Naval State University",           "REGION VIII",  "Leyte",    "Naval" },
                new string[] { "403616",    "ACLC College of Ormoc City",           "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "403619",    "San Lorenzo Ruiz College of Ormoc",            "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "403620",    "STI College - Ormoc",          "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "404790",    "St. Paul's School of Ormoc Foundation, Inc.",          "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "404791",    "St. Peter's College of Ormoc",             "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "404794",    "Sto. Niño College of Ormoc",           "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "404795",    "Western Leyte College of Ormoc City Inc.",             "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "406906",    "Ormoc City Institute of Technology",           "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "407352",    "St. Aloysius Institute of Technology",             "REGION VIII",  "Leyte",    "Ormoc City" },
                new string[] { "403591",    "Saint Paul School of Business and Law",            "REGION VIII",  "Leyte",    "Palo" },
                new string[] { "404694",    "Bethel International School",          "REGION VIII",  "Leyte",    "Palo" },
                new string[] { "404695",    "Sacred Heart Seminary",            "REGION VIII",  "Leyte",    "Palo" },
                new string[] { "404696",    "St. Mary's Academy of Palo",           "REGION VIII",  "Leyte",    "Palo" },
                new string[] { "404698",    "Colegio de San Francisco Javier, Inc.",            "REGION VIII",  "Leyte",    "Palompon" },
                new string[] { "404700",    "Northern Leyte College",           "REGION VIII",  "Leyte",    "Palompon" },
                new string[] { "451532",    "Palompon Institute of Technology",             "REGION VIII",  "Leyte",    "Palompon" },
                new string[] { "404701",    "John F. Kennedy Memorial Foundation School, Inc.",             "REGION VIII",  "Leyte",    "San Isidro" },
                new string[] { "406964",    "Colegio de Sta. Lourdes of Leyte Foundation, Inc.",            "REGION VIII",  "Leyte",    "Tabontabon" },
                new string[] { "407353",    "Arc Angelus Civitas School, Inc.",             "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "403565",    "AMA Computer College-Tacloban City",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "403623",    "ABE International College of Business and Economics-Tacloban City",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "403624",    "ACLC College of Tacloban City",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "403632",    "Colegio de la Salle Foundation de Tacloban, Inc.",             "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "403634",    "Dr. V. Orestes Romualdez Educational Foundation, Inc.",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404797",    "Asian Development Foundation College",             "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404799",    "Antonia Vargas Salino School Foundatin, Inc. (Eastern Visayas College Preparatory School)",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404801",    "Holy Infant College",          "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404802",    "Holy Virgin of Salvacion School, Inc.",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404804",    "Leyte Colleges",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404805",    "Leyte Progressive High School",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404814",    "St. Therese Christian Development Center Foundation, Inc.",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404815",    "St. Therese Educational Foundation of Tacloban, Inc.",             "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404818",    "Tacloban Angelicum Learning Center",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "406911",    "Datamex Institute of Computer Technology-Tacloban City",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "407293",    "Tacloban Institute of Electronics",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "407377",    "Tacloban Central Institute of Technical Studies, Inc.",            "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "407553",    "Sacred Heart School",          "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "455004",    "Liceo del Verbo Divino",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "455010",    "JE Mondejar Computer College, Inc.",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "455012",    "St. Scholastica's College Tacloban",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "455014",    "Cambridge Center for International Studies - EV Phils., Inc. (CIE)",           "REGION VIII",  "Leyte",    "Tacloban City" },
                new string[] { "404705",    "Holy Child High School",           "REGION VIII",  "Leyte",    "Villaba" },
                new string[] { "404706",    "Villaba Vocational High School",           "REGION VIII",  "Leyte",    "Villaba" },
                new string[] { "404751",    "Saint Francis College",            "REGION VIII",  "Northern Samar",   "Allen" },
                new string[] { "453009",    "Asia College of Advance Studies in Arts, Sciences, and Technology, Inc.",          "REGION VIII",  "Northern Samar",   "Bobon" },
                new string[] { "403596",    "Global School for Technological Studies, Inc.",            "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "403615",    "Lt. Jacob O. Meimban Memorial Foundation Eastern Visayas College, Inc.",           "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "404754",    "Colegio de San Lorenzo Ruiz de Manila of Northern Samar, Inc.",            "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "404756",    "Northern Samar Colleges",          "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "406597",    "Saint Anthony Farm Institute of Technology",           "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "407552",    "St. Michael Academy",          "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "453012",    "East Pacific Computer College",            "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "600077",    "University of Eastern Philippines-Catarman",           "REGION VIII",  "Northern Samar",   "Catarman" },
                new string[] { "404760",    "Fair Gems Academy, Inc.",          "REGION VIII",  "Northern Samar",   "Catubig" },
                new string[] { "453024",    "University of Eastern Philippines, Pedro Rebadulla Memorial Campus",           "REGION VIII",  "Northern Samar",   "Catubig" },
                new string[] { "404761",    "Colegio de Santa Teresita de Laoang, Inc.",            "REGION VIII",  "Northern Samar",   "Laoang" },
                new string[] { "600079",    "University of Eastern Philippines Laoang Laboratory High School",          "REGION VIII",  "Northern Samar",   "Laoang" },
                new string[] { "407667",    "Colegio de Las Navas",             "REGION VIII",  "Northern Samar",   "Las Navas" },
                new string[] { "404763",    "Barobaybay Academy, Inc.",             "REGION VIII",  "Northern Samar",   "Lavezares" },
                new string[] { "404764",    "Holy Family Center of Studies Foundation Inc.",            "REGION VIII",  "Northern Samar",   "Lavezares" },
                new string[] { "453001",    "Colegio de San Juan Samar",            "REGION VIII",  "Northern Samar",   "Lavezares" },
                new string[] { "403645",    "John Paul Seminary House of Formation",            "REGION VIII",  "Northern Samar",   "Mondragon" },
                new string[] { "404765",    "St. Anthony Academy",          "REGION VIII",  "Northern Samar",   "Mondragon" },
                new string[] { "404766",    "Pearl Island Academy Foundation Inc.",             "REGION VIII",  "Northern Samar",   "San Antonio" },
                new string[] { "453011",    "Tan Ting Bing Memorial Colleges Foundation, Inc.",             "REGION VIII",  "Northern Samar",   "San Isidro" },
                new string[] { "453503",    "MSH Sisters Academy of Basey, Inc",            "REGION VIII",  "Samar",    "Basey" },
                new string[] { "403573",    "STI Calbayog",             "REGION VIII",  "Samar",    "Calbayog City" },
                new string[] { "404781",    "La Milagrosa Academy",             "REGION VIII",  "Samar",    "Calbayog City" },
                new string[] { "406897",    "ACLC College of Calbayog",             "REGION VIII",  "Samar",    "Calbayog City" },
                new string[] { "406902",    "Samar College of Science and Technology",          "REGION VIII",  "Samar",    "Calbayog City" },
                new string[] { "407551",    "Christ the King College",          "REGION VIII",  "Samar",    "Calbayog City" },
                new string[] { "404772",    "Samar Colleges",           "REGION VIII",  "Samar",    "City of Calbayog (Capital)" },
                new string[] { "404775",    "St. Mary's College of Catbalogan",             "REGION VIII",  "Samar",    "City of Calbayog (Capital)" },
                new string[] { "404777",    "St. Michael's High School",            "REGION VIII",  "Samar",    "Gandara" },
                new string[] { "404707",    "Saint Anthony's High School of Anahawan Southern Leyte, Inc.",             "REGION VIII",  "Southern Leyte",   "Anahawan" },
                new string[] { "403593",    "Maasin City College",          "REGION VIII",  "Southern Leyte",   "City of Maasin (Capital)" },
                new string[] { "403595",    "STI Maasin",           "REGION VIII",  "Southern Leyte",   "City of Maasin (Capital)" },
                new string[] { "404716",    "Maasin Christian Academy",             "REGION VIII",  "Southern Leyte",   "City of Maasin (Capital)" },
                new string[] { "404717",    "Saint Joseph College, Maasin, Leyte",          "REGION VIII",  "Southern Leyte",   "City of Maasin (Capital)" },
                new string[] { "404718",    "The College of Maasin",            "REGION VIII",  "Southern Leyte",   "City of Maasin (Capital)" },
                new string[] { "404711",    "Holy Rosary Academy of Hinunangan, Inc.",          "REGION VIII",  "Southern Leyte",   "Hinunangan" },
                new string[] { "600268",    "Southern Leyte State University-Hinunangan",           "REGION VIII",  "Southern Leyte",   "Hinunangan" },
                new string[] { "404710",    "Hinundayan Catholic Institute, Inc.",          "REGION VIII",  "Southern Leyte",   "Hinundayan" },
                new string[] { "404712",    "Libagon Academy Foundation, Inc.",             "REGION VIII",  "Southern Leyte",   "Libagon" },
                new string[] { "404714",    "Saint Ignatius Loyola Academy Inc.",           "REGION VIII",  "Southern Leyte",   "Liloan" },
                new string[] { "404720",    "Maci-Jose K. Demetrio Learning Foundation, Inc.",          "REGION VIII",  "Southern Leyte",   "Macrohon" },
                new string[] { "404721",    "Santo Niño Academy",           "REGION VIII",  "Southern Leyte",   "Malitbog" },
                new string[] { "404722",    "St. James College of Padre Burgos Southern Leyte, Inc",            "REGION VIII",  "Southern Leyte",   "Padre Burgos" },
                new string[] { "404723",    "The Cristo Rey Regional High School, Inc.",            "REGION VIII",  "Southern Leyte",   "Saint Bernard" },
                new string[] { "600269",    "Southern Leyte State University-San Juan",             "REGION VIII",  "Southern Leyte",   "San Juan (Cabalian)" },
                new string[] { "404729",    "Saint Thomas Aquinas College",             "REGION VIII",  "Southern Leyte",   "Sogod" },
                new string[] { "600270",    "Southern Leyte State University - Main Campus",            "REGION VIII",  "Southern Leyte",   "Sogod" },
                new string[] { "404730",    "Dr. Rath Memorial Institute Foundation, Inc.",             "REGION VIII",  "Southern Leyte",   "Tomas Oppus" },
                new string[] { "600080",    "Southern Leyte State University-Tomas Oppus",          "REGION VIII",  "Southern Leyte",   "Tomas Oppus" },

            };
            return School;
        }
    }
}