using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion6
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "403198",    "Altavas College",                                                                                  "REGION VI",    "Aklan",    "Altavas" },
                new string[] { "403919",    "Balete Academy, Inc.",                                                                             "REGION VI",    "Aklan",    "Balete" },
                new string[] { "403921",    "Central Visayan Institute of Aklan, Inc",                                                          "REGION VI",    "Aklan",    "Banga" },
                new string[] { "600062",    "Aklan State University-Main, College of Teacher Education, Kalibo, Banga, Laboratory High School", "REGION VI",    "Aklan",    "Banga" },
                new string[] { "403923",    "Kalantiaw Institute",                                                                              "REGION VI",    "Aklan",    "Batan" },
                new string[] { "403924",    "Buruanga Academy, Inc.",                                                                           "REGION VI",    "Aklan",    "Buruanga" },
                new string[] { "403925",    "Ibajay Academy, Inc.",                                                                             "REGION VI",    "Aklan",    "Ibajay" },
                new string[] { "403927",    "Melchor Memorial School, Inc.",                                                                    "REGION VI",    "Aklan",    "Ibajay" },
                new string[] { "402999",    "STI College - Kalibo",                                                                             "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403928",    "Aklan Academy",                                                                                    "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403929",    "Aklan Catholic College",                                                                           "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403932",    "Aklan Polytechnic College",                                                                        "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403933",    "Christ the King School Kalibo, Inc.",                                                              "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403934",    "Dela Cruz Institute of Business & Industry",                                                       "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403935",    "Infant Jesus School",                                                                              "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403936",    "Kalibo Institute, Inc.",                                                                           "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403938",    "Northwestern Visayan Colleges",                                                                    "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403940",    "Saint Gabriel College, Inc.",                                                                      "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "406705",    "St. Anne Montessori School Kalibo Aklan, Inc.",                                                    "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "407531",    "Infant Jesus Academy",                                                                             "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438005",    "Aklan Valley High School",                                                                         "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438006",    "Central Panay College of Science and Technology, Inc.",                                            "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438010",    "Joselito Alba Vocational and Technical School",                                                    "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438011",    "Starglow Center for Academics and Arts, Inc.",                                                     "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438012",    "Wadeford School",                                                                                  "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438053",    "Garcia College of Technology, Inc.",                                                               "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "438065",    "Verde Grande College, Inc.",                                                                       "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403942",    "Lezo Technical College",                                                                           "REGION VI",    "Aklan",    "Lezo" },
                new string[] { "403943",    "Aklan Central Institute, Inc.",                                                                    "REGION VI",    "Aklan",    "Makato" },
                new string[] { "403945",    "Bloomfield Integrated Academy Inc",                                                                "REGION VI",    "Aklan",    "Malay" },
                new string[] { "403948",    "Conperey Integrated Learning School",                                                              "REGION VI",    "Aklan",    "Malay" },
                new string[] { "438023",    "Boracay Island Global Academy",                                                                    "REGION VI",    "Aklan",    "Malay" },
                new string[] { "438064",    "Caticlan Academy Foundation, Inc.",                                                                "REGION VI",    "Aklan",    "Malay" },
                new string[] { "403194",    "St. Joseph's Academy of Malinao, Aklan, Inc.",                                                     "REGION VI",    "Aklan",    "Malinao" },
                new string[] { "403939",    "Panay Technological College",                                                                      "REGION VI",    "Aklan",    "Kalibo" },
                new string[] { "403951",    "Western Aklan Academy, Inc.",                                                                      "REGION VI",    "Aklan",    "Nabas" },
                new string[] { "438029",    "St. Anne Business Institute, Inc.",                                                                "REGION VI",    "Aklan",    "Nabas" },
                new string[] { "438027",    "Montfort Technical Institute",                                                                     "REGION VI",    "Aklan",    "New Washington" },
                new string[] { "403953",    "Irao Institute",                                                                                   "REGION VI",    "Aklan",    "Numancia" },
                new string[] { "403954",    "Madyaas Institute Inc.",                                                                           "REGION VI",    "Aklan",    "Numancia" },
                new string[] { "403956",    "Sto. Niño Seminary",                                                                               "REGION VI",    "Aklan",    "Numancia" },
                new string[] { "403957",    "St. Andrew's High School",                                                                         "REGION VI",    "Antique",  "Anini-y" },
                new string[] { "403958",    "St. Therese's High School, Inc.",                                                                  "REGION VI",    "Antique",  "Anini-y" },
                new string[] { "403960",    "St. Anthony's High School of Barbaza, Inc.",                                                       "REGION VI",    "Antique",  "Barbaza" },
                new string[] { "403007",    "Saint Joseph Academy",                                                                             "REGION VI",    "Antique",  "Bugasong" },
                new string[] { "403963",    "Semirara Adventist Academy Inc.",                                                                  "REGION VI",    "Antique",  "Caluya" },
                new string[] { "438504",    "Divine Word School of Semirara Island, Inc",                                                       "REGION VI",    "Antique",  "Caluya" },
                new string[] { "403009",    "St. Michael High School of Culasi, Inc.",                                                          "REGION VI",    "Antique",  "Culasi" },
                new string[] { "403959",    "Jinalinan Academy, Inc.",                                                                          "REGION VI",    "Antique",  "Pandan" },
                new string[] { "403968",    "Pandan Bay Institute, Inc.",                                                                       "REGION VI",    "Antique",  "Pandan" },
                new string[] { "403969",    "St. Augustine's Academy of Patnongon, Inc.",                                                       "REGION VI",    "Antique",  "Patnongon" },
                new string[] { "403000",    "Advanced Central College Discovery High School",                                                   "REGION VI",    "Antique",  "San Jose" },
                new string[] { "405993",    "Wright Technological College of Antique",                                                          "REGION VI",    "Antique",  "San Jose" },
                new string[] { "438501",    "St. Anthony's College",                                                                            "REGION VI",    "Antique",  "San Jose" },
                new string[] { "403971",    "St. Vincent's High School of San Remegio, Inc.",                                                   "REGION VI",    "Antique",  "San Remigio" },
                new string[] { "403972",    "St. Blaise High School",                                                                           "REGION VI",    "Antique",  "Sebaste" },
                new string[] { "403011",    "Wright Technological College of Antique (Wright Tech)",                                            "REGION VI",    "Antique",  "Sibalom" },
                new string[] { "600021",    "University of Antique-Main Campus",                                                                "REGION VI",    "Antique",  "Sibalom" },
                new string[] { "600038",    "University of Antique-Tario Lim Memorial Campus",                                                  "REGION VI",    "Antique",  "Tibiao" },
                new string[] { "403965",    "Dao Catholic High School, Inc.",                                                                   "REGION VI",    "Antique",  "Tobias Fornier (Dao)" },
                new string[] { "403974",    "St. Luke's Academy, Inc",                                                                          "REGION VI",    "Antique",  "Valderrama" },
                new string[] { "403975",    "Our Lady of Fatima Academy",                                                                       "REGION VI",    "Capiz",    "Dao" },
                new string[] { "405996",    "Saint Martin Academy, Inc.",                                                                       "REGION VI",    "Capiz",    "Dumalag" },
                new string[] { "403065",    "Our Lady of Snows Institute",                                                                      "REGION VI",    "Capiz",    "Dumarao" },
                new string[] { "403067",    "Saint Catherine Academy",                                                                          "REGION VI",    "Capiz",    "Mambusao" },
                new string[] { "600063",    "Capiz State University-Burias",                                                                    "REGION VI",    "Capiz",    "Mambusao" },
                new string[] { "439001",    "Daile's Franciscan Learning Institute Inc.",                                                       "REGION VI",    "Capiz",    "Panitan" },
                new string[] { "439007",    "St. Lawrence Parochial School",                                                                    "REGION VI",    "Capiz",    "Panitan" },
                new string[] { "403982",    "Pontevedra Christian School, Inc.",                                                                "REGION VI",    "Capiz",    "Pontevedra" },
                new string[] { "439004",    "Step by Step Christian Academy",                                                                   "REGION VI",    "Capiz",    "Pontevedra" },
                new string[] { "403981",    "Parish School of Saint Isidore-High School Department, Inc.",                                      "REGION VI",    "Capiz",    "Ponteverde" },
                new string[] { "403068",    "Saint Joseph Diocesan School, Inc.",                                                               "REGION VI",    "Capiz",    "President Roxas" },
                new string[] { "403984",    "Elizalde Academy Inc.",                                                                            "REGION VI",    "Capiz",    "President Roxas" },
                new string[] { "403182",    "St. Anthony College of Roxas City, Inc.",                                                          "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "404194",    "Our Lady of Grace Academy",                                                                        "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "404196",    "Saint Mary's Academy of Capiz",                                                                    "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "404197",    "College of St. John-Roxas",                                                                        "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "443501",    "Colegio de la Purisima Concepcion",                                                                "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "443502",    "St. Pius X Seminary",                                                                              "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "443503",    "Filamer Christian University",                                                                     "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "443520",    "Hercor College, Inc",                                                                              "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "600069",    "Capiz State University-Main",                                                                      "REGION VI",    "Capiz",    "Roxas City" },
                new string[] { "403989",    "Good Shepherd's Fold Academy",                                                                     "REGION VI",    "Guimaras",     "Buenavista" },
                new string[] { "404800",    "Grace Baptist Academy",                                                                            "REGION VI",    "Guimaras",     "Buenavista" },
                new string[] { "600238",    "Guimaras State College",                                                                           "REGION VI",    "Guimaras",     "Buenavista" },
                new string[] { "403990",    "Immaculate Heart of Mary Academy of Guimaras",                                                     "REGION VI",    "Guimaras",     "Jordan" },
                new string[] { "403991",    "St. Joseph School-Hijas de Jesus, Incorporated",                                                   "REGION VI",    "Guimaras",     "Jordan" },
                new string[] { "439501",    "Guimaras Baptist Academy, Inc.",                                                                   "REGION VI",    "Guimaras",     "Jordan" },
                new string[] { "403249",    "Philippine College of Business and Accountancy",                                                   "REGION VI",    "Guimaras",     "Nueva Valencia" },
                new string[] { "403992",    "Holy Rosary Academy - Guimaras, Inc.",                                                             "REGION VI",    "Guimaras",     "Nueva Valencia" },
                new string[] { "439502",    "Notre Dame Academy",                                                                               "REGION VI",    "Guimaras",     "Sibunag" },
                new string[] { "403108",    "St. Paul School-Barotac Nuevo",                                                                    "REGION VI",    "Iloilo",   "Barotac Nuevo" },
                new string[] { "403997",    "Iloilo Christian School of Barotac Nuevo, Inc.",                                                   "REGION VI",    "Iloilo",   "Barotac Nuevo" },
                new string[] { "600239",    "Iloilo State College of Fisheries- Barotac Nuevo",                                                 "REGION VI",    "Iloilo",   "Barotac Nuevo" },
                new string[] { "600240",    "Iloilo Science and Technology University-Barotac Nuevo",                                           "REGION VI",    "Iloilo",   "Barotac Nuevo" },
                new string[] { "600241",    "Iloilo State College of Fisheries-Main (Tiwi)",                                                    "REGION VI",    "Iloilo",   "Barotac Nuevo" },
                new string[] { "403999",    "St. Paul School, Barotac Viejo, Iloilo, Inc.",                                                     "REGION VI",    "Iloilo",   "Barotac Viejo" },
                new string[] { "404001",    "Mary Immaculate Academy",                                                                          "REGION VI",    "Iloilo",   "Calinog" },
                new string[] { "404231",    "Assumption School-Passi",                                                                          "REGION VI",    "Iloilo",   "City of Passi" },
                new string[] { "446002",    "Academia de San Guillermo",                                                                        "REGION VI",    "Iloilo",   "City of Passi" },
                new string[] { "446007",    "Passi Montessori International School, Inc.",                                                      "REGION VI",    "Iloilo",   "City of Passi" },
                new string[] { "407532",    "Mater Carmeli School",                                                                             "REGION VI",    "Iloilo",   "Dingle" },
                new string[] { "404011",    "St. Augustine Catholic School",                                                                    "REGION VI",    "Iloilo",   "Dumangas" },
                new string[] { "440046",    "St. Louis de Montfort Academy",                                                                    "REGION VI",    "Iloilo",   "Dumangas" },
                new string[] { "600245",    "Iloilo Science and Technology University-Dumangas",                                                "REGION VI",    "Iloilo",   "Dumangas" },
                new string[] { "404014",    "Iloilo King of Glory Christian Academy Inc.",                                                      "REGION VI",    "Iloilo",   "Estancia" },
                new string[] { "600066",    "Northern Iloilo Polytechnic State University",                                                     "REGION VI",    "Iloilo",   "Estancia" },
                new string[] { "403110",    "ABE International Business College-Iloilo City",                                                   "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403116",    "ACLC College of Iloilo",                                                                           "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403120",    "AMA Computer College-Iloilo City",                                                                 "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403127",    "Assumption School Iloilo",                                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403130",    "Iloilo Doctor's College",                                                                          "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403132",    "Professional Electronics Institute, Inc.",                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403138",    "St. Augustine School of Nursing-Iloilo City",                                                      "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403140",    "St. Therese-MTC Colleges-La Fiesta",                                                               "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403149",    "STI College - Iloilo",                                                                             "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "403157",    "Western Institute of Technology",                                                                  "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404163",    "Angelicum School",                                                                                 "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404170",    "Colegio de las Hijas de Jesus",                                                                    "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404172",    "Doane Christian Academy Foundation, Inc.",                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404173",    "Filipino-American School Town, Inc.",                                                              "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404174",    "Holy Rosary Academy, Inc.",                                                                        "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404177",    "Hua Siong College of Iloilo, Inc.",                                                                "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404186",    "Santa Clarita International School, Inc.",                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404187",    "Santa Isabel International School, Inc.",                                                          "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404188",    "Ateneo de Iloilo",                                                                                 "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404189",    "Sun Yat Sen High School of Iloilo, Inc.",                                                          "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404190",    "PAREF Westbridge School, Inc.",                                                                    "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "405880",    "ACSI College Iloilo, Inc.",                                                                        "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "407075",    "Cabalum Western College",                                                                          "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "407421",    "Asian College of Aeronautics, Inc.",                                                               "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "407634",    "John B. Lacson Foundation Maritime University - Arevalo, Inc.",                                    "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "407660",    "St. Therese - MTC Colleges-Tigbauan, Inc.",                                                        "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442503",    "Alphacrest Academy, Inc.",                                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442519",    "Iloilo Scholastic Academy",                                                                        "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442564",    "Central Philippine University",                                                                    "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442565",    "Colegio del Sagrado Corazon de Jesus",                                                             "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442568",    "University of Iloilo",                                                                             "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442570",    "Colegio De San Jose",                                                                              "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442572",    "John B. Lacson Foundation Maritime University-Molo, Inc",                                          "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442573",    "St. Vincent Ferrer Seminary",                                                                      "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442574",    "University of San Agustin",                                                                        "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442580",    "St. Robert's International Academy, Inc.",                                                         "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442600",    "St. Paul University Iloilo",                                                                       "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "442612",    "St. Therese - MTC Colleges-Jalandoni, Inc.",                                                       "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "600067",    "West Visayas State University",                                                                    "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "600252",    "Iloilo Science and Technology University-La Paz",                                                  "REGION VI",    "Iloilo",   "Iloilo City" },
                new string[] { "404015",    "Calvario Memorial Christian School (Janiuay, Iloilo), Inc.",                                       "REGION VI",    "Iloilo",   "Janiuay" },
                new string[] { "440002",    "CenterPhil Montessori Learning Center, Inc.",                                                      "REGION VI",    "Iloilo",   "Janiuay" },
                new string[] { "600247",    "West Visayas State University-Lambunao",                                                           "REGION VI",    "Iloilo",   "Lambunao" },
                new string[] { "404018",    "St. Catherine Parochial School",                                                                   "REGION VI",    "Iloilo",   "Leon" },
                new string[] { "404020",    "Kaunlaran Integrated School Foundation, Inc.",                                                     "REGION VI",    "Iloilo",   "Miagao" },
                new string[] { "404021",    "St. Louise de Marillac School of Miagao",                                                          "REGION VI",    "Iloilo",   "Miagao" },
                new string[] { "600248",    "Iloilo Science and Technology University-Miag-ao",                                                 "REGION VI",    "Iloilo",   "Miagao" },
                new string[] { "600249",    "University of the Philippines - Visayas",                                                          "REGION VI",    "Iloilo",   "Miagao" },
                new string[] { "440043",    "Georgia International Academy, Inc.",                                                              "REGION VI",    "Iloilo",   "Oton" },
                new string[] { "407064",    "Iloilo Merchant Marine School",                                                                    "REGION VI",    "Iloilo",   "Pavia" },
                new string[] { "404027",    "West Visayan Academy",                                                                             "REGION VI",    "Iloilo",   "Pototan" },
                new string[] { "600250",    "West Visayas State University-Pototan",                                                            "REGION VI",    "Iloilo",   "Pototan" },
                new string[] { "600251",    "Iloilo State College of Fisheries- San Enrique",                                                   "REGION VI",    "Iloilo",   "San Enrique" },
                new string[] { "404030",    "Eucharistic King Academy",                                                                         "REGION VI",    "Iloilo",   "Sara" },
                new string[] { "404031",    "San Juan Academy, Inc",                                                                            "REGION VI",    "Iloilo",   "Sara" },
                new string[] { "406004",    "BJ Institute of Technology Inc.",                                                                  "REGION VI",    "Iloilo",   "Sara" },
                new string[] { "440019",    "Queen of Heaven Mission School, Inc.",                                                             "REGION VI",    "Iloilo",   "Tigbauan" },
                new string[] { "404034",    "Sacred Heart Academy, Inc.",                                                                       "REGION VI",    "Iloilo",   "Zarraga" },
                new string[] { "440052",    "Gamot Cogon Institute",                                                                            "REGION VI",    "Iloilo",   "Zarraga" },
            };
            return School;
        }
    }
}