using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegionCAR
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "400860",    "Data Center College of the Philippines",           "CAR",  "Abra",     "Bangued" },
                new string[] { "406102",    "Abra Valley Colleges",             "CAR",  "Abra",     "Bangued" },
                new string[] { "406107",    "Holy Spirit Academy of Bangued",           "CAR",  "Abra",     "Bangued" },
                new string[] { "406109",    "St. Joseph Seminary",          "CAR",  "Abra",     "Bangued" },
                new string[] { "478501",    "Divine Word College of Bangued",           "CAR",  "Abra",     "Bangued" },
                new string[] { "600197",    "Abra State Institute of Science and Technology-Bangued Campus",            "CAR",  "Abra",     "Bangued" },
                new string[] { "406112",    "Abra Mountain Development Educational Center",             "CAR",  "Abra",     "Bucloc" },
                new string[] { "406113",    "Heart of Mary High School",            "CAR",  "Abra",     "Dolores" },
                new string[] { "406115",    "Queen of Peace High School - Canan",           "CAR",  "Abra",     "La Paz" },
                new string[] { "406116",    "Queen of Peace High School - La Paz",          "CAR",  "Abra",     "La Paz" },
                new string[] { "406117",    "Our Lady of Guadalupe School",             "CAR",  "Abra",     "Lacub" },
                new string[] { "406118",    "Holy Cross School of Lagangilang, Inc.",           "CAR",  "Abra",     "Lagangilang" },
                new string[] { "600113",    "Abra State Institute of Sciences and Technology",          "CAR",  "Abra",     "Lagangilang" },
                new string[] { "406122",    "Our Lady of Lourdes High School",          "CAR",  "Abra",     "Manabo" },
                new string[] { "406124",    "Little Flower High School",            "CAR",  "Abra",     "Peñarrubia" },
                new string[] { "406125",    "St. Mary's High School",           "CAR",  "Abra",     "Pidigan" },
                new string[] { "406126",    "Catholic High School of Pilar",            "CAR",  "Abra",     "Pilar" },
                new string[] { "406127",    "Fr. Arnoldus High School",             "CAR",  "Abra",     "Sallapadan" },
                new string[] { "406128",    "St. John High School",             "CAR",  "Abra",     "San Juan" },
                new string[] { "406129",    "Holy Ghost School",            "CAR",  "Abra",     "Tayum" },
                new string[] { "406132",    "St. Paul High School",             "CAR",  "Abra",     "Villaviciosa" },
                new string[] { "600114",    "Apayao State College",             "CAR",  "Apayao",   "Conner" },
                new string[] { "406134",    "Saint Joseph High School of Flora, Inc.",          "CAR",  "Apayao",   "Flora" },
                new string[] { "406136",    "Our Lady of Lourdes High School of Kabugao",           "CAR",  "Apayao",   "Kabugao" },
                new string[] { "406137",    "Santo Rosario School of Pudtol, Inc.",             "CAR",  "Apayao",   "Pudtol" },
                new string[] { "406138",    "Saint Paul's Academy of Sayangan, Inc.",           "CAR",  "Benguet",  "Atok" },
                new string[] { "400861",    "AMA Computer College-Baguio City",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400867",    "Baguio College of Technology",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400869",    "BSBT College, Inc.",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400873",    "Casiciaco Recoletos Seminary, Inc.",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400883",    "Data Center College of the Philippines of Baguio City, Inc",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400889",    "Informatics Baguio City Center, Inc.",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400903",    "Philippine Women's University - CDCEC, Baguio City, Inc.",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "400906",    "STI College - Baguio",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406209",    "Baguio Achievers' Academy Inc.",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406212",    "Baguio Central University",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406214",    "Baguio City Academy College",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406216",    "Baguio City Science Foundation",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406217",    "University of the Cordilleras",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406219",    "Baguio Patriotic High School",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406221",    "Baguio Seventh-day Adventist School Academy",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406222",    "Baguio Siloam Christian Academy, Inc.",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406228",    "Disciples for Christ International School",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406230",    "Easter College",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406255",    "Our Lady of Mt. Carmel Montessori",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406266",    "Small World Christian School Foundation",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406278",    "University of Baguio High School",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406285",    "Yesu Maeul Christian Academy",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "407044",    "Saint Francis Xavier Seminary, Inc.",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "407316",    "NorthPhil Polytechnic Institute, Inc.",            "CAR",  "Benguet",  "Baguio City" },
                new string[] { "407460",    "University of Baguio Science High School",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481503",    "Pines City Colleges",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481504",    "Berkeley School",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481509",    "Academia de Sophia International",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481514",    "Educare Learning Center",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481517",    "Remnant International College, Inc.",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481521",    "Shalom International School",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481523",    "Christian Legacy Academy",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481527",    "Baguio International Academy",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481531",    "Union School International-Baguio City, Inc.",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481536",    "Saint Louis School, Inc.(Center) High School Department",          "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481538",    "Westmont School Montessori",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481542",    "Fame Golf Mission School, Inc.",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481545",    "St. Joseph De Mary Learning Center",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481564",    "Baguio Vision Christian Academy Foundation, Inc.",             "CAR",  "Benguet",  "Baguio City" },
                new string[] { "481566",    "Saint Louis University",           "CAR",  "Benguet",  "Baguio City" },
                new string[] { "406144",    "Sacred Heart High School of Itogon, Inc.",             "CAR",  "Benguet",  "Itogon" },
                new string[] { "481510",    "Philippine BELL International School",             "CAR",  "Benguet",  "Itogon" },
                new string[] { "400912",    "BVS College",          "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "400925",    "Philippine Nazarene College",          "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "406014",    "Concordia College of Benguet, Inc.",           "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "406149",    "Cordillera Career Development College",            "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "406153",    "HOPE Christian Academy",           "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "406156",    "San Jose School of La Trinidad, Inc",          "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "406162",    "Star Colleges",            "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "479537",    "King's College of the Philippines",            "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "479540",    "Northskills Polytechnic College, Inc.",            "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "600116",    "Benguet State University-Secondary Lab School",            "CAR",  "Benguet",  "La Trinidad" },
                new string[] { "407590",    "Immaculate Conception School",             "CAR",  "Ifugao",   "Banaue" },
                new string[] { "406176",    "The Ifugao Academy, Inc.",             "CAR",  "Ifugao",   "Kiangan" },
                new string[] { "406177",    "St. Joseph's School",          "CAR",  "Ifugao",   "Kiangan" },
                new string[] { "407645",    "Riverview Polytechnic and Academic School, Inc.",          "CAR",  "Ifugao",   "Kiangan" },
                new string[] { "406178",    "Don Bosco High School",            "CAR",  "Ifugao",   "Lagawe" },
                new string[] { "406180",    "San Francisco High School",            "CAR",  "Ifugao",   "Lamut" },
                new string[] { "406181",    "Assumption Academy",           "CAR",  "Ifugao",   "Mayoyao" },
                new string[] { "406182",    "St. Paul's Memorial School of Kalinga, Inc.",          "CAR",  "Kalinga",  "Balbalan" },
                new string[] { "406183",    "St. Theresita High School of Salegseg, Inc.",          "CAR",  "Kalinga",  "Balbalan" },
                new string[] { "400927",    "International School of Asia and the Pacific-Kalinga Campus",          "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "400939",    "Cordillera A+ Computer Technology College",            "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "406188",    "Saint Tonis College, Inc.",            "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "406192",    "St. Theresita High School - Tabuk",            "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "406195",    "Tabuk Institute",          "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "407461",    "Saint William's Academy",          "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "480511",    "Kalinga Colleges of Science and Technology",           "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "600198",    "Kalinga-Apayao State College",             "CAR",  "Kalinga",  "City of Tabuk" },
                new string[] { "406185",    "St. Theresita's School of Lubuagan, Inc.",             "CAR",  "Kalinga",  "Lubuagan" },
                new string[] { "406186",    "St. Theresita High School - Pinukpuk",             "CAR",  "Kalinga",  "Pinukpuk" },
                new string[] { "406187",    "Saint Michael's Academy, Rizal, Inc.",             "CAR",  "Kalinga",  "Rizal (Liwan)" },
                new string[] { "406198",    "St. Theresita's High School - Tinglayan",          "CAR",  "Kalinga",  "Tinglayan" },
                new string[] { "406199",    "Bauko Catholic School",            "CAR",  "Mt. Province",     "Bauko" },
                new string[] { "406201",    "St. James High School of Mountain Province Inc.",          "CAR",  "Mt. Province",     "Besao" },
                new string[] { "406203",    "Saint Vincent's School",           "CAR",  "Mt. Province",     "Bontoc" },
                new string[] { "481005",    "XiJEN College of Mountain Province, Inc.",             "CAR",  "Mt. Province",     "Bontoc" },
                new string[] { "406206",    "Saint Mary's School of Sagada",            "CAR",  "Mt. Province",     "Sagada" },
            };
            return School;
        }
    }
}
    