using Domain.School;
using Domain.Taxonomy;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain.Seed
{
    public class DBInitiializerSchoolRegion1_2
    {
         private static DbSet<CityMunicipality> cityMunicipalities;
        private static DbSet<Region> regionEntity;
        private static DbSet<Province> provinceEntity;
        public  static void CreateDefaultData(DataContext dataContext)
        {
            dataContext.Database.EnsureCreated();
            AddDefaultSchool(dataContext);
        }


        public static void AddDefaultSchool(DataContext dataContext)
        {
            List<string[]> Schools = new List<string[]> {
                #region REGION I
                new string[] { "400001",	"St. Andrew Academy",			                                                "REGION I",	    "Ilocos Norte",	                "Bacarra"                   }, 
                new string[] { "400002",	"Badoc Junior College, Inc.",			                                        "REGION I",	    "Ilocos Norte",	                "Badoc"                     }, 
                new string[] { "400003",	"IGAMA Colleges Foundation, Inc.",			                                    "REGION I",	    "Ilocos Norte",	                "Badoc"                     }, 
                new string[] { "400004",	"Juan Luna Memorial Academy, Inc.",			                                    "REGION I",	    "Ilocos Norte",	                "Badoc"                     }, 
                new string[] { "400006",	"Saint Lawrence the Deacon Academy (formerly St. Lawrence Academy)",			"REGION I",	    "Ilocos Norte",	                "Bangui"                    }, 
                new string[] { "400013",	"Banna Academy Inc.",			                                                "REGION I",	    "Ilocos Norte",	                "Banna (Espiritu)"          }, 
                new string[] { "400007",	"Batac Institute, Inc.",			                                            "REGION I",	    "Ilocos Norte",	                "City of Batac"             }, 
                new string[] { "400008",	"Batac Junior College",			                                                "REGION I",	    "Ilocos Norte",	                "City of Batac"             }, 
                new string[] { "407479",	"Immaculate Conception Academy",			                                    "REGION I",	    "Ilocos Norte",	                "City of Batac"             }, 
                new string[] { "600000",	"Mariano Marcos State University-Batac",			                            "REGION I",	    "Ilocos Norte",	                "City of Batac"             }, 
                new string[] { "400012",	"St. Joseph Institute of Dingras, Inc.",			                            "REGION I",	    "Ilocos Norte",	                "Dingras"                   }, 
                new string[] { "400277",	"Divine Word College of Laoag",			                                        "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400278",	"Holy Spirit Academy - Laoag City",			                                    "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400285",	"Northern Christian College",			                                        "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400287",	"Northwestern University",			                                            "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400288",	"Our Saviour's Foundation, Inc. (Saviour's Christian Academy)",			        "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400291",	" St.Joseph High School of Laoag, Inc.",			                            "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400292",	" St.Mary's Seminary",			                                                "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "401751",	" AMA Computer College-Laoag City",			                                    "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "401755",	" Data Center College of the Philippines of Laoag City",			            "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "401756",	" STI College - Laoag",			                                                "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "407045",	" AIE College - Laoag, Inc.",			                                        "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "413001",	" International School of the Arts, the Languages and the Academe",		        "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "600005",	" Mariano Marcos State University",			                                    "REGION I",	    "Ilocos Norte",	                "Laoag City"                }, 
                new string[] { "400015",	" St.Jude High School",			                                                "REGION I",	    "Ilocos Norte",	                "Pagudpud"                  }, 
                new string[] { "400016",	" Paoay North Institute",			                                            "REGION I",	    "Ilocos Norte",	                "Paoay"                     }, 
                new string[] { "400017",	" Pasuquin High School of Ilocos Norte, Inc.",			                        "REGION I",	    "Ilocos Norte",	                "Pasuquin"                  }, 
                new string[] { "400018",	" St.James Academy of Pasuquin Ilocos Norte, Inc.",			                    "REGION I",	    "Ilocos Norte",	                "Pasuquin"                  }, 
                new string[] { "400019",	" Roosevelt High School",			                                            "REGION I",	    "Ilocos Norte",	                "Piddig"                    }, 
                new string[] { "400020",	" Saint Anne Academy of Piddig, Ilocos Norte, Inc.",			                "REGION I",	    "Ilocos Norte",	                "Piddig"                    }, 
                new string[] { "400021",	" Pinili Institute",			                                                "REGION I",	    "Ilocos Norte",	                "Pinili"                    }, 
                new string[] { "400022",	" Sta.Rosa Academy of San Nicolas Ilocos Norte, Inc.",			                "REGION I",	    "Ilocos Norte",	                "San Nicolas"               }, 
                new string[] { "400023",	" Gov.Roque B.Ablan, Sr., Memorial Academy, Inc.",			                    "REGION I",	    "Ilocos Norte",	                "Solsona"                   }, 
                new string[] { "400025",	" Saint Nicholas Academy of Vintar",			                                "REGION I",	    "Ilocos Norte",	                "Vintar"                    }, 
                new string[] { "400028",	" Holy Name High School",			                                            "REGION I",	    "Ilocos Sur",	                "Burgos"                    }, 
                new string[] { "400029",	" Cabugao Institute",			                                                "REGION I",	    "Ilocos Sur",	                "Cabugao"                   }, 
                new string[] { "400032",	" St.Agnes School, Inc.",			                                            "REGION I",	    "Ilocos Sur",	                "Cervantes"                 }, 
                new string[] { "600324",	" Ilocos Sur Polytechnic State College-Cervantes Campus",		                "REGION I",	    "Ilocos Sur",	                "Cervantes"                 }, 
                new string[] { "400031",	" St.Joseph's Institute, Inc.",			                                        "REGION I",	    "Ilocos Sur",	                "City of Candon"            }, 
                new string[] { "496008",	" Nicosat Colleges Inc.",			                                            "REGION I",	    "Ilocos Sur",	                "City of Candon"            }, 
                new string[] { "600323",	" Ilocos Sur Polytechnic State College-Candon Campus",			                "REGION I",	    "Ilocos Sur",	                "City of Candon"            }, 
                new string[] { "400058",	" Marian Institute of Vigan, Inc",			                                    "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "400061",	" Divine Word College of Vigan",			                                    "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "400062",	" Immaculate Conception Minor Seminary",			                            "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "400787",	" Macro Colleges, Inc.",			                                            "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "407607",	" Ilocos Sur Community College",			                                    "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "407616",	" Data Center College of the Philippines of Vigan City",		                "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "407620",	" STI College - Vigan",			                                                "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "407621",	" University of Northern Philippines",			                                "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "407652",	"Lyceum de Ylocos",			                                                    "REGION I",	    "Ilocos Sur",	                "City of Vigan"             }, 
                new string[] { "400035",	"Concepcion Adventist Academy",			                                        "REGION I",	    "Ilocos Sur",	                "Gregorio del Pilar (Concepcion)" }, 
                new string[] { "400037",	"St. William's Institute",			                                            "REGION I",	    "Ilocos Sur",	                "Magsingal"                 }, 
                new string[] { "400039",	"Narvacan Catholic School",			                                            "REGION I",	    "Ilocos Sur",	                "Narvacan"                  }, 
                new string[] { "410519",	"Polytechnic College of Region I, Inc.",		                                "REGION I",	    "Ilocos Sur",	                "Narvacan"                  }, 
                new string[] { "600326",	"Ilocos Sur Polytechnic State College-Narvacan Campus",			                "REGION I",	    "Ilocos Sur",	                "Narvacan"                  }, 
                new string[] { "400040",	"Tirad View Academy",			                                                "REGION I",	    "Ilocos Sur",	                "Quirino (Angkaki)"         }, 
                new string[] { "400042",	"San Esteban Academy",			                                                "REGION I",	    "Ilocos Sur",	                "San Esteban"               }, 
                new string[] { "400027",	"St. Paul College of Ilocos Sur",			                                    "REGION I",	    "Ilocos Sur",	                "San Vicente"               }, 
                new string[] { "400044",	"Santa High School, Inc.",			                                            "REGION I",	    "Ilocos Sur",	                "Santa"                     }, 
                new string[] { "400045",	"Sta. Catalina High School, Inc.",			                                    "REGION I",	    "Ilocos Sur",	                "Santa Catalina"            }, 
                new string[] { "400046",	"Our Lady of Guadalupe Academy",			                                    "REGION I",	    "Ilocos Sur",	                "Santa Cruz"                }, 
                new string[] { "400047",	"Pascual Rivera Pimentel Memorial Academy",	                                    "REGION I",	    "Ilocos Sur",	                "Santa Cruz"                }, 
                new string[] { "400048",	"San Jose High School",			                                                "REGION I",	    "Ilocos Sur",	                "Santa Cruz"                }, 
                new string[] { "400049",	"Sta. Cruz Institute",			                                                "REGION I",	    "Ilocos Sur",	                "Santa Cruz"                }, 
                new string[] { "400050",	"Sta. Lucia Academy",			                                                "REGION I",	    "Ilocos Sur",	                "Santa Lucia"               }, 
                new string[] { "400051",	"Sta. Lucia Catholic School, Inc.",			                                    "REGION I",	    "Ilocos Sur",	                "Santa Lucia"               }, 
                new string[] { "407593",	"St. Mary's College",			                                                "REGION I",	    "Ilocos Sur",	                "Santa Maria"               }, 
                new string[] { "600001",	"Ilocos Sur Polytechnic State College",			                                "REGION I",	    "Ilocos Sur",	                "Santa Maria"               }, 
                new string[] { "400053",	"Santiago Catholic School",			                                            "REGION I",	    "Ilocos Sur",	                "Santiago"                  }, 
                new string[] { "400054",	"Santiago Institute",			                                                "REGION I",	    "Ilocos Sur",	                "Santiago"                  }, 
                new string[] { "600325",	"Ilocos Sur Polytechnic State College-Santiago Campus",			                "REGION I",	    "Ilocos Sur",	                "Santiago"                  }, 
                new string[] { "400055",	"Benito Soliven Academy",			                                            "REGION I",	    "Ilocos Sur",	                "Santo Domingo"             }, 
                new string[] { "400056",	"Saint Augustine's School - Ilocos",			                                "REGION I",	    "Ilocos Sur",	                "Tagudin"                   }, 
                new string[] { "410532",	"Asean Institute for Research and Technology of the Philippines, Inc.",	        "REGION I",	    "Ilocos Sur",	                "Tagudin"                   }, 
                new string[] { "600131",	"Ilocos Sur Polytechnic State College-Tagudin Campus",			                "REGION I",	    "Ilocos Sur",	                "Tagudin"                   }, 
                new string[] { "400065",	"Agoo Academy",			                                                        "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "400067",	"Agoo Kiddie Special School, Inc.",			                                    "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "400068",	"Agoo Montessori Learning Center and High School, Inc.",			            "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "400070",	"St. Mary's Academy - Agoo, La Union, Inc",			                            "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "411016",	"Polytechnic College of La Union",			                                    "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "600004",	"Don Mariano Marcos Memorial State University-South La Union",			        "REGION I",	    "La Union",	                    "Agoo"                      }, 
                new string[] { "400072",	"Aringay School of Science, Arts, Technology and Trade",			            "REGION I",	    "La Union",	                    "Aringay"                   }, 
                new string[] { "400073",	"Notre Dame Institute of Aringay, La Union",			                        "REGION I",	    "La Union",	                    "Aringay"                   }, 
                new string[] { "411059",	"South Ilocandia College of Arts and Technology (SICAT)",			            "REGION I",	    "La Union",	                    "Aringay"                   }, 
                new string[] { "400075",	"Lord of Zion Divine School",			                                        "REGION I",	    "La Union",	                    "Bacnotan"                  }, 
                new string[] { "400076",	"Saint Anthony Montessori Educational Network, Inc.",			                "REGION I",	    "La Union",	                    "Bacnotan"                  }, 
                new string[] { "400077",	"Sta. Veronica College",			                                            "REGION I",	    "La Union",	                    "Bacnotan"                  }, 
                new string[] { "400078",	"Stella Maris Academy",			                                                "REGION I",	    "La Union",	                    "Bacnotan"                  }, 
                new string[] { "600003",	"Don Mariano Marcos Memorial State University-North La Union",			        "REGION I",	    "La Union",	                    "Bacnotan"                  }, 
                new string[] { "400080",	"Osias Educational Foundation",			                                        "REGION I",	    "La Union",	                    "Balaoan"                   }, 
                new string[] { "400081",	"San Nicolas Academy",			                                                "REGION I",	    "La Union",	                    "Balaoan"                   }, 
                new string[] { "400082",	"Saint Christopher Academy",			                                        "REGION I",	    "La Union",	                    "Bangar"                    }, 
                new string[] { "411033",	"Saint Bernard College La Union",			                                    "REGION I",	    "La Union",	                    "Bangar"                    }, 
                new string[] { "400084",	"La Union Colleges of Science and Technology, Inc.",			                "REGION I",	    "La Union",	                    "Bauang"                    }, 
                new string[] { "400086",	"Saint Anthony Montessori Educational Network, Inc",			                "REGION I",	    "La Union",	                    "Bauang"                    }, 
                new string[] { "407301",	"Bauang Training Center and Services",			                                "REGION I",	    "La Union",	                    "Bauang"                    }, 
                new string[] { "407480",	"Sacred Heart School",			                                                "REGION I",	    "La Union",	                    "Bauang"                    }, 
                new string[] { "400090",	"La Union Standard Academy",			                                        "REGION I",	    "La Union",	                    "Caba"                      }, 
                new string[] { "400091",	"Saint John the Baptist Learning Center",			                            "REGION I",	    "La Union",	                    "Caba"                      }, 
                new string[] { "411008",	"Remnant International School",			                                        "REGION I",	    "La Union",	                    "Caba"                      }, 
                new string[] { "400101",	"BHC Educational Institution, Inc.",			                                "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400103",	"Christ the King College",			                                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400104",	"CICOSAT Colleges",			                                                    "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400105",	"Diocesan Seminary of the Heart of Jesus",			                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400106",	"Felkris Academy, Inc.",			                                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400107",	"Gifted Learning Centre, Inc.",			                                        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400110",	"La Union Cultural Institute",			                                        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400115",	"Saint Louis College",			                                                "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400119",	"Union Christian College",			                                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "401764",	"STI College - La Union",			                                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "406977",	"Northern Philippines College for Maritime, Science and Technology",	        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "407623",	"AIE College - La Union, Inc.",			                                        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "407650",	"AMA Computer College-San Fernando, La Union",			                        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "411040",	"La Finn's Scholastica",			                                            "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "411062",	"Saint John Bosco College of Northern Luzon, Inc.",			                    "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "600008",	"Don Mariano Marcos Memorial State University, Mid La Union Campus",	        "REGION I",	    "La Union",	                    "City of San Fernando"      }, 
                new string[] { "400092",	"Santa Catalina Academy",			                                            "REGION I",	    "La Union",	                    "Luna"                      }, 
                new string[] { "400096",	"Union Schools (La Union) Phils., Inc.",			                            "REGION I",	    "La Union",	                    "Naguilian"                 }, 
                new string[] { "411023",	"Philippine Central College of Arts, Science and Technology",			        "REGION I",	    "La Union",	                    "Naguilian"                 }, 
                new string[] { "411048",	"Colegio de La Union",			                                                "REGION I",	    "La Union",	                    "Naguilian"                 }, 
                new string[] { "400097",	"Pugo Catholic School",			                                                "REGION I",	    "La Union",	                    "Pugo"                      }, 
                new string[] { "400098",	"St. Mary's Academy of Rosario, Inc",			                                "REGION I",	    "La Union",	                    "Rosario"                   }, 
                new string[] { "400099",	"Union Institute of Rosario",			                                        "REGION I",	    "La Union",	                    "Rosario"                   }, 
                new string[] { "411056",	"La Union Christian Comprehensive College",			                            "REGION I",	    "La Union",	                    "Rosario"                   }, 
                new string[] { "400112",	"Lorma Colleges Special Science High School",			                        "REGION I",	    "La Union",	                    "San Juan"                  }, 
                new string[] { "400124",	"St. Mary of the Sea Academy",			                                        "REGION I",	    "La Union",	                    "Santo Tomas"               }, 
                new string[] { "400125",	"San Alberto Magno Academy",			                                        "REGION I",	    "La Union",	                    "Tubao"                     }, 
                new string[] { "400128",	"Aguilar Catholic School, Inc.",			                                    "REGION I",	    "Pangasinan",	                "Aguilar"                   }, 
                new string[] { "400129",	"Zaratan Educational Institute, Inc.",			                                "REGION I",	    "Pangasinan",	                "Aguilar"                   }, 
                new string[] { "400139",	"Asbury College, Inc.",			                                                "REGION I",	    "Pangasinan",	                "Anda"                      }, 
                new string[] { "407482",	"St. Nicholas Catholic School of Anda",			                                "REGION I",	    "Pangasinan",	                "Anda"                      }, 
                new string[] { "412030",	"Eylim Christian Academy",			                                            "REGION I",	    "Pangasinan",	                "Asingan"                   }, 
                new string[] { "600218",	"Pangasinan State University-Asingan",			                                "REGION I",	    "Pangasinan",	                "Asingan"                   }, 
                new string[] { "400142",	"Mary Help of Christians Catholic School",		                                "REGION I",	    "Pangasinan",	                "Basista"                   }, 
                new string[] { "411528",	"BFF (Bancolita-Frias Family) Learning Academy, Inc.",			                "REGION I",	    "Pangasinan",	                "Basista"                   }, 
                new string[] { "400143",	"Marianne College of Science and Technology",			                        "REGION I",	    "Pangasinan",	                "Bayambang"                 }, 
                new string[] { "400145",	"Saint Vincent Catholic School",			                                    "REGION I",	    "Pangasinan",	                "Bayambang"                 }, 
                new string[] { "600007",	"Pangasinan State University-Bayambang",			                            "REGION I",	    "Pangasinan",	                "Bayambang"                 }, 
                new string[] { "400199",	"Holy Child Academy of Binalonan",			                                    "REGION I",	    "Pangasinan",	                "Binalonan"                 }, 
                new string[] { "407614",	"WCC Aeronautical and Technological College",			                        "REGION I",	    "Pangasinan",	                "Binalonan"                 }, 
                new string[] { "412027",	"Math Excellence Academy of Binalonan, Inc.",			                        "REGION I",	    "Pangasinan",	                "Binalonan"                 }, 
                new string[] { "400146",	"Binmaley Catholic School, Inc.",			                                    "REGION I",	    "Pangasinan",	                "Binmaley"                  }, 
                new string[] { "400149",	"Mary Help of Christians Seminary",			                                    "REGION I",	    "Pangasinan",	                "Binmaley"                  }, 
                new string[] { "600217",	"Pangasinan State University-Binmaley",			                                "REGION I",	    "Pangasinan",	                "Binmaley"                  }, 
                new string[] { "411564",	"St. Adelaide School-Philippines",			                                    "REGION I",	    "Pangasinan",	                "Burgos"                    }, 
                new string[] { "401758",	"AIE College, Calasiao",			                                            "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "401763",	"Philippine College of Science and Technology",			                        "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "407618",	"Señor Tesoro College",			                                                "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "411517",	"Señor Tesoro Academy",			                                                "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "411518",	"Mother Lourdes Learning School",			                                    "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "411520",	"Sir Melan Learning Center, Inc.",			                                    "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "411555",	"Carthel Science Educational Foundation-Dagupan, Inc.",			                "REGION I",	    "Pangasinan",	                "Calasiao"                  }, 
                new string[] { "400132",	"Mary the Queen Foundation",			                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "400136",	"Colegio San Jose De Alaminos",			                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "400138",	"The Great Plebeian College",			                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "401729",	"Golden West Colleges",			                                                "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "401730",	"PASS College",			                                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "404116",	"STI Alaminos",			                                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "407294",	"AIE College - Alaminos, Inc.",			                                        "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "496503",	"Ednas School of Alaminos, Inc.",			                                    "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "600216",	"Pangasinan State University-Alaminos",			                                "REGION I",	    "Pangasinan",	                "City of Alaminos"          }, 
                new string[] { "400315",	"Divine Grace Montessori And High School of Urdaneta, Inc.",			        "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400316",	"Divine Word College of Urdaneta",			                                    "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400318",	"Lyceum Northern Luzon",			                                            "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400319",	"Merryland Montessori & High School, Inc.",			                            "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400324",	"Our Lady of the Lilies Academy",			                                    "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400325",	"PanPacific University North Philippines",			                            "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400326",	"St. Andrew Montessori and High School",			                            "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "407610",	"PHINMA-UPang College Urdaneta, Inc.",			                                "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "407617",	"AIE College - Urdaneta, Inc.",			                                        "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "407619",	"ABE International College of Business and Accountancy-Urdaneta Campus",        "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "414003",	"International Colleges for Excellence, Inc.",			                        "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "414004",	"Lyceum Northwestern University-Urdaneta Campus",			                    "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "414011",	"Luzon College of Science and Technology (URD), Inc.",			                "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "600219",	"Pangasinan State University-Urdaneta",			                                "REGION I",	    "Pangasinan",	                "City of Urdaneta"          }, 
                new string[] { "400252",	"University of Pangasinan",			                                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400253",	"St. Michael School By-The-Sea, Inc.",			                                "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400254",	"Lyceum Northwestern University",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400255",	"Divine Word Academy of Dagupan",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400256",	"Dominican School (Dagupan), Inc.",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400258",	"Ednas School",			                                                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400259",	"Escuela De Nuestra Señora de la Salette",			                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400263",	"La Marea Academy",			                                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400265",	"University of Luzon",			                                                "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400267",	"Mother Goose Special School System-Special Science High School- Dagupan City",	"REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400269",	"Pangasinan Universal Institute",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400270",	"St. Albert the Great School",			                                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400271",	"St. John's Cathedral School",			                                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "401732",	"AMA Computer College-Dagupan City",			                                "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "401741",	"Dagupan College Foundation",			                                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "401743",	"Kingfisher School of Business and Finance",			                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "401749",	"STI College - Dagupan",			                                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "404121",	"AIE College, Inc. - Dagupan",			                                        "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "404133",	"British College International",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "404138",	"Prime Brilliant Minds Academy",			                                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "407300",	"Manila Montessori College International",			                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "412501",	"Pamma Learning Center",			                                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "412502",	"Genesis School of Happy Kids Advanced Studies",			                    "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "412510",	"PIMSAT Colleges, Inc.",			                                            "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "412512",	"Colegio De Dagupan",			                                                "REGION I",	    "Pangasinan",	                "Dagupan City"              }, 
                new string[] { "400156",	"Dasol Catholic School",			                                            "REGION I",	    "Pangasinan",	                "Dasol"                     }, 
                new string[] { "400157",	"Don Marcelo Jimenez Memorial Polytechnic Institute",		                    "REGION I",	    "Pangasinan",	                "Dasol"                     }, 
                new string[] { "400158",	"St. John's Institute",			                                                "REGION I",	    "Pangasinan",	                "Infanta"                   }, 
                new string[] { "600182",	"Pangasinan State University-Infanta",			                                "REGION I",	    "Pangasinan",	                "Infanta"                   }, 
                new string[] { "400159",	"St. Columban's School, Inc.",			                                        "REGION I",	    "Pangasinan",	                "Labrador"                  }, 
                new string[] { "400160",	"The Adelphi College",			                                                "REGION I",	    "Pangasinan",	                "Lingayen"                  }, 
                new string[] { "400165",	"JN Montessori and High School, Inc.",			                                "REGION I",	    "Pangasinan",	                "Lingayen"                  }, 
                new string[] { "400168",	"Saint Columban's College",			                                            "REGION I",	    "Pangasinan",	                "Lingayen"                  }, 
                new string[] { "400169",	"St. Columban's Institute",			                                            "REGION I",	    "Pangasinan",	                "Lingayen"                  }, 
                new string[] { "404146",	"Lingayen Technological Institute",			                                    "REGION I",	    "Pangasinan",	                "Lingayen"                  }, 
                new string[] { "400170",	"Riverview High School",			                                            "REGION I",	    "Pangasinan",	                "Mabini"                    }, 
                new string[] { "400173",	"Malasiqui Agno Valley College",			                                    "REGION I",	    "Pangasinan",	                "Malasiqui"                 }, 
                new string[] { "400174",	"Malasiqui Catholic School",			                                        "REGION I",	    "Pangasinan",	                "Malasiqui"                 }, 
                new string[] { "400175",	"Perpetual Help College of Pangasinan",		                                    "REGION I",	    "Pangasinan",	                "Malasiqui"                 }, 
                new string[] { "400203",	"Family Child Development School",			                                    "REGION I",	    "Pangasinan",	                "Manaoag"                   }, 
                new string[] { "400206",	"Colegio de San Juan de Letran-Manaoag",	                                    "REGION I",	    "Pangasinan",	                "Manaoag"                   }, 
                new string[] { "412010",	"St. Camillus College of Manaoag",			                                    "REGION I",	    "Pangasinan",	                "Manaoag"                   }, 
                new string[] { "400210",	"Cherished Moment School",			                                            "REGION I",	    "Pangasinan",	                "Mangaldan"                 }, 
                new string[] { "400212",	"Metro-Dagupan Colleges",			                                            "REGION I",	    "Pangasinan",	                "Mangaldan"                 }, 
                new string[] { "400213",	"Santo Tomas Catholic School, Inc.",			                                "REGION I",	    "Pangasinan",	                "Mangaldan"                 }, 
                new string[] { "400176",	"Mangatarem Catholic School",			                                        "REGION I",	    "Pangasinan",	                "Mangatarem"                }, 
                new string[] { "400177",	"Mystical Rose College of Science and Technology",			                    "REGION I",	    "Pangasinan",	                "Mangatarem"                }, 
                new string[] { "411569",	"Ladder of Success Montessori School of Mangatarem, Inc.",			            "REGION I",	    "Pangasinan",	                "Mangatarem"                }, 
                new string[] { "400181",	"Mapandan Catholic School",			                                            "REGION I",	    "Pangasinan",	                "Mapandan"                  }, 
                new string[] { "400215",	"Movers Academy, Inc.",			                                                "REGION I",	    "Pangasinan",	                "Natividad"                 }, 
                new string[] { "400218",	"St. Philomena's Academy",			                                            "REGION I",	    "Pangasinan",	                "Pozorrubio"                }, 
                new string[] { "407609",	"University of Luzon - Pozorrubio Campus",			                            "REGION I",	    "Pangasinan",	                "Pozorrubio"                }, 
                new string[] { "412049",	"Mary Help of Christians Boarding School, Inc.",			                    "REGION I",	    "Pangasinan",	                "Pozorrubio"                }, 
                new string[] { "400219",	"Bethel Faith Christian Academy Inc.",			                                "REGION I",	    "Pangasinan",	                "Rosales"                   }, 
                new string[] { "400224",	"Rosales Wesleyan Academy, Inc.",			                                    "REGION I",	    "Pangasinan",	                "Rosales"                   }, 
                new string[] { "412043",	"Divine Grace Montessori and High School of Rosales, Inc.",			            "REGION I",	    "Pangasinan",	                "Rosales"                   }, 
                new string[] { "400297",	"Clark Educational Center, Inc.",			                                    "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400298",	"Ednas School of San Carlos, Inc.",			                                    "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400300",	"Gospel of Christ School",			                                            "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400304",	"Palaris Colleges Inc.",			                                            "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400306",	"San Carlos College",			                                                "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400307",	"San Carlos Preparatory School",			                                    "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400309",	"St. Charles Academy",			                                                "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400311",	"St. Therese College Foundation",			                                    "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "407615",	"Pangasinan State University-San Carlos City",			                        "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "408004",	"Virgen Milagrosa University Foundation, Inc.",			                        "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "413501",	"Saint Albert the Great Science Academy",			                            "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "413503",	"Our Lady of Grace School of San Carlos City, Inc.",			                "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "413505",	"PIMSAT Colleges, Inc.",			                                            "REGION I",	    "Pangasinan",	                "San Carlos City"           }, 
                new string[] { "400225",	"Archdiocesan School of San Fabian",			                                "REGION I",	    "Pangasinan",	                "San Fabian"                }, 
                new string[] { "400227",	"Joyland School, Inc",			                                                "REGION I",	    "Pangasinan",	                "San Fabian"                }, 
                new string[] { "400230",	"San Jacinto Catholic School",			                                        "REGION I",	    "Pangasinan",	                "San Jacinto"               }, 
                new string[] { "400231",	"St. Mary's Dominican School",			                                        "REGION I",	    "Pangasinan",	                "San Manuel"                }, 
                new string[] { "400234",	"Red Arrow High School",			                                            "REGION I",	    "Pangasinan",	                "San Nicolas"               }, 
                new string[] { "400235",	"San Quintin High School Foundation, Inc.",			                            "REGION I",	    "Pangasinan",	                "San Quintin"               }, 
                new string[] { "407611",	"Quintinians Technical Vocational School, Inc.",			                    "REGION I",	    "Pangasinan",	                "San Quintin"               }, 
                new string[] { "412024",	"Saint Rose Academy of San Quintin, Inc.",			                            "REGION I",	    "Pangasinan",	                "San Quintin"               }, 
                new string[] { "400238",	"Northern Luzon Adventist College",			                                    "REGION I",	    "Pangasinan",	                "Sison"                     }, 
                new string[] { "400239",	"Our Lady of Mt. Carmel Academy",			                                    "REGION I",	    "Pangasinan",	                "Sison"                     }, 
                new string[] { "400236",	"Saint Mary's Integrated School",			                                    "REGION I",	    "Pangasinan",	                "Sta. Maria"                }, 
                new string[] { "407612",	"Pangasinan State University-Sta. Maria",			                            "REGION I",	    "Pangasinan",	                "Sta. Maria"                }, 
                new string[] { "400240",	"Luna Colleges, Inc.",			                                                "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "400243",	"Tayug Foundational Christian Academy",			                                "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "407624",	"Panpacific University North Philippines-Tayug",			                    "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "408645",	"Metro Global Institute of Sciene and Technology Inc.",		                    "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "412016",	"Divine Grace Montessori and High School",			                            "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "412074",	"Kingsville Advanced School",			                                        "REGION I",	    "Pangasinan",	                "Tayug"                     }, 
                new string[] { "400245",	"Immaculate Conception Catholic School",			                            "REGION I",	    "Pangasinan",	                "Umingan"                   }, 
                new string[] { "400246",	"Quezon Memorial Academy",			                                            "REGION I",	    "Pangasinan",	                "Umingan"                   }, 
                new string[] { "404143",	"Hope of Melbourne Colleges Foundation, Inc.",			                        "REGION I",	    "Pangasinan",	                "Umingan"                   }, 
                new string[] { "408644",	"Sta. Catalina College of Science and Technology Umingan Branch Inc.",			"REGION I",	    "Pangasinan",	                "Umingan"                   }, 
                new string[] { "400186",	"Urbiztondo Catholic School",			                                        "REGION I",	    "Pangasinan",	                "Urbiztondo"                }, 
                new string[] { "400249",	"Saint Anthony Abbot Academy",			                                        "REGION I",	    "Pangasinan",	                "Villasis"                  }, 
                new string[] { "412009",	"Palm Springs Montessori Integrated School, Inc.",			                    "REGION I",	    "Pangasinan",	                "Villasis"                  },

                #endregion

                #region REGION II
                new string[] { "400331",	"Divine Word High School - Dana-ili Campus",			                        "REGION II",	"Cagayan",                      "Abulug"                    },
                new string[] { "400332",	"Lyceum of Abulug",			                                                    "REGION II",	"Cagayan",                      "Abulug"                    },
                new string[] { "415024",	"F.L. Vargas College",			                                                "REGION II",	"Cagayan",                      "Abulug"                    },
                new string[] { "400334",	"Lyceum of Alcala, Inc.",			                                            "REGION II",	"Cagayan",                      "Alcala"                    },
                new string[] { "400335",	"St. Philomene of Alcala, Inc.",			                                    "REGION II",	"Cagayan",                      "Alcala"                    },
                new string[] { "400336",	"Allacapan Institute",			                                                "REGION II",	"Cagayan",                      "Allacapan"                 },
                new string[] { "400339",	"Our Lady of Victories Academy",	                                            "REGION II",	"Cagayan",                      "Amulung"                   },
                new string[] { "400344",	"Cagayan Valley Institute",			                                            "REGION II",	"Cagayan",                      "Aparri"                    },
                new string[] { "400345",	"Lyceum of Aparri",			                                                    "REGION II",	"Cagayan",                      "Aparri"                    },
                new string[] { "400349",	"St. Paul School of Aparri",		                                            "REGION II",	"Cagayan",                      "Aparri"                    },
                new string[] { "400350",	"St. Joseph's College of Baggao, Inc.",			                                "REGION II",	"Cagayan",                      "Baggao"                    },
                new string[] { "400353",	"Northern Cagayan Colleges Foundation, Inc.",			                        "REGION II",	"Cagayan",                      "Ballesteros"               },
                new string[] { "400354",	"Quezon Colleges of the North",			                                        "REGION II",	"Cagayan",                      "Ballesteros"               },
                new string[] { "400356",	"Northeastern Academy",			                                                "REGION II",	"Cagayan",                      "Buguey"                    },
                new string[] { "400357",	"Lyceum of Camiguin",			                                                "REGION II",	"Cagayan",                      "Calayan"                   },
                new string[] { "400360",	"Lyceum of Camalaniugan",			                                            "REGION II",	"Cagayan",                      "Camalaniugan"              },
                new string[] { "400362",	"Academy of St. Joseph",			                                            "REGION II",	"Cagayan",                      "Claveria"                  },
                new string[] { "400364",	"Our Lady of Snows Academy, Inc.",			                                    "REGION II",	"Cagayan",                      "Enrile"                    },
                new string[] { "400366",	"Northern Philippines Academy",			                                        "REGION II",	"Cagayan",                      "Gattaran"                  },
                new string[] { "400368",	"St. Catherine's Academy",			                                            "REGION II",	"Cagayan",                      "Gattaran"                  },
                new string[] { "400370",	"St. Anthony's Academy - Gonzaga",			                                    "REGION II",	"Cagayan",                      "Gonzaga"                   },
                new string[] { "415008",	"Saint James Academy of Iguig, Inc.",			                                "REGION II",	"Cagayan",                      "Iguig"                     },
                new string[] { "400375",	"Lyceum of Lal-lo",			                                                    "REGION II",	"Cagayan",                      "Lal-lo"                    },
                new string[] { "400377",	"Lasam Academy Incorporated",			                                        "REGION II",	"Cagayan",                      "Lasam"                     },
                new string[] { "400378",	"San Lorenzo Ruiz Educational Institute, Inc.",			                        "REGION II",	"Cagayan",                      "Lasam"                     },
                new string[] { "400379",	"Pamplona Institute",			                                                "REGION II",	"Cagayan",                      "Pamplona"                  },
                new string[] { "400381",	"San Jacinto Seminary",			                                                "REGION II",	"Cagayan",                      "Peñablanca"                },
                new string[] { "415063",	"International School of Asia and the Pacific-Cagayan",			                "REGION II",	"Cagayan",                      "Peñablanca"                },
                new string[] { "400383",	"Our Lady of Piat High School",			                                        "REGION II",	"Cagayan",                      "Piat"                      },
                new string[] { "400384",	"Piat Academy",			                                                        "REGION II",	"Cagayan",                      "Piat"                      },
                new string[] { "407484",	"Saint Francis Academy-Rizal",			                                        "REGION II",	"Cagayan",                      "Rizal"                     },
                new string[] { "400386",	"Divine Word High School - Sanchez Mira",			                            "REGION II",	"Cagayan",                      "Sanchez-Mira"              },
                new string[] { "400387",	"Namuac Academy",			                                                    "REGION II",	"Cagayan",                      "Sanchez-Mira"              },
                new string[] { "400389",	"Thoburn Memorial Academy",			                                            "REGION II",	"Cagayan",                      "Sanchez-Mira"              },
                new string[] { "400391",	"St. Anthony's College",			                                            "REGION II",	"Cagayan",                      "Santa Ana"                 },
                new string[] { "407483",	"Saint Francis Academy",			                                            "REGION II",	"Cagayan",                      "Santa Teresita"            },
                new string[] { "400361",	"Veridiano Academy Foundation",			                                        "REGION II",	"Cagayan",                      "Santo Niño (Faire)"        },
                new string[] { "400394",	"San Vicente Institute of Solana, Inc.",			                            "REGION II",	"Cagayan",                      "Solana"                    },
                new string[] { "400399",	"Lyceum of Tuao",			                                                    "REGION II",	"Cagayan",                      "Tuao"                      },
                new string[] { "400548",	"University of Cagayan Valley",			                                        "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "400561",	"University of Saint Louis",			                                        "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "400562",	"St. Paul University Philippines",			                                    "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "401785",	"AMA Computer College-Tuguegarao City",			                                "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "401787",	"Maila Rosario College",			                                            "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "401790",	"STI College - Tuguegarao",			                                            "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "404185",	"City Technological Institute",			                                        "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "407148",	"Cagayan Metropolitan Institute of Technology, Inc.",			                "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "407150",	"International School of Asia and the Pacific - Atulayan",		                "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "407151",	"Khan's Maritime Academy of the Philippines",			                        "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "417001",	"John Wesley College",			                                                "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "417010",	"F. L. Vargas College",			                                                "REGION II",	"Cagayan",                      "Tuguegarao City"           },
                new string[] { "400404",	"Dalton Academy",			                                                    "REGION II",	"Isabela",                      "Alicia"                    },
                new string[] { "400406",	"Northeast Luzon Adventist College",			                                "REGION II",	"Isabela",                      "Alicia"                    },
                new string[] { "400407",	"School of Our Lady of Atocha",			                                        "REGION II",	"Isabela",                      "Alicia"                    },
                new string[] { "415590",	"Top Achievers Private School, Inc.",			                                "REGION II",	"Isabela",                      "Alicia"                    },
                new string[] { "400410",	"La Salette of Aurora, Inc.",			                                        "REGION II",	"Isabela",                      "Aurora"                    },
                new string[] { "400414",	"St. Ferdinand College, Inc. - Cabagan",			                            "REGION II",	"Isabela",                      "Cabagan"                   },
                new string[] { "400416",	"La Salette of Cabatuan",			                                            "REGION II",	"Isabela",                      "Cabatuan"                  },
                new string[] { "400417",	"Philippine Yuh Chiau School",			                                        "REGION II",	"Isabela",                      "Cabatuan"                  },
                new string[] { "400355",	"Isabela College of Arts and Technology",			                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400418",	"Metropolitan Bible Baptist Learning Center, Inc.",			                    "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400420",	"Centro De Cultura",			                                                "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400422",	"Isabela Colleges Inc.",			                                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400423",	"Merry Sunshine Montessori School",			                                    "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400424",	"Nan Sing School of Cauayan City, Inc.",			                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400426",	"Our Lady of the Pillar College-Cauayan City",			                        "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "404150",	"College of Business Education Science and Technology, Inc",	                "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "404153",	"East Asia International Systems College",			                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "415501",	"Saint Clare College of Region 02, Inc.",			                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "415527",	"University of Perpetual Help System Laguna-JONELTA",			                "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "415528",	"Children of Lourdes Academy-Cauayan Inc.",			                            "REGION II",	"Isabela",                      "City of Cauayan"           },
                new string[] { "400464",	"Infant Jesus Montessori School, Inc.",			                                "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "400473",	"Santiago Cultural Institute",			                                        "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "400475",	"University of La Salette, Inc.",			                                    "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "400830",	"Sistech College of Santiago City, Inc.",			                            "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "401777",	"AMA Computer College-Santiago City",			                                "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "401783",	"Patria Sable Corpus College",			                                        "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "415533",	"Children First School",			                                            "REGION II",	"Isabela",                      "City of Santiago"          },
                new string[] { "400429",	"St. John Berchmans High School Inc.",			                                "REGION II",	"Isabela",                      "Cordon"                    },
                new string[] { "400446",	"Magsaysay Memorial High School",			                                    "REGION II",	"Isabela",                      "Delfin Albano (Magsaysay)" },
                new string[] { "400431",	"School of St. Joseph the Worker-Echague",			                            "REGION II",	"Isabela",                      "Echague"                   },
                new string[] { "400432",	"St. Dominic Human Development Center, Inc.",		                            "REGION II",	"Isabela",                      "Echague"                   },
                new string[] { "400435",	"Casa Del Niño Montessori School of Ilagan",		                            "REGION II",	"Isabela",                      "Ilagan City"               },
                new string[] { "400436",	"Central Isabela Christian Academy",			                                "REGION II",	"Isabela",                      "Ilagan City"               },
                new string[] { "400440",	"St. Ferdinand College, Inc. - Ilagan Campus",		                            "REGION II",	"Isabela",                      "Ilagan City"               },
                new string[] { "415547",	"Miracle Light Christian Academy",			                                    "REGION II",	"Isabela",                      "Ilagan City"               },
                new string[] { "400443",	"Children's Learning and Development Center Foundation, Incorporation",			"REGION II",	"Isabela",                      "Jones"                     },
                new string[] { "400444",	"La Salette of Jones, Inc.",			                                        "REGION II",	"Isabela",	                    "Jones"                     },
                new string[] { "400448",	"Mallig Plains College",			                                            "REGION II",	"Isabela",	                    "Mallig"                    },
                new string[] { "400450",	"School of St. Joseph (Naguilian, Isabela), Inc.",			                    "REGION II",	"Isabela",	                    "Naguilian"                 },
                new string[] { "400452",	"La Salette of Quezon, Inc",			                                        "REGION II",	"Isabela",	                    "Quezon"                    },
                new string[] { "415534",	"Wonderful Grace Learning Center",			                                    "REGION II",	"Isabela",	                    "Quirino"                   },
                new string[] { "400453",	"JET Montessori of Ramon, Inc.",			                                    "REGION II",	"Isabela",	                    "Ramon"                     },
                new string[] { "400454",	"La Salette of Ramon, Inc.",			                                        "REGION II",	"Isabela",	                    "Ramon"                     },
                new string[] { "415508",	"Lord Reigns Christian Academy",			                                    "REGION II",	"Isabela",	                    "Ramon"                     },
                new string[] { "415538",	"Alvarez-Ramales School Foundation, Inc.",			                            "REGION II",	"Isabela",	                    "Ramon"                     },
                new string[] { "400455",	"La Salette of Roxas College, Inc.",			                                "REGION II",	"Isabela",	                    "Roxas"                     },
                new string[] { "415553",	"Casa Del Niño Montessori School of Roxas",			                            "REGION II",	"Isabela",	                    "Roxas"                     },
                new string[] { "400458",	"Southern Isabela Academy, Inc.",			                                    "REGION II",	"Isabela",	                    "San Guillermo"             },
                new string[] { "415599",	"Our Lady of the Pillar College-San Manuel",			                        "REGION II",	"Isabela",	                    "San Manuel"                },
                new string[] { "400459",	"Alejandrino Family Learning Center",			                                "REGION II",	"Isabela",	                    "San Mariano"               },
                new string[] { "415516",	"Saint Thomas Montessori De San Mariano, Inc.",			                        "REGION II",	"Isabela",	                    "San Mariano"               },
                new string[] { "400460",	"Eveland Christian College. Inc.",			                                    "REGION II",	"Isabela",	                    "San Mateo"                 },
                new string[] { "400462",	"La Salette of San Mateo",			                                            "REGION II",	"Isabela",	                    "San Mateo"                 },
                new string[] { "400476",	"Northern Isabela Academy, Inc.",			                                    "REGION II",	"Isabela",	                    "Santo Tomas"               },
                new string[] { "400477",	"School of Saint Matthias",			                                            "REGION II",	"Isabela",	                    "Tumauini"                  },
                new string[] { "415509",	"Advance Montessori Education Center of Isabela",			                    "REGION II",	"Isabela",	                    "Tumauini"                  },
                new string[] { "401768",	"STI - Cauayan",			                                                    "REGION II",	"Isabela",	                    "City of Cauayan"           },
                new string[] { "400470",	"Northeastern College",			                                                "REGION II",	"Isabela",	                    "City of Santiago"          },
                new string[] { "401782",	"Cagayan Valley Computer & Information Technology College (CVCITC)",			"REGION II",	"Isabela",	                    "City of Santiago"          },
                new string[] { "401784",	"STI College - Santiago",			                                            "REGION II",	"Isabela",	                    "City of Santiago"          },
                new string[] { "401771",	"STI Ilagan",			                                                        "REGION II",	"Isabela",	                    "Ilagan City"               },
                new string[] { "401773",	"HG Baquiran College",			                                                "REGION II",	"Isabela",	                    "Tumauini"                  },
                new string[] { "400483",	"Nueva Vizcaya Institute",			                                            "REGION II",	"Nueva Vizcaya",	            "Aritao"                    },
                new string[] { "400484",	"St. Teresita's Academy of Aritao, Inc.",			                            "REGION II",	"Nueva Vizcaya",	            "Aritao"                    },
                new string[] { "404176",	"Southern Cagayan Valley School of Technology, Inc.",			                "REGION II",	"Nueva Vizcaya",	            "Aritao"                    },
                new string[] { "400491",	"Saint Jerome's Academy",			                                            "REGION II",	"Nueva Vizcaya",	            "Bagabag"                   },
                new string[] { "400499",	"Saint Catherine's School",			                                            "REGION II",	"Nueva Vizcaya",	            "Bambang"                   },
                new string[] { "401775",	"King's College of the Philippines, Inc.",			                            "REGION II",	"Nueva Vizcaya",	            "Bambang"                   },
                new string[] { "600015",	"Nueva Vizcaya State University",			                                    "REGION II",	"Nueva Vizcaya",	            "Bambang"                   },
                new string[] { "400506",	"Saint Mary's University",			                                            "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "401776",	"Sierra College",			                                                    "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "407322",	"Our Lady of Peace and Good Voyage Institute of Technology, Inc.",			    "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "416003",	"Nueva Vizcaya Bright Child School, Inc.",			                            "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "416026",	"PLT College, Inc.",			                                                "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "600014",	"Nueva Vizcaya State University",			                                    "REGION II",	"Nueva Vizcaya",	            "Bayombong"                 },
                new string[] { "400509",	"Saint Joseph School",			                                                "REGION II",	"Nueva Vizcaya",	            "Diadi"                     },
                new string[] { "400515",	"Camella SNV School",			                                                "REGION II",	"Nueva Vizcaya",	            "Dupax del Norte"           },
                new string[] { "400521",	"Aldersgate College",			                                                "REGION II",	"Nueva Vizcaya",	            "Solano"                    },
                new string[] { "400532",	"Saint Louis School of Solano",			                                        "REGION II",	"Nueva Vizcaya",	            "Solano"                    },
                new string[] { "400536",	"Our Lady of Fatima School of Villaverde",			                            "REGION II",	"Nueva Vizcaya",	            "Villaverde"                },
                new string[] { "400540",	"Saint Mark's School",			                                                "REGION II",	"Quirino",	                    "Cabarroguis"               },
                new string[] { "400543",	"Saint Mary's Academy",			                                                "REGION II",	"Quirino",	                    "Diffun"                    },
                new string[] { "600016",	"Quirino State University-Main Campus, Diffun",		                            "REGION II",	"Quirino",	                    "Diffun"                    },
                new string[] { "400546",	"Saint Vincent School",			                                                "REGION II",	"Quirino",	                    "Maddela"                   },
                new string[] { "416501",	"Maddela Marvelous Grace Christian School, Inc.",	                            "REGION II",	"Quirino",	                    "Maddela"                   },
                #endregion

            };
            Schools.AddRange(DBInitializerSchoolRegion4A.AddDefaultSchool());
            Schools.AddRange(DBInitializerSchoolRegion4B.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion5.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion6.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion7.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion8.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion9.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegion10.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegionARMM.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegionCAR.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegionCARAGA.AddDefaultSchools());
            Schools.AddRange(DBInitializerSchoolRegionNCR.AddDefaultSchools());
            cityMunicipalities = dataContext.Set<CityMunicipality>();

            regionEntity = dataContext.Set<Region>();
            provinceEntity = dataContext.Set<Province>();


            var municipalList = cityMunicipalities.AsNoTracking().ToList();
            var resultRegion = regionEntity.AsNoTracking().ToList();
            var resultProvince = provinceEntity.AsNoTracking().ToList();

            for (int i = 0; i < Schools.Count; i++)
            {
                string provinceName = Schools[i][3].ToUpper();
                string regionName = Schools[i][2].ToUpper();
                string municipalityName = Schools[i][4].ToUpper();
                var idProvince = resultProvince.Where(x => x.ProvinceName ==provinceName  ).FirstOrDefault();
                var idRegion = regionEntity.Where(x => x.Description == regionName).FirstOrDefault();


                int regionId = Convert.ToInt32(idRegion.RegionID);
                int provinceId = Convert.ToInt32(idProvince.ProvinceID);
                var idMunicapality = cityMunicipalities.Where(x=> 
                            x.RegionID == regionId && 
                            x.ProvinceID == provinceId
                            && x.CityMunicipalityName == municipalityName).FirstOrDefault();

                if (idMunicapality!=null )
                {

                    var school = new Domain.School.School
                    {
                        SchoolCode = Schools[i][0],
                        SchoolName = Schools[i][1],
                        RegionID = regionId,
                        ProvinceID = provinceId,
                        CityMunicipalityID = Convert.ToInt32(idMunicapality.CityMunicipalityID),
                        Status = true
                    };
                    dataContext.School.Add(school);
                    dataContext.SaveChanges();
                }
            }
        }

    }
}
