using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegionIVB
    {
        public static void AddDefaultSchool(DataContext dataContext)
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "403376",    "Educational Systems Technological Institute",                                      "REGION IV-B",          "Marinduque",           "Boac"                  },
                new string[] { "403379",    "Saint Mary's College of Marinduque",                                               "REGION IV-B",          "Marinduque",           "Boac"                  },
                new string[] { "600046",    "Marinduque State College",                                                         "REGION IV-B",          "Marinduque",           "Boac"                  },
                new string[] { "403381",    "Marinduque Victorians College (Formerly Buenavista Academy)",                      "REGION IV-B",          "Marinduque",           "Buenavista"            },
                new string[] { "403384",    "Marinduque Midwest College",                                                       "REGION IV-B",          "Marinduque",           "Gasan"                 },
                new string[] { "403387",    "Marinduque Academy",                                                               "REGION IV-B",          "Marinduque",           "Mogpog"                },
                new string[] { "403388",    "Quezon-Roxas High School of Marinduque, Inc.",                                     "REGION IV-B",          "Marinduque",           "Mogpog"                },
                new string[] { "403392",    "Malindig Institute Foundation, Inc.",                                              "REGION IV-B",          "Marinduque",           "Santa Cruz"            },
                new string[] { "403395",    "Santa Cruz Institute (Marinduque), Inc.",                                          "REGION IV-B",          "Marinduque",           "Santa Cruz"            },
                new string[] { "403397",    "Our Mother of Perpetual Succor Academy",                                           "REGION IV-B",          "Marinduque",           "Torrijos"              },
                new string[] { "403399",    "San Rafael High School",                                                           "REGION IV-B",          "Occidental Mindoro",   "Abra de Ilog"          },
                new string[] { "403402",    "Stella Maris School",                                                              "REGION IV-B",          "Occidental Mindoro",   "Lubang"                },
                new string[] { "403408",    "West Mindoro Academy",                                                             "REGION IV-B",          "Occidental Mindoro",   "Mamburao"              },
                new string[] { "406251",    "Occidental Mindoro State College-Mamburao Campus",                                 "REGION IV-B",          "Occidental Mindoro",   "Mamburao"              },
                new string[] { "429516",    "Katutubo Excel Schools, Inc.",                                                     "REGION IV-B",          "Occidental Mindoro",   "Mamburao"              },
                new string[] { "403410",    "Colegio de San Sebastian",                                                         "REGION IV-B",          "Occidental Mindoro",   "Sablayan"              },
                new string[] { "403411",    "D-SHEP Foundation Academy",                                                        "REGION IV-B",          "Occidental Mindoro",   "Sablayan"              },
                new string[] { "406249",    "Occidental Mindoro State College-Sablayan Campus",                                 "REGION IV-B",          "Occidental Mindoro",   "Sablayan"              },
                new string[] { "403419",    "Bethany School of Technology and Humanities, Inc.",                                "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "403421",    "Divine Word College of San Jose",                                                  "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "403428",    "San Jose Adventist Academy",                                                       "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "405436",    "Capt. Lawrence A. Cooper Technical College, Inc.-San Jose",                        "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "406231",    "Occidental Mindoro State College-Labangan Campus",                                 "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "406239",    "Occidental Mindoro State College-Murtha Campus",                                   "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "407522",    "Holy Family Academy",                                                              "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "429509",    "Philippine Central Islands College",                                               "REGION IV-B",          "Occidental Mindoro",   "San Jose"              },
                new string[] { "402376",    "Baco Community College",                                                           "REGION IV-B",          "Oriental Mindoro",     "Baco"                  },
                new string[] { "403430",    "Baco Catholic School",                                                             "REGION IV-B",          "Oriental Mindoro",     "Baco"                  },
                new string[] { "403431",    "Bansud Institute, Inc.",                                                           "REGION IV-B",          "Oriental Mindoro",     "Bansud"                },
                new string[] { "403437",    "Eastern Mindoro College",                                                          "REGION IV-B",          "Oriental Mindoro",     "Bongabong"             },
                new string[] { "403438",    "St. Joseph Academy",                                                               "REGION IV-B",          "Oriental Mindoro",     "Bongabong"             },
                new string[] { "430016",    "Innovative College of Science and Technology",                                     "REGION IV-B",          "Oriental Mindoro",     "Bongabong"             },
                new string[] { "600048",    "Mindoro State College of Agriculture and Technology-Bongabong Campus",             "REGION IV-B",          "Oriental Mindoro",     "Bongabong"             },
                new string[] { "402370",    "ACLC College of Calapan",                                                          "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "402371",    "Southwestern Luzon Maritime Institute Foundation",                                 "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "403545",    "Divine Word College of Calapan",                                                   "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "403546",    "Holy Infant Academy",                                                              "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "403549",    "Luna Goco Colleges",                                                               "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "403550",    "Southfields Educational Philippines, Inc",                                         "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "405432",    "Advanced Skills Training and Education Services, Inc.",                            "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "406200",    "City College of Calapan",                                                          "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "407051",    "International Technological Institute of Arts and Tourism",                        "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "432007",    "St. Anthony College of Calapan City, Inc.",                                        "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "600045",    "Mindoro State College of Agriculture and Technology-Calapan City Campus",          "REGION IV-B",          "Oriental Mindoro",     "City of Calapan"       },
                new string[] { "402377",    "Erhard Science and Technological Institute - Oriental Mindoro, Inc. (ESTI-OMI)",   "REGION IV-B",          "Oriental Mindoro",     "Gloria"                },
                new string[] { "407523",    "Sacred Heart Academy",                                                             "REGION IV-B",          "Oriental Mindoro",     "Gloria"                },
                new string[] { "403443",    "Mansalay Catholic High School",                                                    "REGION IV-B",          "Oriental Mindoro",     "Mansalay"              },
                new string[] { "403446",    "Agustin Gutierrez Memorial Academy",                                               "REGION IV-B",          "Oriental Mindoro",     "Naujan"                },
                new string[] { "403448",    "Naujan Academy",                                                                   "REGION IV-B",          "Oriental Mindoro",     "Naujan"                },
                new string[] { "402380",    "Pinamalayan Maritime Foundation and Technological College, Inc.",                  "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "403451",    "Abada College",                                                                    "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "403453",    "EMA Emits College, Philippines",                                                   "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "403455",    "Immaculate Heart of Mary Academy",                                                 "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "405452",    "Divine Word College of Calapan-Pinamalayan Campus",                                "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "406959",    "Southwestern Institute of Business and Technology",                                "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "430020",    "Institute of Business, Science and Medical Arts, Inc.",                            "REGION IV-B",          "Oriental Mindoro",     "Pinamalayan"           },
                new string[] { "403461",    "Pola Catholic School",                                                             "REGION IV-B",          "Oriental Mindoro",     "Pola"                  },
                new string[] { "403463",    "Prince of Peace College Inc.",                                                     "REGION IV-B",          "Oriental Mindoro",     "Puerto Galera"         },
                new string[] { "403464",    "Puerto Galera Academy",                                                            "REGION IV-B",          "Oriental Mindoro",     "Puerto Galera"         },
                new string[] { "430005",    "Gloders College, Inc.",                                                            "REGION IV-B",          "Oriental Mindoro",     "Puerto Galera"         },
                new string[] { "403466",    "Clarendon College",                                                                "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "403468",    "John Paul College",                                                                "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "403473",    "Roxas Seventh-Day Adventist Academy",                                              "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "403475",    "Santo Niño School of Roxas",                                                       "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "430012",    "Gelacio I. Yason Foundation-Family Farm School, Inc.",                             "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "430019",    "Paradigm Colleges of Science and Technology",                                      "REGION IV-B",          "Oriental Mindoro",     "Roxas"                 },
                new string[] { "403476",    "Northern Mindoro Academy",                                                         "REGION IV-B",          "Oriental Mindoro",     "San Teodoro"           },
                new string[] { "403478",    "Grace Mission College",                                                            "REGION IV-B",          "Oriental Mindoro",     "Socorro"               },
                new string[] { "403480",    "Mina de Oro Catholic School",                                                      "REGION IV-B",          "Oriental Mindoro",     "Socorro"               },
                new string[] { "402379",    "Mina De Oro Institute of Science and Technology",                                  "REGION IV-B",          "Oriental Mindoro",     "Victoria"              },
                new string[] { "403481",    "ACMCL College",                                                                    "REGION IV-B",          "Oriental Mindoro",     "Victoria"              },
                new string[] { "403482",    "Good Shepherd Academy",                                                            "REGION IV-B",          "Oriental Mindoro",     "Victoria"              },
                new string[] { "403485",    "Oriental Mindoro Academy",                                                         "REGION IV-B",          "Oriental Mindoro",     "Victoria"              },
                new string[] { "600049",    "Mindoro State College of Agriculture and Technology-Main Campus",                  "REGION IV-B",          "Oriental Mindoro",     "Victoria"              },
                new string[] { "600230",    "Western Philippines University-Main",                                              "REGION IV-B",          "Palawan",              "Aborlan"               },
                new string[] { "403488",    "Leonides S. Virata Memorial School",                                               "REGION IV-B",          "Palawan",              "Bataraza"              },
                new string[] { "403491",    "Sacred Heart of Jesus High School",                                                "REGION IV-B",          "Palawan",              "Brooke's Point"        },
                new string[] { "403492",    "St. Augustine's Academy",                                                          "REGION IV-B",          "Palawan",              "Coron"                 },
                new string[] { "403506",    "Loyola College of Culion",                                                         "REGION IV-B",          "Palawan",              "Culion"                },
                new string[] { "403493",    "Saint Joseph Academy",                                                             "REGION IV-B",          "Palawan",              "Cuyo"                  },
                new string[] { "403499",    "Palawan Adventist Academy",                                                        "REGION IV-B",          "Palawan",              "Narra"                 },
                new string[] { "403500",    "San Francisco Javier College",                                                     "REGION IV-B",          "Palawan",              "Narra"                 },
                new string[] { "600231",    "Palawan State University-Narra",                                                   "REGION IV-B",          "Palawan",              "Narra"                 },
                new string[] { "402388",    "STI College - Puerto Princesa",                                                    "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "403532",    "Holy Trinity University",                                                          "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "403536",    "Palawan Hope Christian School",                                                    "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "403537",    "Palawan Polytechnic College, Inc",                                                 "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "403541",    "Seminario De San Jose",                                                            "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "405456",    "ACLC College of Puerto Princesa",                                                  "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "407632",    "Palawan Technological College, Inc.",                                              "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "431503",    "FullBright Colleges, Inc.",                                                        "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "431506",    "Jesus, the Divine Son Academy, Inc.",                                              "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "431511",    "Center for Positive Futures, Inc. (Puerto Princesa City)",                         "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "600051",    "Palawan State University-Main Campus",                                             "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "600306",    "Palawan State University-Cuyo",                                                    "REGION IV-B",          "Palawan",              "Puerto Princesa City"  },
                new string[] { "600232",    "Palawan State University-Roxas",                                                   "REGION IV-B",          "Palawan",              "Roxas"                 },
                new string[] { "403505",    "Saint Ezekiel Moreno High School",                                                 "REGION IV-B",          "Palawan",              "Taytay"                },
                new string[] { "430514",    "Faith Adventist Academy",                                                          "REGION IV-B",          "Palawan",              "Taytay"                },
                new string[] { "600233",    "Palawan State University-Taytay",                                                  "REGION IV-B",          "Palawan",              "Taytay"                },
                new string[] { "403515",    "Adventist Mission Academy of Romblon (AMAR) Inc.",                                 "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "403523",    "Virginia Centurione Bracelli School",                                              "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "431010",    "Erhard Systems Technological Institute",                                           "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "431011",    "Epiphany School of Peace and Goodwill, Inc.",                                      "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "431013",    "Colegio de Tablas",                                                                "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "600053",    "Romblon State University",                                                         "REGION IV-B",          "Romblon",              "Odiongan"              },
                new string[] { "431014",    "Montfort Academy",                                                                 "REGION IV-B",          "Romblon",              "Romblon"               },
                new string[] { "403525",    "Holy Rosary Academy",                                                              "REGION IV-B",          "Romblon",              "San Agustin"           },
                new string[] { "403526",    "Badajoz Tablas College",                                                           "REGION IV-B",          "Romblon",              "San Agustin"           },
                new string[] { "403527",    "Fabella Institute",                                                                "REGION IV-B",          "Romblon",              "San Andres"            },
            };
        }
    }
}
