using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion12
    {
        public static void AddDefaultSchool(DataContext dataContext)
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "403878",    "AMA Computer College-Cotabato City",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "403879",    "STI College - Cotabato",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405797",    "Antonio R. Pacheco College, Inc.",             "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405800",    "Cotabato City Institute",          "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405803",    "Nahdah Central Academy",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405806",    "Notre Dame of Cotabato, Inc",          "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405816",    "Shariff Kabunsuan College, Inc.",          "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405818",    "St. Benedict College of Cotabato, Inc.",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "469509",    "Dr. P. Ocampo Colleges, Inc.",             "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "469517",    "Notre Dame-RVM College of Cotabato",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "469530",    "Notre Dame University",            "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "469532",    "Coland Systems Technology, Inc",           "REGION XII",   "Cotabato City",    "Cotabato City" },
                new string[] { "405593",    "Notre Dame of Genio Edcor, Inc.",          "REGION XII",   "North Cotabato",   "Alamada" },
                new string[] { "467504",    "St. Uriel College, Inc.",          "REGION XII",   "North Cotabato",   "Antipas" },
                new string[] { "467571",    "Untalan Institute of Technology",          "REGION XII",   "North Cotabato",   "Antipas" },
                new string[] { "403987",    "Cotabato Foundation College of Science and Technology",            "REGION XII",   "North Cotabato",   "Arakan" },
                new string[] { "467543",    "Sahmyok International Academy",            "REGION XII",   "North Cotabato",   "Arakan" },
                new string[] { "404010",    "North Valley College Foundation Inc.",             "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405817",    "North Point College of Arts and Technology, Inc.",             "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405859",    "ABC Educational Development Center",           "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405862",    "Central Mindanao Colleges",            "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405867",    "Notre Dame of Kidapawan College",          "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405870",    "St. Mary's Academy of Kidapawan, Inc",             "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "470513",    "Kidapawan Technical School and Security Training Center, Inc.",            "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "470516",    "Colegio de Kidapawan, Inc.",           "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "470523",    "Kidapawan Doctors College, Inc.",          "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "600278",    "University of Southern Mindanao-Kidapawan",            "REGION XII",   "North Cotabato",   "City of Kidapawan" },
                new string[] { "405598",    "Kabacan Wesleyan Academy, Inc.",           "REGION XII",   "North Cotabato",   "Kabacan" },
                new string[] { "405599",    "Notre Dame of Kabacan, Inc.",          "REGION XII",   "North Cotabato",   "Kabacan" },
                new string[] { "405601",    "St. Luke's Institute",             "REGION XII",   "North Cotabato",   "Kabacan" },
                new string[] { "600102",    "University of Southern Mindanao",          "REGION XII",   "North Cotabato",   "Kabacan" },
                new string[] { "405607",    "Notre Dame of Libungan",           "REGION XII",   "North Cotabato",   "Libungan" },
                new string[] { "405612",    "Notre Dame of Makilala, Inc.",             "REGION XII",   "North Cotabato",   "Makilala" },
                new string[] { "405813",    "Makilala Institute of Science and Technology",             "REGION XII",   "North Cotabato",   "Makilala" },
                new string[] { "405615",    "Matalam Institute of Science and Technology, Inc.",            "REGION XII",   "North Cotabato",   "Matalam" },
                new string[] { "467549",    "Matalam Polytechnic College, Inc.",            "REGION XII",   "North Cotabato",   "Matalam" },
                new string[] { "405617",    "I-link College of Science and Technology",             "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "405618",    "St. Mary's Academy",           "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "405619",    "Notre Dame of Midsayap College",           "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "405621",    "Southern Christian College",           "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "467511",    "Midsayap Community College",           "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "467527",    "St. Jude College of Science and Technology",           "REGION XII",   "North Cotabato",   "Midsayap" },
                new string[] { "405628",    "Notre Dame of M'lang",             "REGION XII",   "North Cotabato",   "M'lang" },
                new string[] { "405629",    "Southern Baptist College",             "REGION XII",   "North Cotabato",   "M'lang" },
                new string[] { "405632",    "Notre Dame of Pigcawayan, Inc.",           "REGION XII",   "North Cotabato",   "Pigcawayan" },
                new string[] { "405636",    "The Notre Dame of Pikit, Inc.",            "REGION XII",   "North Cotabato",   "Pikit" },
                new string[] { "467539",    "President Roxas Institute of Technology, Inc.",            "REGION XII",   "North Cotabato",   "President Roxas" },
                new string[] { "405641",    "Notre Dame of Tulunan",            "REGION XII",   "North Cotabato",   "Tulunan" },
                new string[] { "406319",    "Primasia Foundation College, Inc.",            "REGION XII",   "Sarangani",    "Alabel" },
                new string[] { "405645",    "Notre Dame of Glan, Inc.",             "REGION XII",   "Sarangani",    "Glan" },
                new string[] { "405835",    "Green Valley College Foundation, Inc.-Glan",           "REGION XII",   "Sarangani",    "Glan" },
                new string[] { "405646",    "Notre Dame of Kiamba, Inc.",           "REGION XII",   "Sarangani",    "Kiamba" },
                new string[] { "405647",    "Southern Cotabato Academy, Inc.",          "REGION XII",   "Sarangani",    "Kiamba" },
                new string[] { "407002",    "Euro Asia College of Technology, Inc.",            "REGION XII",   "Sarangani",    "Kiamba" },
                new string[] { "405648",    "Notre Dame of Maasim",             "REGION XII",   "Sarangani",    "Maasim" },
                new string[] { "405836",    "Green Valley College Foundation, Inc.-Maasim",             "REGION XII",   "Sarangani",    "Maasim" },
                new string[] { "405649",    "Edenton Mission College",          "REGION XII",   "Sarangani",    "Maitum" },
                new string[] { "405650",    "Notre Dame of Maitum, Inc.",           "REGION XII",   "Sarangani",    "Maitum" },
                new string[] { "406633",    "Patriarch-Ambassador College of the Philippines, Inc.",            "REGION XII",   "Sarangani",    "Maitum" },
                new string[] { "405651",    "Holy Infant School of Malungon",           "REGION XII",   "Sarangani",    "Malungon" },
                new string[] { "405654",    "Pablo Omerez Cedeño Memorial Learning Center",             "REGION XII",   "Sarangani",    "Malungon" },
                new string[] { "405655",    "Malandag Adventist Academy, Inc.",             "REGION XII",   "Sarangani",    "Malungon" },
                new string[] { "405656",    "Malandag Institute, Inc.",             "REGION XII",   "Sarangani",    "Malungon" },
                new string[] { "468005",    "Malungon Christian Learning Center",           "REGION XII",   "Sarangani",    "Malungon" },
                new string[] { "405661",    "Notre Dame of Banga",          "REGION XII",   "South Cotabato",   "Banga" },
                new string[] { "406641",    "Green Valley College Foundation, Inc. - Banga",            "REGION XII",   "South Cotabato",   "Banga" },
                new string[] { "468509",    "Mindanao Community School",            "REGION XII",   "South Cotabato",   "Banga" },
                new string[] { "468510",    "Notre Dame of Lamba",          "REGION XII",   "South Cotabato",   "Banga" },
                new string[] { "403901",    "ACLC College of Marbel",           "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "403916",    "Goldenstate College of Koronadal City, Inc.",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "403941",    "Regency Polytechnic College-Maritime High School",             "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "403946",    "STI College - Koronadal",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405878",    "Green Valley College Foundation, Inc.",            "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405881",    "King's College of Marbel",             "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405891",    "Notre Dame-Siena School of Marbel",            "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405893",    "Notre Dame of Marbel University",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405894",    "Notre Dame of San Jose",           "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "405948",    "Ramon Magsaysay Memorial Colleges-Marbel, Inc.",           "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "406631",    "Marbel Institute of Technical College, Inc.",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "407007",    "International Cruise Ship College, Inc.",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "407040",    "Southern Institute of Technical Education and Driving School, Inc.",           "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "407575",    "Holy Child College of Information Technology, Inc.",           "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "471002",    "Perezville Kiddie Care and Learning School, Incorporated",             "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "471015",    "St. Alexius College",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "471017",    "Marvelous College of Technology, Inc.",            "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "471021",    "Korbel Foundation College, Inc.",          "REGION XII",   "South Cotabato",   "City of Koronadal" },
                new string[] { "403882",    "ACLC College of General Santos City",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403883",    "AMA Computer College-General Santos City",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403891",    "Gensan College of Technology, Inc.",           "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403894",    "Gensantos Foundation College, Inc.",           "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403897",    "Goldenstate College",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403899",    "STI College - General Santos",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "403900",    "Villamor College of Business and Arts",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405832",    "General Santos Hope Christian School",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405833",    "Holy Trinity College of General Santos City",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405844",    "New Era University",           "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405846",    "Notre Dame of Dadiangas University",           "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405850",    "Ramon Magsaysay Memorial Colleges",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405854",    "The Heritage Academy of the Philippines",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405858",    "Shalom Crest Wizard Academy",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405950",    "Brokenshire College - SOCSKSARGEN, Inc.",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "406625",    "Passionist Technological Institute, Inc.",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "407006",    "General Santos Doctors' Medical School Foundation, Inc.",          "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "407573",    "Notre Dame - Siena College of General Santos City",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "407574",    "The Quantum Academy, Inc.",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "407826",    "Joji Ilagan International School of Hotel and Tourism Management",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "470004",    "Notre Dame of Dadiangas University - Integrated Basic Education Dept. (Espina Campus)",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "470005",    "Passionist Sisters' School, Inc.",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "470007",    "Stratford International School",           "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "470008",    "Canonico Antonio Institute, Inc.",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "470047",    "Cronasia Foundation College, Inc",             "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "600100",    "Mindanao State University-General Santos City",            "REGION XII",   "South Cotabato",   "General Santos City (Dadiangas)" },
                new string[] { "405718",    "King's of Lake Sebu",          "REGION XII",   "South Cotabato",   "Lake Sebu" },
                new string[] { "405756",    "Santa Cruz Mission School, Inc.",          "REGION XII",   "South Cotabato",   "Lake Sebu" },
                new string[] { "405664",    "Notre Dame of Norala, Inc.",           "REGION XII",   "South Cotabato",   "Norala" },
                new string[] { "406642",    "Green Valley College Foundation, Inc. - Norala",           "REGION XII",   "South Cotabato",   "Norala" },
                new string[] { "405666",    "B.E.S.T. College of Polomolok, Inc.",          "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405669",    "Christian School of Polomolok, Inc.",          "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405671",    "Dole Philippines School",          "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405673",    "General Santos Academy",           "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405675",    "Matutum View Baptist Academy, Inc.",           "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405677",    "Notre Dame- Siena College of Polomolok",           "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405680",    "Schola De San Jose",           "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "468574",    "St. Lorenzo School of Polomolok, Inc.",            "REGION XII",   "South Cotabato",   "Polomolok" },
                new string[] { "405711",    "Notre Dame of Sto. Niño",          "REGION XII",   "South Cotabato",   "Santo Niño" },
                new string[] { "407042",    "Green Valley College Foundation, Inc. - Sto. Niño",            "REGION XII",   "South Cotabato",   "Santo Niño" },
                new string[] { "405686",    "Allah Valley Academy",             "REGION XII",   "South Cotabato",   "Surallah" },
                new string[] { "405689",    "Moloy High School, Inc.",          "REGION XII",   "South Cotabato",   "Surallah" },
                new string[] { "405693",    "Thelsan School, Inc.",             "REGION XII",   "South Cotabato",   "Surallah" },
                new string[] { "468517",    "Holy Child College of Information Technology, Inc. -Surallah",             "REGION XII",   "South Cotabato",   "Surallah" },
                new string[] { "405695",    "Notre Dame of New Iloilo",             "REGION XII",   "South Cotabato",   "Tantangan" },
                new string[] { "406643",    "Green Valley College Foundation, Inc. - T'boli",           "REGION XII",   "South Cotabato",   "T'boli" },
                new string[] { "405705",    "Matutum View Academy of SDA, Inc.",            "REGION XII",   "South Cotabato",   "Tupi" },
                new string[] { "406031",    "South East Asian Institute of Technology Inc.",            "REGION XII",   "South Cotabato",   "Tupi" },
                new string[] { "405761",    "Notre Dame of Masiag Inc.",            "REGION XII",   "Sultan Kudarat",   "Bagumbayan" },
                new string[] { "469014",    "Kabuling Learning Center",             "REGION XII",   "Sultan Kudarat",   "Bagumbayan" },
                new string[] { "400778",    "St. John Early Learning Center, Inc.",             "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "400779",    "VMC Asian College Foundation, Inc",            "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "403952",    "STI College - Tacurong",           "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "405780",    "Tacurong Siloam ABC Learning Center",          "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "405781",    "Notre Dame of Tacurong College",           "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "405787",    "Notre Dame-Siena College of Tacurong, Inc",            "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "405789",    "Southern Mindanao Institute of Technology, Inc.",          "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "600103",    "Sultan Kudarat State University-Main",             "REGION XII",   "Sultan Kudarat",   "City of Tacurong" },
                new string[] { "406667",    "Green Valley College Foundation, Inc. - Columbio",             "REGION XII",   "Sultan Kudarat",   "Columbio" },
                new string[] { "405762",    "Notre Dame of Dukay, Inc.",            "REGION XII",   "Sultan Kudarat",   "Esperanza" },
                new string[] { "405763",    "Notre Dame of Esperanza",          "REGION XII",   "Sultan Kudarat",   "Esperanza" },
                new string[] { "469013",    "4A School of Excellence, Inc.",            "REGION XII",   "Sultan Kudarat",   "Esperanza" },
                new string[] { "407417",    "International School for Advance Genuine and Education, Inc.",             "REGION XII",   "Sultan Kudarat",   "Isulan" },
                new string[] { "403947",    "Green Valley College Foundation, Inc.-Isulan, Sultan Kudarat",             "REGION XII",   "Sultan Kudarat",   "Isulan (Capital)" },
                new string[] { "405765",    "King's College of Isulan",             "REGION XII",   "Sultan Kudarat",   "Isulan (Capital)" },
                new string[] { "405769",    "Notre Dame of Isulan, Inc.",           "REGION XII",   "Sultan Kudarat",   "Isulan (Capital)" },
                new string[] { "405773",    "Notre Dame of Kalamansig, Inc.",           "REGION XII",   "Sultan Kudarat",   "Kalamansig" },
                new string[] { "405777",    "Notre Dame of Lambayong, Inc.",            "REGION XII",   "Sultan Kudarat",   "Lambayong (Mariano Marcos)" },
                new string[] { "403949",    "West Celebes College of Technology, Inc.",             "REGION XII",   "Sultan Kudarat",   "Lebak" },
                new string[] { "405775",    "Notre Dame Of Salaman College",            "REGION XII",   "Sultan Kudarat",   "Lebak" },
                new string[] { "405776",    "Salaman Institute",            "REGION XII",   "Sultan Kudarat",   "Lebak" },
                new string[] { "405774",    "Notre Dame of Milbuk",             "REGION XII",   "Sultan Kudarat",   "Palimbang" },
                new string[] { "407576",    "Notre Dame of Katiko, Inc.",           "REGION XII",   "Sultan Kudarat",   "President Quirino" },
                new string[] { "469030",    "President Quirino Treasured Child, Inc",           "REGION XII",   "Sultan Kudarat",   "President Quirino" },
                new string[] { "405792",    "Notre Dame of Kulaman, Inc.",          "REGION XII",   "Sultan Kudarat",   "Sen. Ninoy Aquino" },
                new string[] { "405795",    "Kulaman Academy",          "REGION XII",   "Sultan Kudarat",   "Sen. Ninoy Aquino" },
                new string[] { "406101",    "Senator Ninoy Aquino College Foundation",          "REGION XII",   "Sultan Kudarat",   "Sen. Ninoy Aquino" },
                new string[] { "469031",    "King's of Lagubang",           "REGION XII",   "Sultan Kudarat",   "Sen. Ninoy Aquino" },
            };
        }
    }
}