using Domain.School;
using Domain.Taxonomy;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain.Seed
{
    public class DBInitiializerSubClass
    {
        private static DbSet<TrackCategory> trackCategoryEntity;
        private static DbSet<Region> regionEntity;
        private static DbSet<Province> provinceEntity;

        public  static void CreateDefaultData(DataContext dataContext)
        {
            dataContext.Database.EnsureCreated();
            if (dataContext.School.Count() <= 0)
                AddDefaultSchool(dataContext);
        }


        public static void AddDefaultSchool(DataContext dataContext)
        {
            List<string[]> Schools = new List<string[]> {
                #region ARMM
                new string[] { "405839",    "Mindanao Autonomous College Foundation, Inc.",                                 "ARMM",         "Basilan",                      "City of Lamitan"           },
                new string[] { "406057",    "Claret School of Lamitan",                                                     "ARMM",         "Basilan",                      "City of Lamitan"           },
                new string[] { "406921",    "Hardam Furigay Colleges Foundation, Inc.",                                     "ARMM",         "Basilan",                      "City of Lamitan"           },
                new string[] { "407069",    "The Mariam School of Nursing, Inc.",                                           "ARMM",         "Basilan",                      "City of Lamitan"           },
                new string[] { "406059",    "Claret School of Maluso",                                                      "ARMM",         "Basilan",                      "Maluso"                    },
                new string[] { "406060",    "Claret School of Tumahubong",                                                  "ARMM",         "Basilan",                      "Sumisip"                   },
                new string[] { "406063",    "San Isidro High School of Balabagan",                                          "ARMM",         "Lanao del Sur",                "Balabagan"                 },
                new string[] { "600120",    "Adiong Memorial Polytechnic State College",                                    "ARMM",         "Lanao del Sur",                "Ditsaan-Ramain"            },
                new string[] { "406066",    "Our Lady of Peace High School",                                                "ARMM",         "Lanao del Sur",                "Malabang"                  },
                new string[] { "476002",    "Felix A. Panganiban (FAP) Academy of the Philippines, Inc.",                   "ARMM",         "Lanao del Sur",                "Malabang"                  },
                new string[] { "406008",    "Jamiatul Philippine Al-Islamia",                                               "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406086",    "Aba Al-khail Computer School",                                                 "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406089",    "Dansalan College Foundation",                                                  "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406091",    "IBN Siena Integrated School Foundation",                                       "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406093",    "Jamiatu Muslim Mindanao",                                                      "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406096",    "Mapandi Memorial College",                                                     "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "406097",    "Marawi Capitol College Foundation, Inc.",                                      "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478003",    "Marawi Foundation Academy, Inc.",                                              "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478008",    "Masiricampo Abantas Memorial Educational Center, Inc.",                        "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478011",    "Lanao Islamic Paramedical College Foundation, Inc",                            "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478015",    "SMD Foundation Academy",                                                       "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478017",    "RC-AKICFI Science Laboratory School",                                          "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478018",    "Jamiatu Marawi Al-Islamia Foundation",                                         "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478019",    "Fountain Harvest Islamic Academy",                                             "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478020",    "Philippine Engineering and Agro-Industrial College, Inc.",                     "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "478021",    "Datu Blo Umpar Adiong (BUAD) Agricultural School Foundation, Inc.",            "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "600121",    "Mindanao State University-LNCAT",                                              "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "600122",    "Mindanao State University-Marawi",                                             "ARMM",         "Lanao del Sur",                "Marawi City"               },
                new string[] { "475505",    "As-salihein Integrated School Foundation, Inc.",                               "ARMM",         "Lanao del Sur",                "Tamparan"                  },
                new string[] { "405861",    "Adiong Memorial College Foundation, Inc.",                                     "ARMM",         "Lanao del Sur",                "Wao"                       },
                new string[] { "406061",    "La Purisima High School",                                                      "ARMM",         "Lanao del Sur",                "Wao"                       },
                new string[] { "405841",    "VMC Asian College Foundation, Inc.-Kauran Branch",                             "ARMM",         "Maguindanao",                  "Ampatuan"                  },
                new string[] { "476505",    "Maguindanao Institute of Technology and Learning Center, Inc.",                "ARMM",         "Maguindanao",                  "Buluan"                    },
                new string[] { "476519",    "Buluan Technical Educational School of Life, Inc.",                            "ARMM",         "Maguindanao",                  "Buluan"                    },
                new string[] { "476520",    "Eastern Kutawato Islamic Institute, Inc.",                                     "ARMM",         "Maguindanao",                  "Buluan"                    },
                new string[] { "400844",    "Bai Malgen Mama College Inc.",                                                 "ARMM",         "Maguindanao",                  "Datu Odin Sinsuat"         },
                new string[] { "476503",    "Sharif Awliya Academy",                                                        "ARMM",         "Maguindanao",                  "Datu Odin Sinsuat"         },
                new string[] { "600194",    "Mindanao State University-Maguindanao",                                        "ARMM",         "Maguindanao",                  "Datu Odin Sinsuat"         },
                new string[] { "406673",    "Datu Ibrahim Paglas Memorial College",                                         "ARMM",         "Maguindanao",                  "Datu Paglas"               },
                new string[] { "406070",    "Gani L. Abpi College, Inc.",                                                   "ARMM",         "Maguindanao",                  "Datu Piang"                },
                new string[] { "406071",    "Notre Dame of Dulawan",                                                        "ARMM",         "Maguindanao",                  "Datu Piang"                },
                new string[] { "407450",    "Lamalan Balis Flash Image Learning Center, Inc.",                              "ARMM",         "Maguindanao",                  "Datu Piang"                },
                new string[] { "476525",    "Southern Philippines Academy (SPA) College",                                   "ARMM",         "Maguindanao",                  "Datu Piang"                },
                new string[] { "406072",    "Notre Dame of Parang, Inc.",                                                   "ARMM",         "Maguindanao",                  "Parang"                    },
                new string[] { "406073",    "Notre Dame of Sarmiento, Inc",                                                 "ARMM",         "Maguindanao",                  "Parang"                    },
                new string[] { "476508",    "The Easter Joy School, Inc.",                                                  "ARMM",         "Maguindanao",                  "Parang"                    },
                new string[] { "476504",    "Sultan Kudarat Islamic Academy Foundation College",                            "ARMM",         "Maguindanao",                  "Sultan Kudarat (Nuling)"   },
                new string[] { "406074",    "Notre Dame of Upi, Inc.",                                                      "ARMM",         "Maguindanao",                  "Upi"                       },
                new string[] { "406075",    "St. Francis High School",                                                      "ARMM",         "Maguindanao",                  "Upi"                       },
                new string[] { "400857",    "Notre Dame of Jolo College",                                                   "ARMM",         "Sulu",                         "Jolo"                      },
                new string[] { "477001",    "Southwestern Mindanao Islamic Institute",                                      "ARMM",         "Sulu",                         "Jolo"                      },
                new string[] { "477006",    "Sulu College of Technology, Inc.",                                             "ARMM",         "Sulu",                         "Jolo"                      },
                new string[] { "600183",    "Sulu State College",                                                           "ARMM",         "Sulu",                         "Jolo"                      },
                new string[] { "600195",    "Mindanao State University",                                                    "ARMM",         "Sulu",                         "Jolo"                      },
                new string[] { "406079",    "Notre Dame of Siasi",                                                          "ARMM",         "Sulu",                         "Siasi"                     },
                new string[] { "477002",    "Central Sulu College",                                                         "ARMM",         "Sulu",                         "Siasi"                     },
                new string[] { "405845",    "Tawi-Tawi School of Midwifery, Inc.",                                          "ARMM",         "Tawi-Tawi",                    "Bongao"                    },
                new string[] { "406080",    "Notre Dame of Bongao",                                                         "ARMM",         "Tawi-Tawi",                    "Bongao"                    },
                new string[] { "477503",    "Mahardika Institute of Technology, Inc.",                                      "ARMM",         "Tawi-Tawi",                    "Bongao"                    },
                new string[] { "600124",    "Tawi-Tawi Regional Agricultural College-Main",                                 "ARMM",         "Tawi-Tawi",                    "Bongao"                    },
                new string[] { "600196",    "Mindanao State University-Tawi-Tawi",                                          "ARMM",         "Tawi-Tawi",                    "Bongao"                    },
                new string[] { "600329",    "Mindanao State University - Mapun Extension",                                  "ARMM",         "Tawi-Tawi",                    "Mapun"                     },
                new string[] { "600327",    "Mindanao State University - Sibutu Extension",                                 "ARMM",         "Tawi-Tawi",                    "Sibutu"                    },
                new string[] { "600328",    "Mindanao State University - Ungus Matata Extension",                           "ARMM",         "Tawi-Tawi",                    "Tandubas"                  },
                #endregion

                #region CAR
                new string[] { "400860",    "Data Center College of the Philippines",                                       "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "406102",    "Abra Valley Colleges",                                                         "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "406107",    "Holy Spirit Academy of Bangued",                                               "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "406109",    "St. Joseph Seminary",                                                          "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "478501",    "Divine Word College of Bangued",                                               "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "600197",    "Abra State Institute of Science and Technology-Bangued Campus",                "CAR",          "Abra",                         "Bangued"                   },
                new string[] { "406112",    "Abra Mountain Development Educational Center",                                 "CAR",          "Abra",                         "Bucloc"                    },
                new string[] { "406113",    "Heart of Mary High School",                                                    "CAR",          "Abra",                         "Dolores"                   },
                new string[] { "406115",    "Queen of Peace High School - Canan",                                           "CAR",          "Abra",                         "La Paz"                    },
                new string[] { "406116",    "Queen of Peace High School - La Paz",                                          "CAR",          "Abra",                         "La Paz"                    },
                new string[] { "406117",    "Our Lady of Guadalupe School",                                                 "CAR",          "Abra",                         "Lacub"                     },
                new string[] { "406118",    "Holy Cross School of Lagangilang, Inc.",                                       "CAR",          "Abra",                         "Lagangilang"               },
                new string[] { "600113",    "Abra State Institute of Sciences and Technology",                              "CAR",          "Abra",                         "Lagangilang"               },
                new string[] { "406122",    "Our Lady of Lourdes High School",                                              "CAR",          "Abra",                         "Manabo"                    },
                new string[] { "406124",    "Little Flower High School",                                                    "CAR",          "Abra",                         "Peñarrubia"                },
                new string[] { "406125",    "St. Mary's High School",                                                       "CAR",          "Abra",                         "Pidigan"                   },
                new string[] { "406126",    "Catholic High School of Pilar",                                                "CAR",          "Abra",                         "Pilar"                     },
                new string[] { "406127",    "Fr. Arnoldus High School",                                                     "CAR",          "Abra",                         "Sallapadan"                },
                new string[] { "406128",    "St. John High School",                                                         "CAR",          "Abra",                         "San Juan"                  },
                new string[] { "406129",    "Holy Ghost School",                                                            "CAR",          "Abra",                         "Tayum"                     },
                new string[] { "406132",    "St. Paul High School",                                                         "CAR",          "Abra",                         "Villaviciosa"              },
                new string[] { "600114",    "Apayao State College",                                                         "CAR",          "Apayao",                       "Conner"                    },
                new string[] { "406134",    "Saint Joseph High School of Flora, Inc.",                                      "CAR",          "Apayao",                       "Flora"                     },
                new string[] { "406136",    "Our Lady of Lourdes High School of Kabugao",                                   "CAR",          "Apayao",                       "Kabugao"                   },
                new string[] { "406137",    "Santo Rosario School of Pudtol, Inc.",                                         "CAR",          "Apayao",                       "Pudtol"                    },
                new string[] { "406138",    "Saint Paul's Academy of Sayangan, Inc.",                                       "CAR",          "Benguet",                      "Atok"                      },
                new string[] { "400861",    "AMA Computer College-Baguio City",                                             "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400867",    "Baguio College of Technology",                                                 "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400869",    "BSBT College, Inc.",                                                           "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400873",    "Casiciaco Recoletos Seminary, Inc.",                                           "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400883",    "Data Center College of the Philippines of Baguio City, Inc",                   "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400889",    "Informatics Baguio City Center, Inc.",                                         "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400903",    "Philippine Women's University - CDCEC, Baguio City, Inc.",                     "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "400906",    "STI College - Baguio",                                                         "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406209",    "Baguio Achievers' Academy Inc.",                                               "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406212",    "Baguio Central University",                                                    "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406214",    "Baguio City Academy College",                                                  "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406216",    "Baguio City Science Foundation",                                               "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406217",    "University of the Cordilleras",                                                "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406219",    "Baguio Patriotic High School",                                                 "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406221",    "Baguio Seventh-day Adventist School Academy",                                  "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406222",    "Baguio Siloam Christian Academy, Inc.",                                        "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406228",    "Disciples for Christ International School",                                    "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406230",    "Easter College",                                                               "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406255",    "Our Lady of Mt.Carmel Montessori",                                             "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406266",    "Small World Christian School Foundation",                                      "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406278",    "University of Baguio High School",                                             "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406285",    "Yesu Maeul Christian Academy",                                                 "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "407044",    "Saint Francis Xavier Seminary, Inc.",                                          "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "407316",    "NorthPhil Polytechnic Institute, Inc.",                                        "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "407460",    "University of Baguio Science High School",                                     "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481503",    "Pines City Colleges",                                                          "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481504",    "Berkeley School",                                                              "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481509",    "Academia de Sophia International",                                             "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481514",    "Educare Learning Center",                                                      "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481517",    "Remnant International College, Inc.",                                          "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481521",    "Shalom International School",                                                  "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481523",    "Christian Legacy Academy",                                                     "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481527",    "Baguio International Academy",                                                 "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481531",    "Union School International-Baguio City, Inc.",                                 "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481536",    "Saint Louis School, Inc.(Center) High School Department",                      "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481538",    "Westmont School Montessori",                                                   "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481542",    "Fame Golf Mission School, Inc.",                                               "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481545",    "St. Joseph De Mary Learning Center",                                           "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481564",    "Baguio Vision Christian Academy Foundation, Inc.",                             "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "481566",    "Saint Louis University",                                                       "CAR",          "Benguet",                      "Baguio City"               },
                new string[] { "406144",    "Sacred Heart High School of Itogon, Inc.",                                     "CAR",          "Benguet",                      "Itogon"                    },
                new string[] { "481510",    "Philippine BELL International School",                                         "CAR",          "Benguet",                      "Itogon"                    },
                new string[] { "400912",    "BVS College",                                                                  "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "400925",    "Philippine Nazarene College",                                                  "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "406014",    "Concordia College of Benguet, Inc.",                                           "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "406149",    "Cordillera Career Development College",                                        "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "406153",    "HOPE Christian Academy",                                                       "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "406156",    "San Jose School of La Trinidad, Inc",                                          "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "406162",    "Star Colleges",                                                                "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "479537",    "King's College of the Philippines",                                            "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "479540",    "Northskills Polytechnic College, Inc.",                                        "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "600116",    "Benguet State University-Secondary Lab School",                                "CAR",          "Benguet",                      "La Trinidad"               },
                new string[] { "407590",    "Immaculate Conception School",                                                 "CAR",          "Ifugao",                       "Banaue"                    },
                new string[] { "406176",    "The Ifugao Academy, Inc.",                                                     "CAR",          "Ifugao",                       "Kiangan"                   },
                new string[] { "406177",    "St. Joseph's School",                                                          "CAR",          "Ifugao",                       "Kiangan"                   },
                new string[] { "407645",    "Riverview Polytechnic and Academic School, Inc.",                              "CAR",          "Ifugao",                       "Kiangan"                   },
                new string[] { "406178",    "Don Bosco High School",                                                        "CAR",          "Ifugao",                       "Lagawe"                    },
                new string[] { "406180",    "San Francisco High School",                                                    "CAR",          "Ifugao",                       "Lamut"                     },
                new string[] { "406181",    "Assumption Academy",                                                           "CAR",          "Ifugao",                       "Mayoyao"                   },
                new string[] { "406182",    "St. Paul's Memorial School of Kalinga, Inc.",                                  "CAR",          "Kalinga",                      "Balbalan"                  },
                new string[] { "406183",    "St. Theresita High School of Salegseg, Inc.",                                  "CAR",          "Kalinga",                      "Balbalan"                  },
                new string[] { "400927",    "International School of Asia and the Pacific-Kalinga Campus",                  "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "400939",    "Cordillera A+ Computer Technology College",                                    "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "406188",    "Saint Tonis College, Inc.",                                                    "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "406192",    "St. Theresita High School - Tabuk",                                            "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "406195",    "Tabuk Institute",                                                              "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "407461",    "Saint William's Academy",                                                      "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "480511",    "Kalinga Colleges of Science and Technology",                                   "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "600198",    "Kalinga-Apayao State College",                                                 "CAR",          "Kalinga",                      "City of Tabuk"             },
                new string[] { "406185",    "St. Theresita's School of Lubuagan, Inc.",                                     "CAR",          "Kalinga",                      "Lubuagan"                  },
                new string[] { "406186",    "St. Theresita High School - Pinukpuk",                                         "CAR",          "Kalinga",                      "Pinukpuk"                  },
                new string[] { "406187",    "Saint Michael's Academy, Rizal, Inc.",                                         "CAR",          "Kalinga",                      "Rizal"                     },
                new string[] { "406198",    "St. Theresita's High School - Tinglayan",                                      "CAR",          "Kalinga",                      "Tinglayan"                 },
                new string[] { "406199",    "Bauko Catholic School",                                                        "CAR",          "Mt. Province",                 "Bauko"                     },
                new string[] { "406201",    "St. James High School of Mountain Province Inc.",                              "CAR",          "Mt. Province",                 "Besao"                     },
                new string[] { "406203",    "Saint Vincent's School",                                                       "CAR",          "Mt. Province",                 "Bontoc"                    },
                new string[] { "481005",    "XiJEN College of Mountain Province, Inc.",                                     "CAR",          "Mt. Province",                 "Bontoc"                    },
                new string[] { "406206",    "Saint Mary's School of Sagada",                                                "CAR",          "Mt. Province",                 "Sagada"                    },

                #endregion

                #region CARAGA
                new string[] { "405902",    "Buenavista Institute",                                                         "CARAGA",       "Agusan del Norte",             "Buenavista"                },
                new string[] { "405903",    "Saint James High School",                                                      "CARAGA",       "Agusan del Norte",             "Buenavista"                },
                new string[] { "404051",    "ACLC College of Butuan City, Inc.",                                            "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "404075",    "Asian College Foundation",                                                     "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "404077",    "Butuan Doctors' College",                                                      "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405954",    "Agusan Business and Arts Foundation, Inc.",                                    "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405955",    "Agusan Colleges, Inc.",                                                        "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405956",    "Colegio De Caraga Inc. (CDCI)",                                                "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405958",    "Angelicum Montessori School, Inc.",                                            "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405959",    "Balite Institute of Technology-Butuan",                                        "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405963",    "Butuan City Colleges",                                                         "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405971",    "Father Urios Institute of Technology of Ampayon, Inc.",                        "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405973",    "Holy Child Colleges of Butuan",                                                "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405977",    "Northeastern Mindanao Academy",                                                "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405981",    "Saint Joseph Institute of Technology",                                         "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405985",    "Timber City Academy",                                                          "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405986",    "Father Saturnino Urios University-Butuan City",                                "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "407089",    "Philippine Electronics and Communications Institute of Technology",            "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "407428",    "Center for Healthcare Professions Butuan",                                     "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "407429",    "Colegio De Liga ng mga Barangay",                                              "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "407578",    "Father Saturnino Urios University Archbishop Morelos Campus(Basic Ed)",        "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "408198",    "Saint Joseph Institute of Technology - Annex Campus",                          "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "600279",    "Caraga State University - Main Campus",                                        "CARAGA",       "Agusan del Norte",             "Butuan City"               },
                new string[] { "405910",    "Our Lady of Carmen Academy of Caraga, Inc.",                                   "CARAGA",       "Agusan del Norte",             "Carmen"                    },
                new string[] { "405904",    "Bishop Haden Institute, Inc.",                                                 "CARAGA",       "Agusan del Norte",             "City of Cabadbaran"        },
                new string[] { "405906",    "Candelaria Institute of Cabadbaran, Inc.",                                     "CARAGA",       "Agusan del Norte",             "City of Cabadbaran"        },
                new string[] { "405907",    "Mindanao Institute",                                                           "CARAGA",       "Agusan del Norte",             "City of Cabadbaran"        },
                new string[] { "405908",    "Northern Mindanao Colleges, Inc.",                                             "CARAGA",       "Agusan del Norte",             "City of Cabadbaran"        },
                new string[] { "600132",    "Caraga State University - Cabadbaran",                                         "CARAGA",       "Agusan del Norte",             "City of Cabadbaran"        },
                new string[] { "404040",    "Caraga Institute of Technology",                                               "CARAGA",       "Agusan del Norte",             "Kitcharao"                 },
                new string[] { "405911",    "Immaculate Heart of Mary Academy - Kitcharao, Inc",                            "CARAGA",       "Agusan del Norte",             "Kitcharao"                 },
                new string[] { "405912",    "Fr.Urios Academy of Magallanes, Inc.",                                         "CARAGA",       "Agusan del Norte",             "Magallanes"                },
                new string[] { "405917",    "Northwestern Agusan Colleges",                                                 "CARAGA",       "Agusan del Norte",             "Nasipit"                   },
                new string[] { "405919",    "Saint Michael College of Caraga",                                              "CARAGA",       "Agusan del Norte",             "Nasipit"                   },
                new string[] { "472021",    "Divine Word Manobo Cultural Development Academy Foundation, Inc.",             "CARAGA",       "Agusan del Sur",               "Bunawan"                   },
                new string[] { "600104",    "Agusan del Sur State College of Agriculture and Technology",                   "CARAGA",       "Agusan del Sur",               "Bunawan"                   },
                new string[] { "405824",    "Informatic Technological College of Bayugan City, Inc.",                       "CARAGA",       "Agusan del Sur",               "City of Bayugan"           },
                new string[] { "405921",    "Agusan del Sur College, Inc",                                                  "CARAGA",       "Agusan del Sur",               "City of Bayugan"           },
                new string[] { "405923",    "Father Saturnino Urios College of Bayugan Inc.",                               "CARAGA",       "Agusan del Sur",               "City of Bayugan"           },
                new string[] { "405924",    "Forest Hills Academy",                                                         "CARAGA",       "Agusan del Sur",               "City of Bayugan"           },
                new string[] { "405927",    "Mount Olive Laymen's Academy",                                                 "CARAGA",       "Agusan del Sur",               "City of Bayugan"           },
                new string[] { "405935",    "Monato Institute of Technology",                                               "CARAGA",       "Agusan del Sur",               "Prosperidad "              },
                new string[] { "405939",    "Philsaga High School Foundation, Inc.",                                        "CARAGA",       "Agusan del Sur",               "Rosario "                  },
                new string[] { "407679",    "AMA Computer Learning Center of Agusan Del Sur, Inc.",                         "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "404047",    "Saint Francis Xavier College, Inc.",                                           "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "404049",    "STI - San Francisco",                                                          "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "405823",    "Informatic Computer Institute of Agusan del Sur, Inc",                         "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "405940",    "Mt.Carmel College of San Francisco, Inc.",                                     "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "405944",    "San Francisco Colleges",                                                       "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "472036",    "Southway College of Technology",                                               "CARAGA",       "Agusan del Sur",               "San Francisco (Anao-Aon)"  },
                new string[] { "407577",    "Father Saturnino Urios College of Sibagat, Inc.",                              "CARAGA",       "Agusan del Sur",               "Sibagat"                   },
                new string[] { "405819",    "Asian Skills Academy Foundation, Inc.",                                        "CARAGA",       "Agusan del Sur",               "Trento"                    },
                new string[] { "405821",    "Computer Research Network, Inc.-Main Campus",                                  "CARAGA",       "Agusan del Sur",               "Trento"                    },
                new string[] { "405951",    "Father Saturnino Urios College of Trento, Inc.",                               "CARAGA",       "Agusan del Sur",               "Trento"                    },
                new string[] { "400591",    "Loreto Academy",                                                               "CARAGA",       "Dinagat Islands",              "Loreto"                    },
                new string[] { "400834",    "Don Jose Ecleo Memorial Foundation College of Science and Technology",         "CARAGA",       "Dinagat Islands",              "San Jose"                  },
                new string[] { "406016",    "Saint John's School",                                                          "CARAGA",       "Surigao del Norte",            "Bacuag"                    },
                new string[] { "404094",    "Siargao Island Institute of Technology",                                       "CARAGA",       "Surigao del Norte",            "Dapa"                      },
                new string[] { "405989",    "San Nicolas School",                                                           "CARAGA",       "Surigao del Norte",            "Dapa"                      },
                new string[] { "473013",    "Mt. Carmel School of Siargao, Inc.",                                           "CARAGA",       "Surigao del Norte",            "Del Carmen"                },
                new string[] { "600106",    "Surigao State College of Technology-Del Carmen",                               "CARAGA",       "Surigao del Norte",            "Del Carmen"                },
                new string[] { "406017",    "Saint Augustine Institute",                                                    "CARAGA",       "Surigao del Norte",            "Gigaquit"                  },
                new string[] { "407579",    "San Nicolas Academy",                                                          "CARAGA",       "Surigao del Norte",            "Mainit"                    },
                new string[] { "600281",    "Surigao State College of Technology-Mainit",                                   "CARAGA",       "Surigao del Norte",            "Mainit"                    },
                new string[] { "406030",    "San Nicolas High School",                                                      "CARAGA",       "Surigao del Norte",            "San Francisco (Anao-Aon)"  },
                new string[] { "404100",    "Bucas Grande Foundation College",                                              "CARAGA",       "Surigao del Norte",            "Socorro"                   },
                new string[] { "404086",    "STI College - Surigao",                                                        "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "406006",    "Northeastern Mindanao Colleges",                                               "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "406007",    "St. Paul University-Surigao",                                                  "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "406009",    "St. Jude Thaddeus Institute of Technology",                                    "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "406012",    "Surigao Education Center",                                                     "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "600280",    "Surigao State College of Technology",                                          "CARAGA",       "Surigao del Norte",            "Surigao City"              },
                new string[] { "406033",    "Mother of Mercy Academy",                                                      "CARAGA",       "Surigao del Sur",              "Barobo"                    },
                new string[] { "407582",    "Surigao Sur College - Barobo",                                                 "CARAGA",       "Surigao del Sur",              "Barobo"                    },
                new string[] { "406041",    "San Antonio School, Inc.",                                                     "CARAGA",       "Surigao del Sur",              "Cagwait"                   },
                new string[] { "600185",    "Surigao del Sur State University-Cagwait",                                     "CARAGA",       "Surigao del Sur",              "Cagwait"                   },
                new string[] { "406042",    "St. Michael College",                                                          "CARAGA",       "Surigao del Sur",              "Cantilan"                  },
                new string[] { "600109",    "Surigao del Sur State University-Cantilan",                                    "CARAGA",       "Surigao del Sur",              "Cantilan"                  },
                new string[] { "405829",    "Gaspar Rodriguez Educational and Training Center, Inc.",                       "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406035",    "Andres Soriano College of Bislig",                                             "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406036",    "De La Salle John Bosco College",                                               "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406038",    "Recaredo Castillo College",                                                    "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406039",    "Southern Technological Institute of the Philippines",                          "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406040",    "Saint Vincent De Paul Diocesan College",                                       "CARAGA",       "Surigao del Sur",              "City of Bislig"            },
                new string[] { "406055",    "Saint Theresa College of Tandag, Inc.",                                        "CARAGA",       "Surigao del Sur",              "City of Tandag"            },
                new string[] { "600282",    "Surigao del Sur State University-Main, Tandag",                                "CARAGA",       "Surigao del Sur",              "City of Tandag"            },
                new string[] { "406045",    "Diatagon Catholic High School",                                                "CARAGA",       "Surigao del Sur",              "Lianga"                    },
                new string[] { "600108",    "Surigao del Sur State University-Lianga",                                      "CARAGA",       "Surigao del Sur",              "Lianga"                    },
                new string[] { "407583",    "Surigao Sur College - Pagtilaan",                                              "CARAGA",       "Surigao del Sur",              "Lingig"                    },
                new string[] { "406047",    "Saint Michael's School",                                                       "CARAGA",       "Surigao del Sur",              "Madrid"                    },
                new string[] { "407580",    "Holy Child Academy",                                                           "CARAGA",       "Surigao del Sur",              "Marihatag"                 },
                new string[] { "407581",    "Saint Augustine High School",                                                  "CARAGA",       "Surigao del Sur",              "San Agustin"               },
                new string[] { "600186",    "Surigao del Sur State University-San Miguel",                                  "CARAGA",       "Surigao del Sur",              "San Miguel"                },
                new string[] { "407584",    "Surigao Sur College - Tagongon",                                               "CARAGA",       "Surigao del Sur",              "Tagbina"                   },
                new string[] { "474501",    "Surigao Sur College - Villaverde",                                             "CARAGA",       "Surigao del Sur",              "Tagbina"                   },
                new string[] { "406053",    "Purisima Diocesan School, Inc",                                                "CARAGA",       "Surigao del Sur",              "Tago"                      },

                #endregion  
            };
        }

    }
}
