using System;
using System.Collections.Generic;
using System.Text;

namespace Domain.Seed
{
    public class DBInitializerSchoolRegion7
    {
        public static List<string[]> AddDefaultSchools()
        {
            List<string[]> School = new List<string[]>
            {
                new string[] { "404233",    "Holy Infant Academy-Anda",             "REGION VII",   "Bohol",    "Anda" },
                new string[] { "404234",    "Christ the King Academy",              "REGION VII",   "Bohol",    "Antequera" },
                new string[] { "404235",    "Immaculata High School",               "REGION VII",   "Bohol",    "Baclayon" },
                new string[] { "407537",    "Carmel Academy",                       "REGION VII",   "Bohol",    "Balilihan" },
                new string[] { "600253",    "Bohol Island State University-Balilihan Campus",           "REGION VII",   "Bohol",    "Balilihan" },
                new string[] { "403511",    "Saint Anthony Academy",            "REGION VII",   "Bohol",    "Batuan" },
                new string[] { "405890",    "Batuan Colleges, Inc.",            "REGION VII",   "Bohol",    "Batuan" },
                new string[] { "404295",    "Bien Unido Academy",           "REGION VII",   "Bohol",    "Bien Unido" },
                new string[] { "404296",    "Holy Child Academy",           "REGION VII",   "Bohol",    "Bien Unido" },
                new string[] { "446533",    "Immaculate Mother School of Bilar, Inc.",          "REGION VII",   "Bohol",    "Bilar" },
                new string[] { "600070",    "Bohol Island State University-Bilar Campus",           "REGION VII",   "Bohol",    "Bilar" },
                new string[] { "403250",    "Buenavista Community College",             "REGION VII",   "Bohol",    "Buenavista" },
                new string[] { "406292",    "Artiaga's Learning Center Inc.",           "REGION VII",   "Bohol",    "Cadiz City" },
                new string[] { "600254",    "Bohol Island State University-Calape Campus",          "REGION VII",   "Bohol",    "Calape" },
                new string[] { "404239",    "St. Joseph Academy",           "REGION VII",   "Bohol",    "Candijay" },
                new string[] { "600071",    "Bohol Island State University-Candijay Campus",            "REGION VII",   "Bohol",    "Candijay" },
                new string[] { "407535",    "BIT International College-Carmen",             "REGION VII",   "Bohol",    "Carmen" },
                new string[] { "404241",    "Holy Infant Academy-Catigbian",            "REGION VII",   "Bohol",    "Catigbian" },
                new string[] { "404242",    "Immaculate Mary Academy",          "REGION VII",   "Bohol",    "Catigbian" },
                new string[] { "405889",    "Bohol Northwestern Colleges",          "REGION VII",   "Bohol",    "Catigbian" },
                new string[] { "446542",    "Presentation of Mary School of Clarin, Inc.",          "REGION VII",   "Bohol",    "Clarin" },
                new string[] { "600255",    "Bohol Island State University-Clarin Campus",          "REGION VII",   "Bohol",    "Clarin" },
                new string[] { "404243",    "Infant King Academy",          "REGION VII",   "Bohol",    "Cortes" },
                new string[] { "446510",    "Bohol International Learning Center",          "REGION VII",   "Bohol",    "Cortes" },
                new string[] { "446544",    "International Academe of Ensciema",            "REGION VII",   "Bohol",    "Dauis" },
                new string[] { "(Blank)",   "STI College Bohol, Inc.",          "REGION VII",   "Bohol",    "Dauis" },
                new string[] { "404244",    "Saint Nicholas Academy",           "REGION VII",   "Bohol",    "Dimiao" },
                new string[] { "404245",    "Immaculate Academy",           "REGION VII",   "Bohol",    "Duero" },
                new string[] { "404246",    "St. John the Baptist Academy",             "REGION VII",   "Bohol",    "Garcia-Hernandez" },
                new string[] { "404253",    "Santo Niño Institute",             "REGION VII",   "Bohol",    "Getafe" },
                new string[] { "404247",    "Saint Mary Academy",           "REGION VII",   "Bohol",    "Guindulman" },
                new string[] { "403270",    "Saint Paul's Academy",             "REGION VII",   "Bohol",    "Inabanga" },
                new string[] { "404249",    "BIT International College-Jagna",          "REGION VII",   "Bohol",    "Jagna" },
                new string[] { "404250",    "Central Visayan Institute Foundation",             "REGION VII",   "Bohol",    "Jagna" },
                new string[] { "404251",    "Colegio dela Medalla Milagrosa",           "REGION VII",   "Bohol",    "Jagna" },
                new string[] { "404252",    "San Miguel Academy, Bohol",            "REGION VII",   "Bohol",    "Jagna" },
                new string[] { "404282",    "Blessed Trinity College - A.R. of Talibon, Bohol, Inc.",           "REGION VII",   "Bohol",    "Kapawan" },
                new string[] { "407539",    "Holy Rosary Academy",          "REGION VII",   "Bohol",    "Lila" },
                new string[] { "407540",    "Holy Trinity Academy",             "REGION VII",   "Bohol",    "Loay" },
                new string[] { "404256",    "PMI-Loboc Academy",            "REGION VII",   "Bohol",    "Loboc" },
                new string[] { "404258",    "Saint Teresa Academy",             "REGION VII",   "Bohol",    "Loon" },
                new string[] { "404259",    "UB-Loon Institute",            "REGION VII",   "Bohol",    "Loon" },
                new string[] { "405738",    "Bohol College of Science and Technology, Inc.-Loon Campus",            "REGION VII",   "Bohol",    "Loon" },
                new string[] { "407541",    "Sacred Heart Academy",             "REGION VII",   "Bohol",    "Loon" },
                new string[] { "404260",    "Santa Monica Institute",           "REGION VII",   "Bohol",    "Mabini" },
                new string[] { "404262",    "Saint Vincent Institute",          "REGION VII",   "Bohol",    "Maribojoc" },
                new string[] { "404240",    "St. Anthony's Academy",            "REGION VII",   "Bohol",    "North Carmen" },
                new string[] { "403266",    "Cristal e-College",            "REGION VII",   "Bohol",    "Panglao" },
                new string[] { "404263",    "San Agustin Academy",          "REGION VII",   "Bohol",    "Panglao" },
                new string[] { "446505",    "Arbasto Foundation, Inc.",             "REGION VII",   "Bohol",    "Panglao" },
                new string[] { "446627",    "Panglao Christian Academy, Inc.",          "REGION VII",   "Bohol",    "Panglao" },
                new string[] { "404264",    "Virgen del Pilar Academy",             "REGION VII",   "Bohol",    "Pilar" },
                new string[] { "600308",    "Bohol College of Science and Technology, Inc.-Pilar Campus",           "REGION VII",   "Bohol",    "Pilar" },
                new string[] { "407538",    "Holy Child Academy of Pitogo, Bohol, Inc.",            "REGION VII",   "Bohol",    "President Carlos P. Garcia (Pitogo)" },
                new string[] { "600307",    "Bohol College of Science and Technology, Inc.-Main Campus",            "REGION VII",   "Bohol",    "Sagbayan" },
                new string[] { "404267",    "St. Augustine Institute of Sagbayan, Bohol Inc.",          "REGION VII",   "Bohol",    "Sagbayan (Borja)" },
                new string[] { "403554",    "STI College - Bohol",          "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404269",    "BIT International College-Tagbilaran",             "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404270",    "Bohol Wisdom School",          "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404272",    "Tagbilaran Grace Christian School",            "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404273",    "Holy Name University",             "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404274",    "Holy Spirit School of Tagbilaran",             "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404277",    "Royal Christian School",           "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404280",    "University of Bohol",          "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404281",    "Victoriano D. Tirol Advanced Learning Center",             "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "492001",    "Holy Infant School of Tagbilaran",             "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "492010",    "Immaculate Heart of Mary Seminary",            "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "492018",    "Schola Societas, Inc.",            "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "600022",    "Bohol Island State University-Main Campus",            "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "(Blank)",   "Cristal e-College",            "REGION VII",   "Bohol",    "Tagbilaran City" },
                new string[] { "404284",    "Bohol Maranatha Christian Academy, Inc.",          "REGION VII",   "Bohol",    "Talibon" },
                new string[] { "407536",    "BIT International College-Talibon",            "REGION VII",   "Bohol",    "Talibon" },
                new string[] { "404285",    "St. Isidore Academy of Trinidad",          "REGION VII",   "Bohol",    "Trinidad" },
                new string[] { "404286",    "Holy Cross Academy",           "REGION VII",   "Bohol",    "Tubigon" },
                new string[] { "404287",    "Holy Family of Nazareth School",           "REGION VII",   "Bohol",    "Tubigon" },
                new string[] { "404288",    "Salus Institute of Technology",            "REGION VII",   "Bohol",    "Tubigon" },
                new string[] { "446511",    "Mater Dei College",            "REGION VII",   "Bohol",    "Tubigon" },
                new string[] { "(Blank)",   "St. Pedro Calungsod College, Inc.",            "REGION VII",   "Bohol",    "Tubigon" },
                new string[] { "404289",    "Bohol Northeastern Education Foundation, Inc.",            "REGION VII",   "Bohol",    "Ubay" },
                new string[] { "404291",    "Holy Child Academy (Ubay)",            "REGION VII",   "Bohol",    "Ubay" },
                new string[] { "404293",    "San Pascual Academy",          "REGION VII",   "Bohol",    "Ubay" },
                new string[] { "405892",    "Montessori Educational Learning Center of Ubay, Inc.",             "REGION VII",   "Bohol",    "Ubay" },
                new string[] { "446513",    "Icthus Christian Academy, Inc.",           "REGION VII",   "Bohol",    "Ubay" },
                new string[] { "404297",    "Saint Augustine Academy, Inc.",            "REGION VII",   "Cebu",     "Alcantara" },
                new string[] { "404298",    "Saint Peter Academy of Alegria, Inc.",             "REGION VII",   "Cebu",     "Alegria" },
                new string[] { "447042",    "Saint Michael School",             "REGION VII",   "Cebu",     "Argao" },
                new string[] { "447062",    "Argao Center for Science Learning, Inc.",          "REGION VII",   "Cebu",     "Argao" },
                new string[] { "600256",    "Cebu Technological University-Argao Campus",           "REGION VII",   "Cebu",     "Argao" },
                new string[] { "447104",    "Isler Superior High, Inc.",            "REGION VII",   "Cebu",     "Asturias" },
                new string[] { "404301",    "Saint James Academy",          "REGION VII",   "Cebu",     "Badian" },
                new string[] { "404303",    "St. Francis Academy",          "REGION VII",   "Cebu",     "Balamban" },
                new string[] { "447054",    "Little Angels Montessori School of Cebu Inc.",             "REGION VII",   "Cebu",     "Balamban" },
                new string[] { "447087",    "University of San Jose-Recoletos Balamban Campus",             "REGION VII",   "Cebu",     "Balamban" },
                new string[] { "403292",    "Saint Paul Academy Inc.",          "REGION VII",   "Cebu",     "Bantayan" },
                new string[] { "404305",    "Bantayan Southern Institute",          "REGION VII",   "Cebu",     "Bantayan" },
                new string[] { "404313",    "Sta. Ana Academy of Barili, Inc.",             "REGION VII",   "Cebu",     "Barili" },
                new string[] { "406554",    "Santa Anna Academy of Barili, Inc.",           "REGION VII",   "Cebu",     "Barili" },
                new string[] { "600257",    "Cebu Technological University-Barili",             "REGION VII",   "Cebu",     "Barili" },
                new string[] { "447075",    "Patronage of Mary Development School",             "REGION VII",   "Cebu",     "Boljoon" },
                new string[] { "404319",    "Don Emilio Osmeña Memorial School",            "REGION VII",   "Cebu",     "Borbon" },
                new string[] { "404327",    "Cebu Academy",             "REGION VII",   "Cebu",     "Carmen" },
                new string[] { "407661",    "St. Joseph's Academy, Carmen, Cebu, Inc.",             "REGION VII",   "Cebu",     "Carmen" },
                new string[] { "600258",    "Cebu Technological University-Carmen Campus",          "REGION VII",   "Cebu",     "Carmen" },
                new string[] { "404328",    "Gabriel Jurado Foundation School, Inc.",           "REGION VII",   "Cebu",     "Catmon" },
                new string[] { "404329",    "Passionist Sister's School (Catmon), Inc.",            "REGION VII",   "Cebu",     "Catmon" },
                new string[] { "447099",    "Saint William Cooperative School",             "REGION VII",   "Cebu",     "Catmon" },
                new string[] { "403297",    "AMA Computer College, Inc.-Cebu City",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403314",    "Blessed John XXIII Seminary",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403319",    "CBD Institute of Learning, Inc",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403323",    "College of Technological Sciences",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403330",    "Informatics College Cebu, Inc.",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403336",    "International School for Culinary Arts and Hotel Mgt.-Cebu",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403341",    "Rizwoods Colleges-Sambag",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403342",    "Rogationist Seminary College - Cebu",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403349",    "STI College - Cebu",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403351",    "University of Cebu - Banilad Branch",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403355",    "University of Cebu - Main Campus",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "403365",    "University of Cebu - METC Branch",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404026",    "Colegio de la Inmaculada Concepcion",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404364",    "St. Paul School of Medellin, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404419",    "Lyceum of Cebu",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404423",    "Cebu Bradford School",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404424",    "Cebu Cherish School, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404428",    "Cebu International Distance Education College",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404432",    "Centre for International Education Global Colleges",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404441",    "Harvest Christian School International of Cebu, Inc.",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404443",    "Living Word Christian Learning Center of Cebu, Inc.",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404444",    "Mabolo Christian Academy",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404447",    "Marie Ernestine School",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404449",    "Matilda L. Bradford Christian School, Inc.",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404452",    "PAREF Southcrest School, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404453",    "PAREF Springdale School, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404454",    "Philippine Christian Gospel School",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404456",    "Pope John XXIII Seminary School",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404458",    "Sacred Heart-Hijas de Jesus",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404459",    "Samantabhadra Educational Institute, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404460",    "San Isidro Parish School",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404462",    "Southwestern University",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404465",    "St. Theresa's College-Cebu",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404472",    "University of San Carlos Basic Education Deparment - North Campus",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404474",    "University of Southern Philippines Foundation-Mabini",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404475",    "University of Southern Philippines Foundation-Lahug",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404476",    "University of the Visayas-Main Campus",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404477",    "Visayan Nazarene Bible College",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404478",    "Woodridge International School",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404480",    "Bethany Christian School",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404482",    "Bob Hughes Christian Academy",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404483",    "CBD College",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404485",    "Cebu Eastern College",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404486",    "Cebu Institute of Technology University",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404488",    "Child Learning Foundation Inc.",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404489",    "Childlink Learning Center and Childlink High School Inc",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404491",    "Evangelical Theological College of the Philippines, Inc.",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404492",    "Concord Technical Institute, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404493",    "Don Bosco Technology Center, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404495",    "Holy Rosary School of Pardo",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404500",    "Marianne Childhood Education Center",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404501",    "M-Zed Christian School",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404507",    "Royal Oaks International School-Cebu City",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404508",    "SAE Young Christian School",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404511",    "St. Francis of Assissi School",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404513",    "St. Mary's Academy of San Nicolas",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404514",    "St. Paul College Foundation, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404515",    "St. Paul Learning Center, Inc.",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404516",    "University of San Jose-Recoletos",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "405739",    "Asian Institute of Computer Studies - Cebu",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "405740",    "Britech College",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "405742",    "School of Knowledge for Industrial Labor, Leadership and Service (SKILLS)",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406299",    "International Institute of Technology and Management-Cebu, Inc.",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406310",    "ISHRM School-Cebu",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406568",    "Banilad Center for Professional Development",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406579",    "CITE Technical Institute",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406709",    "FBC Christian School",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "406848",    "Datamex Institute of Computer Technology-Cebu City",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "407546",    "University of San Carlos - Basic Education Department South Campus",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "407547",    "University of the Visayas-Pardo Campus",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "407663",    "Salazar Colleges of Science and Institute of Technology-Main Campus",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447145",    "Mary Our Help Technical Institute for Women, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447510",    "Cebu Mary Immaculate College - Talamban",          "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447511",    "Maria Montessori International School",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447512",    "B.R.I.G.H.T. Academy",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447527",    "Maranatha Christian Academy, Inc. of Cebu",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447534",    "Golden Success College, Inc.",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447550",    "Asian College of Technology-International Education Foundation-AIS-Cebu City",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447552",    "Saint Paul College Foundation, Inc.- Ramos Campus",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447562",    "Saint Anthony Montessori Learning Center, Inc",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "447564",    "Three H Redwood Academy, Inc.",            "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "600263",    "Cebu Technological University-Main",           "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "600332",    "University of the Philippines High School - Cebu",             "REGION VII",   "Cebu",     "Cebu City" },
                new string[] { "404315",    "Cebu Roosevelt Memorial Colleges",             "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "404316",    "Felipe R. Verallo Memorial Foundation College",            "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "404317",    "Northern Cebu Colleges",           "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "404318",    "St. Louise de Marillac College of Bogo",           "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "447030",    "San Roque Child Development Center - Bogo Campus",             "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "(Blank)",   "Araneta Learning Center for Child Development, Inc.",          "REGION VII",   "Cebu",     "City of Bogo" },
                new string[] { "404320",    "Carcar Academy Technical School Inc.",             "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "404323",    "Mother Mary's Children School",            "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "404324",    "St. Catherine's College",          "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "406549",    "Datamex Institute of Computer Technology-Carcar City",             "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "407677",    "Carcar City College",          "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "447011",    "St. Elijah Christian Institute of Technology Foundation, Inc.",            "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "447021",    "Cebu Sacred Heart College, Inc. - Carcar Campus",          "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "447089",    "St. Teresa's School of Valladolid",            "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "447090",    "Eastside Christian Academy",           "REGION VII",   "Cebu",     "City of Carcar" },
                new string[] { "403445",    "Professional Academy of the Philippines",          "REGION VII",   "Cebu",     "City of Naga" },
                new string[] { "403449",    "Academia de San Pedro Calungsod",          "REGION VII",   "Cebu",     "City of Naga" },
                new string[] { "447014",    "Exceed Learning Center Naga, Cebu Inc.",           "REGION VII",   "Cebu",     "City of Naga" },
                new string[] { "447035",    "Bethel Christian Living Heritage School",          "REGION VII",   "Cebu",     "City of Naga" },
                new string[] { "403555",    "Saint Scholastica's Academy",          "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404394",    "Cherubs Academy, Inc.",            "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404395",    "Divino Amore Academy",             "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404402",    "Monterey School Inc.",             "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404403",    "Cebu Sacred Heart College Inc.",           "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404409",    "Saint Teresa's School",            "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404410",    "St. Thomas Aquinas School Of Lawa-An (Montessori) Inc.",           "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404414",    "Talisay Malayan Academy",          "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "406587",    "ABQ International Health Caregiver Program and Consultancy Incorporation",             "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "406710",    "Adventist Academy - Cebu, Inc.",           "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "407550",    "Asian College of Technology-Bulacao Campus",           "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "407589",    "St. Scholastica's Academy",            "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "492502",    "Sisters of Mary School-Girlstown, Inc.",           "REGION VII",   "Cebu",     "City of Talisay" },
                new string[] { "404331",    "University of the Visayas-Compostela Campus",          "REGION VII",   "Cebu",     "Compostela" },
                new string[] { "(Blank)",   "Saint James Technical Skills College, Inc.",           "REGION VII",   "Cebu",     "Compostela" },
                new string[] { "404335",    "Paraclete Learning Center",            "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "404337",    "Sotero B. Cabahug Forum For Literacy",             "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "404357",    "Livingstone Christian Academy, Inc.",          "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "406553",    "Informatics College Cebu Inc. - Consolacion",          "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "407662",    "Consolacion Community College",            "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "447015",    "Our Lady of Rule Catholic Learning School, Inc.",          "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "447056",    "Dominican School, Cebu",           "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "(Blank)",   "Schildknecht School, Inc.",            "REGION VII",   "Cebu",     "Consolacion" },
                new string[] { "404339",    "Cordova Catholic Cooperative School",          "REGION VII",   "Cebu",     "Cordova" },
                new string[] { "447044",    "San Roque Child Development School-East Campus",           "REGION VII",   "Cebu",     "Cordova" },
                new string[] { "447066",    "Benthel Asia School of Technology, Inc. - Cordova Campus",             "REGION VII",   "Cebu",     "Cordova" },
                new string[] { "447077",    "Saint Dominic Savio School of Lapu-Lapu City, Inc.-Cordova Branch",            "REGION VII",   "Cebu",     "Cordova" },
                new string[] { "404344",    "St. Martin de Porres Academy",             "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "447012",    "Constancio P. Go Memorial Learning Center",            "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "447033",    "Dover Academic Center for Excellence, Inc",            "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "447064",    "Integrated Science School-Cebu Branch, Inc.",          "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "447082",    "St. Isidore Labrador Child Development Center, Inc.",          "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "600259",    "Cebu Technological University-Daanbantayan Campus",            "REGION VII",   "Cebu",     "Daanbantayan" },
                new string[] { "404345",    "St. Mary's Academy of Dalaguete, Cebu, Inc.",          "REGION VII",   "Cebu",     "Dalaguete" },
                new string[] { "407544",    "University of the Visayas-Dalaguete Campus",           "REGION VII",   "Cebu",     "Dalaguete" },
                new string[] { "404347",    "Hosanna Learning Center, Inc.",            "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "404350",    "St. Thomas Learning Center Foundation Inc.",           "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "404351",    "Sto. Tomas College",           "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "404352",    "University of the Visayas-Danao Campus",           "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "405946",    "Colegio de San Antonio de Padua",          "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "491502",    "Northeastern Cebu Colleges, Inc.",             "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "491503",    "Padre Pio Child Development School Inc.",          "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "491507",    "Rosemont Hills Montessori College",            "REGION VII",   "Cebu",     "Danao City" },
                new string[] { "404353",    "Little Flower School, Inc.",           "REGION VII",   "Cebu",     "Dumanjug" },
                new string[] { "407542",    "Holy Trinity College",             "REGION VII",   "Cebu",     "Ginatilan" },
                new string[] { "400846",    "San Lorenzo Ruiz School",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "403416",    "Rizwoods Colleges-Maribago",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404538",    "Advance Institute of Technology, Inc.",            "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404539",    "Asian Learning Center (Pajo Branch)",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404542",    "Cebu Christian Institute International",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404545",    "EMD Carmelite Foundation School, Inc. (Main Campus)",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404548",    "Indiana Learning Center",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404553",    "Nissi Academy, Inc.",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404556",    "St. Alphonsus Catholic School Inc.",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404558",    "Saint Dominic Savio School of Lapu-Lapu City, Inc.-Main Branch",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404560",    "St. Joseph's School of Mactan, Inc.",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "405743",    "ELE Technical Training Center and Recruitment Agency Corporation",             "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "405897",    "Benthel Asia School of Technology, Inc. - Lapu-Lapu City Campus",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "405913",    "Proverbs Ville Academy, Inc.",             "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "407588",    "Marie Ernestine School",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "448509",    "EMD Carmelite Foundation School, Inc. (East Campus)",          "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "448511",    "Regent Pacific College",           "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "448515",    "Dr. Caridad C. Labe Education Center of Excellence (CCL Centrex Inc.)",            "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "448519",    "Sto. Niño Mactan Montessori School, Inc.",             "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "448521",    "(New) Saint Andrew School",            "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "(Blank)",   "Flight Dynamics School of Aeronautics",            "REGION VII",   "Cebu",     "Lapu-Lapu City (Opon)" },
                new string[] { "404332",    "Adonai Asian Academy",             "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "404355",    "La Consolacion College-Liloan",            "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "404358",    "San Roque College de Cebu (Formerly San Roque Child Development School)",          "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "407445",    "Trade-Tech International Science Institute",           "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "407785",    "Britech College, Inc.",            "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "447007",    "Academia del Christifidelis",          "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "447057",    "Divine Life Institute of Cebu, Inc",           "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "447141",    "GT Northeast Academy, Inc.",           "REGION VII",   "Cebu",     "Liloan" },
                new string[] { "403283",    "Madridejos Community College",             "REGION VII",   "Cebu",     "Madridejos" },
                new string[] { "404361",    "Villacarlos Academy",          "REGION VII",   "Cebu",     "Madridejos" },
                new string[] { "447059",    "Cebu Northplains College, Inc.",           "REGION VII",   "Cebu",     "Madridejos" },
                new string[] { "447068",    "Salazar Colleges of Science and Technology",           "REGION VII",   "Cebu",     "Madridejos" },
                new string[] { "404362",    "Perpetual Succour Academy, Inc.",          "REGION VII",   "Cebu",     "Malabuyoc" },
                new string[] { "403433",    "ACLC College of Mandaue",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "403439",    "Colegio de la Inmaculada Concepcion- Mandaue",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "403444",    "University of the Visayas-Mandaue Campus",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "404573",    "Mandaue Christian School",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "404580",    "Royal Oaks International School-Mandaue City",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "404585",    "Saint Louis College - Cebu",           "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "404587",    "University of Cebu - Lapu-Lapu-Mandaue Campus",            "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "404589",    "Fervent Academy, Inc.",            "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "405831",    "Datamex Institute of Computer Technology-Mandaue City",            "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "405834",    "Center for Healthcare Professions Cebu, Inc.",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "405926",    "Saint Paul College Foundation, Inc.",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "406029",    "Cebu Doctors' University",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "407548",    "St. Joseph's Academy",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "407635",    "Royal Christian College",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "407665",    "Mandaue City College",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "449020",    "Sacred Heart School - Ateneo de Cebu",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "449022",    "Inchland Academy",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "449024",    "Benedicto College",            "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "449025",    "SPM Academy, Inc.",            "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "449027",    "Larmen de Guia Memorial College",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "(Blank)",   "Intellisense Institute of Technology",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "(Blank)",   "Mandaue Christian School",             "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "(Blank)",   "Philippine Technical and Allied Courses",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "(Blank)",   "Saint Anne Learning Center of Mandaue, Inc.",          "REGION VII",   "Cebu",     "Mandaue City" },
                new string[] { "403284",    "Mary's Children Formation College Foundation, Inc.",           "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "404367",    "Mary Help of Christians School (Cebu), Inc.",          "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "404369",    "St. Cecilia's College",            "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "407543",    "Immaculate Heart of Mary Academy",             "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "407545",    "University of the Visayas-Minglanilla Campus",             "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "447001",    "Sisters of Mary School-Boystown, Inc.",            "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "447016",    "Southern Bethany Christian School of Minglanilla, Inc",            "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "447074",    "Montessori Academy of Southern Cebu, Inc.",            "REGION VII",   "Cebu",     "Minglanilla" },
                new string[] { "404372",    "Our Lady of Mount Carmel Learning Center, Inc.",           "REGION VII",   "Cebu",     "Moalboal" },
                new string[] { "404373",    "San Juan High School of Moalboal, Cebu Inc.",          "REGION VII",   "Cebu",     "Moalboal" },
                new string[] { "600260",    "Cebu Technological University-Moalboal Campus",            "REGION VII",   "Cebu",     "Moalboal" },
                new string[] { "403346",    "Sta. Monica Academy",          "REGION VII",   "Cebu",     "Pinamungahan" },
                new string[] { "403290",    "Mt. Moriah College",           "REGION VII",   "Cebu",     "Poro" },
                new string[] { "404377",    "Camotes Visayan Institute",            "REGION VII",   "Cebu",     "Poro" },
                new string[] { "447003",    "Camotes Hillside Academy, Inc.",           "REGION VII",   "Cebu",     "Poro" },
                new string[] { "403295",    "Saint Pius X School of Samboan Inc.",          "REGION VII",   "Cebu",     "Samboan" },
                new string[] { "404383",    "Notre Dame Academy of San Fernando, Cebu, Inc.",           "REGION VII",   "Cebu",     "San Fernando" },
                new string[] { "447125",    "Inchland Academy",             "REGION VII",   "Cebu",     "San Fernando" },
                new string[] { "404385",    "Campillo Progressive School, Inc.",            "REGION VII",   "Cebu",     "San Francisco" },
                new string[] { "407025",    "Lyceum of Cebu",           "REGION VII",   "Cebu",     "Santander" },
                new string[] { "404388",    "Our Lady of the Pillar Academy-Sibonga",           "REGION VII",   "Cebu",     "Sibonga" },
                new string[] { "447037",    "Our Lady of Lindogon Foundation, Inc.",            "REGION VII",   "Cebu",     "Sibonga" },
                new string[] { "404389",    "Juan Dosado Memorial School, Inc.",            "REGION VII",   "Cebu",     "Sogod" },
                new string[] { "447050",    "Sto. Niño Smart Child Learning Center, Inc.",          "REGION VII",   "Cebu",     "Sogod" },
                new string[] { "404390",    "Tabogon Roosevelt High School",            "REGION VII",   "Cebu",     "Tabogon" },
                new string[] { "404637",    "De La Salle Andres Soriano Memorial College",          "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "404639",    "Consolatrix College of Toledo City, Inc.",             "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "404640",    "Leaton School",            "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "404641",    "University of the Visayas-Toledo Campus",          "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "404642",    "West Bay Learning Center, Inc.",           "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "450502",    "St. Bernardinus for Educational Advancement Foundation, Inc.",             "REGION VII",   "Cebu",     "Toledo City" },
                new string[] { "404417",    "St. Anthony's Academy of Tuburan, Inc.",           "REGION VII",   "Cebu",     "Tuburan" },
                new string[] { "600261",    "Cebu Technological University-Tuburan",            "REGION VII",   "Cebu",     "Tuburan" },
                new string[] { "404418",    "Immaculate Conception Institute of Tudela, Inc.",          "REGION VII",   "Cebu",     "Tudela" },
                new string[] { "404575",    "Mandaue Technical Institute",          "REGION VII",   "Mandaue City",     "Mandaue City" },
                new string[] { "404633",    "Quezon Memorial Institute of Siquijor, Inc.",          "REGION VII",   "Siquijor",     "Canal" },
                new string[] { "404626",    "St. Vincent Academy of Larena Siquijor, Inc.",             "REGION VII",   "Siquijor",     "Larena" },
                new string[] { "600036",    "Siquijor State College",           "REGION VII",   "Siquijor",     "Larena" },
                new string[] { "404635",    "St. Isidore the Farmer Catholic School, Lazi, Siquijor, Inc.",             "REGION VII",   "Siquijor",     "Lazi" },
                new string[] { "404630",    "St. John High School of San Juan Siquijor, Inc.",          "REGION VII",   "Siquijor",     "San Juan" },
                new string[] { "403521",    "Carmelite College",            "REGION VII",   "Siquijor",     "Siquijor" },
                new string[] { "404629",    "Ave Maria Academy",            "REGION VII",   "Siquijor",     "Siquijor" },
                new string[] { "404631",    "Assisi High School",           "REGION VII",   "Siquijor",     "Siquijor" },
                new string[] { "404632",    "BIT International College-Siquijor",           "REGION VII",   "Siquijor",     "Siquijor" },
            };
            return School;
        }
    }
}